### DISCUSSION TITLE
Local copy with Docker Compose

### DISCUSSION THREAD

**Discussion by Brand2** [zitadel/zitadel#3079] [Q&A]
Hi again,

I just wanted to share here where I'm at with getting a local copy (using a stable built image) working with Docker Compose. I have based this off of the `docker-compose-local.yml` file you have under `build/local`. I've got the following directories in place prior to starting:

- A `.keys` folder containing a pre-populated `local_keys.yml` file
- A `.notifications` folder for storing notifications
- A cloned copy of the repo (for running database migrations) under `zitadel`
- A `cockroach-data` folder to persist my CockroachDB data

I have a `Dockerfile.clientid` and `clientid.sh` files too, based on the same files from `build/local` in the repo which copies the client ID into `environment.json`. `environment.json` looks like the following initially:

```json
{
  "authServiceUrl": "http://localhost:50000",
  "mgmtServiceUrl": "http://localhost:50000",
  "adminServiceUrl": "http://localhost:50000",
  "issuer": "http://localhost:50002/oauth/v2",
  "clientid": "client@zitadel"
}
```

I have a Docker Compose file with the following content:

```yaml
version: '3.8'

services:
  db:
    profiles: ['backend', 'storage']
    restart: always
    networks:
      - zitadel
    image: cockroachdb/cockroach:v21.2.3
    volumes:
      - "${PWD}/cockroach-data:/cockroach/cockroach-data"
    command: start-single-node --insecure --listen-addr=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 8080:8080
      - 26257:26257

# schema changes on the database
  db-migrations:
    profiles: ['backend', 'storage']
    restart: on-failure
    networks:
      - zitadel
    depends_on:
      db:
        condition: service_healthy
    image: flyway/flyway:latest
    volumes:
      - ./zitadel/migrations/cockroach:/flyway/sql
    environment:
      - FLYWAY_PLACEHOLDERS_eventstorepassword=NULL
      - FLYWAY_PLACEHOLDERS_managementpassword=NULL
      - FLYWAY_PLACEHOLDERS_adminapipassword=NULL
      - FLYWAY_PLACEHOLDERS_authpassword=NULL
      - FLYWAY_PLACEHOLDERS_notificationpassword=NULL
      - FLYWAY_PLACEHOLDERS_authzpassword=NULL
      - FLYWAY_PLACEHOLDERS_queriespassword=NULL
    command: -url=jdbc:postgresql://db:26257/defaultdb -user=root -password= -connectRetries=5 migrate
# minio is used to store assets
  minio:
    profiles: ['backend', 'storage']
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    restart: on-failure
    networks:
      - zitadel
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    command:
      - gateway
      - nas
      - /export

# To interact with ZITADEL requires some data setted up.
# Due to the evolution of ZITADEL it's required to add additional
# setup steps, because of this fact it's recommended to rerun the setup
# on each restart, at least after a new version got released
  backend-setup:
    image: ghcr.io/caos/zitadel:1.72.1
    profiles: ['backend']
    restart: on-failure
    networks:
      - zitadel
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    volumes:
      - .keys:/.keys
      - .notifications:/.notifications
    env_file:
      - ./local.env
    environment:
      - ZITADEL_EVENTSTORE_HOST=db
    command:
      [
        'setup',
      ]
# starts the backend (API's) of ZITADEL
# Port 50001 serves the GRPC API
# Port 50002 serves the REST API
# Port 50003 serves the login GUI
  backend-run:
    image: ghcr.io/caos/zitadel:1.72.1
    profiles: ['backend']
    restart: on-failure
    networks:
      - zitadel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50002/management/v1/healthz"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      backend-setup:
        condition: service_completed_successfully
    env_file:
      - ./local.env
    volumes:
      - .keys:/.keys
      - .notifications:/.notifications
      - "./environment.json:/console/assets/environment.json"
    environment:
      - ZITADEL_EVENTSTORE_HOST=db
    ports:
      - 50001:50001
      - 50002:50002
      - 50003:50003
    command:
      [
        'start'
      ]
# this service generates the environemnt.json
# needed in console.
# It curl's the client id of console and writes it to
# the environment.json
  client-id:
    profiles: ['frontend', 'console-stub']
    networks:
      - zitadel
    build:
      context: .
      dockerfile: Dockerfile.clientid
      target: client-id
    volumes:
      - ./environment.json:/environment.json
    environment:
      - HOST=backend-run
      - PORT=50002
networks:
  zitadel: {}
```

And a `local.env` file with the following content:

```
#tracing is disabled locally
ZITADEL_TRACING_TYPE=none
#metrics is disabled locally
ZITADEL_METRICS_TYPE=none

#recommended log level for local is debug
ZITADEL_LOG_LEVEL=debug

#database connection (cockroach insecure)
ZITADEL_EVENTSTORE_HOST=localhost
ZITADEL_EVENTSTORE_PORT=26257
CR_SSL_MODE=disable

#keys for cryptography
ZITADEL_KEY_PATH=.keys/local_keys.yaml
ZITADEL_USER_VERIFICATION_KEY=userverificationkey_1
ZITADEL_OTP_VERIFICATION_KEY=OTPVerificationKey_1
ZITADEL_OIDC_KEYS_ID=oidckey_1
ZITADEL_COOKIE_KEY=cookiekey_1
ZITADEL_CSRF_KEY=cookiekey_1
ZITADEL_IDP_CONFIG_VERIFICATION_KEY=idpconfigverificationkey_1
ZITADEL_DOMAIN_VERIFICATION_KEY=domainverificationkey_1

#debug mode is used for notifications
DEBUG_MODE=true
#used in the oidc library
#true enables usage of (insecure) http for localhost as issuer
CAOS_OIDC_DEV=true
#sets the cookies insecure in login (never use this in production!)
ZITADEL_CSRF_DEV=true
LOG_NOTIFICATIONS_ENABLED=true
LOG_NOTIFICATIONS_COMPACT=true
FS_NOTIFICATIONS_ENABLED=true
FS_NOTIFICATIONS_PATH=./.notifications
FS_NOTIFICATIONS_COMPACT=false
CHAT_ENABLED=false

#configuration for api/browser calls
ZITADEL_DEFAULT_DOMAIN=localhost
ZITADEL_ISSUER=http://localhost:50002/oauth/v2
ZITADEL_ACCOUNTS=http://localhost:50003/login
ZITADEL_AUTHORIZE=http://localhost:50002/oauth/v2
ZITADEL_OAUTH=http://localhost:50002/oauth/v2
ZITADEL_CONSOLE=http://localhost:50003
ZITADEL_COOKIE_DOMAIN=localhost
ZITADEL_API_DOMAIN=http://localhost:50002

#caching is used in UI's and API's
ZITADEL_CACHE_MAXAGE=12h
ZITADEL_CACHE_SHARED_MAXAGE=168h
ZITADEL_SHORT_CACHE_MAXAGE=5m
ZITADEL_SHORT_CACHE_SHARED_MAXAGE=15m

#console authorization configuration
ZITADEL_CONSOLE_RESPONSE_TYPE=CODE
ZITADEL_CONSOLE_GRANT_TYPE=AUTHORIZATION_CODE

ZITADEL_CONSOLE_DIR=/console/

#minio configuration
ZITADEL_ASSET_STORAGE_ACCESS_KEY_ID=access_key
ZITADEL_ASSET_STORAGE_SECRET_ACCESS_KEY=secret_key
ZITADEL_ASSET_STORAGE_TYPE=s3
ZITADEL_ASSET_STORAGE_ENDPOINT=minio:9000
ZITADEL_ASSET_STORAGE_BUCKET_PREFIX=local
```

My environment is able to start up, and I can see the server is receiving my requests. However, when I try to go to the console (at `http://localhost:50003`) I end up with a 404 page not found error. Is there some critical piece of information I'm missing about serving the console from the container? Or have I missed something else? Help would be much appreciated, and I would be very happy to contribute the setup (after I've removed the need to run the migrations from the repo cloned directly) to help others trying to get a local copy (not from source) running.

**Comment by Brand2** [comment]
I've narrowed this down to the fact that the console's handler always starts at the `/console` prefix (see [here](https://github.com/caos/zitadel/blob/f485a52d9aad83d3c0c9c4bcd1cfaf60e2a4504c/internal/ui/console/console.go#L28)) and when you go to `/console`, the `index.html` which gets served back looks for files under the `/` path which the HTTP server does not return. Is there some way to make it properly retrieve the static files (JS, assets, etc.) that I've missed? Otherwise it seems like it starts in a way where components will never be correctly returned, as there's no handler for the `/` prefix.

**Comment by Brand2** [comment]
Final update before I call it a night. I got around the previous issue of not getting any of the content by sticking an Nginx container in front of everything with the following configuration (to proxy requests for static content to the path that the upstream understands):

```
server {
    listen 80;
    server_name dev.localhost;

    location / {
        add_header Access-Control-Allow-Origin *;
        rewrite /(.*) /console/$1 break;
        proxy_pass http://backend-run:50003;
        proxy_set_header Host $host;
    }

    location /login {
        proxy_pass http://backend-run:50003;
        proxy_set_header Host $host;
    }

    location /assets/environment.json {
        return 200 '{"authServiceUrl": "http://localhost:50000", "mgmtServiceUrl": "http://localhost:50000", "adminServiceUrl": "http://localhost:50000", "issuer": "http://dev.localhost:50002/oauth/v2", "clientid": "145015849378447365@zitadel"}';
    }
}
```

This makes most everything work so long as I'm accessing things at say `dev.localhost` instead of `localhost` directly, so my `local.env` now looks like the following:

```
#tracing is disabled locally
ZITADEL_TRACING_TYPE=none
#metrics is disabled locally
ZITADEL_METRICS_TYPE=none

#recommended log level for local is debug
ZITADEL_LOG_LEVEL=trace

#database connection (cockroach insecure)
ZITADEL_EVENTSTORE_HOST=localhost
ZITADEL_EVENTSTORE_PORT=26257
CR_SSL_MODE=disable

#keys for cryptography
ZITADEL_KEY_PATH=.keys/local_keys.yaml
ZITADEL_USER_VERIFICATION_KEY=userverificationkey_1
ZITADEL_OTP_VERIFICATION_KEY=OTPVerificationKey_1
ZITADEL_OIDC_KEYS_ID=oidckey_1
ZITADEL_COOKIE_KEY=cookiekey_1
ZITADEL_CSRF_KEY=cookiekey_1
ZITADEL_IDP_CONFIG_VERIFICATION_KEY=idpconfigverificationkey_1
ZITADEL_DOMAIN_VERIFICATION_KEY=domainverificationkey_1

#debug mode is used for notifications
DEBUG_MODE=true
#used in the oidc library
#true enables usage of (insecure) http for localhost as issuer
CAOS_OIDC_DEV=true
#sets the cookies insecure in login (never use this in production!)
ZITADEL_CSRF_DEV=true
LOG_NOTIFICATIONS_ENABLED=true
LOG_NOTIFICATIONS_COMPACT=true
FS_NOTIFICATIONS_ENABLED=true
FS_NOTIFICATIONS_PATH=./.notifications
FS_NOTIFICATIONS_COMPACT=false
CHAT_ENABLED=false

#configuration for api/browser calls
ZITADEL_DEFAULT_DOMAIN=localhost
ZITADEL_ISSUER=http://dev.localhost:50002/oauth/v2
ZITADEL_ACCOUNTS=http://dev.localhost:50003/login
ZITADEL_AUTHORIZE=http://dev.localhost:50002/oauth/v2
ZITADEL_OAUTH=http://dev.localhost:50002/oauth/v2
ZITADEL_CONSOLE=http://dev.localhost:50003/console
ZITADEL_COOKIE_DOMAIN=localhost
ZITADEL_API_DOMAIN=http://dev.localhost:50002

#caching is used in UI's and API's
ZITADEL_CACHE_MAXAGE=12h
ZITADEL_CACHE_SHARED_MAXAGE=168h
ZITADEL_SHORT_CACHE_MAXAGE=5m
ZITADEL_SHORT_CACHE_SHARED_MAXAGE=15m

#console authorization configuration
ZITADEL_CONSOLE_RESPONSE_TYPE=CODE
ZITADEL_CONSOLE_GRANT_TYPE=AUTHORIZATION_CODE

ZITADEL_CONSOLE_DEV_MODE=true
# ZITADEL_CONSOLE_DIR=/

#minio configuration
ZITADEL_ASSET_STORAGE_ACCESS_KEY_ID=access_key
ZITADEL_ASSET_STORAGE_SECRET_ACCESS_KEY=secret_key
ZITADEL_ASSET_STORAGE_TYPE=s3
ZITADEL_ASSET_STORAGE_ENDPOINT=minio:9000
ZITADEL_ASSET_STORAGE_BUCKET_PREFIX=local
```

And my Docker Compose file:

```
version: '3.8'

services:
  db:
    profiles: ['backend', 'storage']
    restart: always
    networks:
      - zitadel
    image: cockroachdb/cockroach:v21.2.3
    volumes:
      - "${PWD}/cockroach-data:/cockroach/cockroach-data"
    command: start-single-node --insecure --listen-addr=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 8080:8080
      - 26257:26257

# schema changes on the database
  db-migrations:
    profiles: ['backend', 'storage']
    restart: on-failure
    networks:
      - zitadel
    depends_on:
      db:
        condition: service_healthy
    image: flyway/flyway:latest
    volumes:
      - ./zitadel/migrations/cockroach:/flyway/sql
    environment:
      - FLYWAY_PLACEHOLDERS_eventstorepassword=NULL
      - FLYWAY_PLACEHOLDERS_managementpassword=NULL
      - FLYWAY_PLACEHOLDERS_adminapipassword=NULL
      - FLYWAY_PLACEHOLDERS_authpassword=NULL
      - FLYWAY_PLACEHOLDERS_notificationpassword=NULL
      - FLYWAY_PLACEHOLDERS_authzpassword=NULL
      - FLYWAY_PLACEHOLDERS_queriespassword=NULL
    command: -url=jdbc:postgresql://db:26257/defaultdb -user=root -password= -connectRetries=5 migrate
# minio is used to store assets
  minio:
    profiles: ['backend', 'storage']
    image: minio/minio:RELEASE.2021-06-14T01-29-23Z
    restart: on-failure
    networks:
      - zitadel
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    command:
      - gateway
      - nas
      - /export

# To interact with ZITADEL requires some data setted up.
# Due to the evolution of ZITADEL it's required to add additional
# setup steps, because of this fact it's recommended to rerun the setup
# on each restart, at least after a new version got released
  backend-setup:
    image: ghcr.io/caos/zitadel:1.75.0
    profiles: ['backend']
    restart: on-failure
    networks:
      - zitadel
    depends_on:
      db-migrations:
        condition: service_completed_successfully
    volumes:
      - .keys:/.keys
      - .notifications:/.notifications
    env_file:
      - ./local.env
    environment:
      - ZITADEL_EVENTSTORE_HOST=db
    command:
      [
        'setup',
      ]
# starts the backend (API's) of ZITADEL
# Port 50001 serves the GRPC API
# Port 50002 serves the REST API
# Port 50003 serves the login GUI
  backend-run:
    image: ghcr.io/caos/zitadel:1.75.0
    profiles: ['backend']
    restart: on-failure
    networks:
      - zitadel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50002/management/v1/healthz"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
      backend-setup:
        condition: service_completed_successfully
    env_file:
      - ./local.env
    volumes:
      - .keys:/.keys
      - .notifications:/.notifications
      - "./environment.json:/console/assets/environment.json"
    environment:
      - ZITADEL_EVENTSTORE_HOST=db
    ports:
      - 50001:50001
      - 50002:50002
    command:
      [
        'start',
      ]
# this service generates the environemnt.json
# needed in console.
# It curl's the client id of console and writes it to
# the environment.json
  client-id:
    profiles: ['frontend', 'console-stub']
    networks:
      - zitadel
    build:
      context: .
      dockerfile: Dockerfile.clientid
      target: client-id
    volumes:
      - ./environment.json:/environment.json
    environment:
      - HOST=backend-run
      - PORT=50002
# the GRPC web gateway proxies the 
# GRPC web calls to GRPC
# it's used in console (frontend) for example
  grpc-web-gateway:
    profiles: ['backend']
    restart: on-failure
    logging:
      driver: none
    depends_on:
      backend-run:
        condition: service_healthy
    networks:
      - zitadel
    build:
      dockerfile: Dockerfile.gateway
    image: grpcweb/grpcwebproxy
    ports:
      - '50000:8080'
  nginx:
    profiles: ['frontend']
    image: nginx:1.21.5
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/dev.conf
    ports:
      - '50003:80'
    networks:
      - zitadel
networks:
  zitadel: {}
```

However, the final hurdle is that the AuthConfig (declared [here](https://github.com/caos/zitadel/blob/f485a52d9aad83d3c0c9c4bcd1cfaf60e2a4504c/console/src/app/app.module.ts#L80)) is hard-coded to require the issuer to have HTTPS. I'm assuming that in the case of the local development environment setup in this repository, this is handled by the fact that you're running through the Angular CLI? Please correct me if I'm wrong, as I would very much like to get this running.
