### DISCUSSION TITLE
Run Zitadel behind Traefik and AWS Load Balancer

### DISCUSSION THREAD

**Discussion by remiallain** [zitadel/zitadel#3984] [Q&A] [answered]
Hello, 

Thank you for your great work with Zitadel !  👏 

I'm currently trying to deploy Zitadel on a Docker Swarm cluster on AWS and facing some issues.

### Context

- Docker Swarm on EC2 
- Traefik listening on port 80 and linked to Zitadel (following the docs)
- AWS ALB (port 443) forward to Traefik on port 80

**To summarize : AWS ALB (443) -> Traefik (80) -> Zitadel (H2C 8080)**

### Issue

When I try to access the UI, there is a blank screen and the requested URI `ui/console/assets/environment.json` return `empty instanceID`

### My configurations:

```yaml
# docker-compose.yml
  zitadel:
    networks:
      - zitadel
      - reverse-proxy
    image: ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.39-amd64
    command: start-from-init --masterkey "!!REDACTED!!" --tlsMode external --config /config.yml --steps /steps.yml
    environment:
      ZITADEL_DATABASE_HOST: cockroach
    configs:
      - source: zitadel-config
        target: /config.yml
      - source: zitadel-steps
        target: /steps.yml
    depends_on:
      - cockroach
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.zitadel.headers.isDevelopment=false"
        - "traefik.http.middlewares.zitadel.headers.allowedHosts=auth.my.domain,my.domain"
        - "traefik.http.services.zitadel-svc.loadbalancer.server.port=8080"
        - "traefik.http.services.zitadel-svc.loadbalancer.server.scheme=h2c"
        - "traefik.http.services.zitadel-svc.loadbalancer.passHostHeader=true"
        - "traefik.http.routers.zitadel.service=zitadel-svc"
        - "traefik.http.routers.zitadel.rule=Host(`auth.my.domain`, `{subdomain:[a-z]+}.auth.my.domain`)"
        - "traefik.http.routers.zitadel.entrypoints=http"
        - "traefik.http.routers.zitadel.middlewares=zitadel"
```

```yaml
# config.yml
Log:
  Level: 'info'

ExternalSecure: true
ExternalDomain: auth.my.domain
ExternalPort: 443

AdminUser:
  Username: '!!REDACTED!!`'
  Password: '!!REDACTED!!`'
```

```yaml
# steps.yml
S3DefaultInstance:
  CustomDomain: auth.my.domain
  Org:
    Name: 'Root'
    Human:
      Username: !!REDACTED!!
      Password: !!REDACTED!!
```

_PS : I've faced no problems when accessing directly from Traefik on port 443 (following your docs on load-balancing)_
