### DISCUSSION TITLE
SMTP with Office 365 gives Unrecognized Authentication Type Error

### DISCUSSION THREAD

**Discussion by Shaurya1409** [zitadel/zitadel#4263] [Q&A]
I have configured Zitadel with my office 365 SMTP settings using host as smtp.office365.com and port 587. 
Transport Layer Security option is checked in Zitadel Settings.

While trying to send an email, I get the following error 

level=error msg="could not connect to smtp" caller="/home/runner/work/zitadel/zitadel/internal/notification/channels/smtp/channel.go:32" error="504 5.7.4 Unrecognized authentication type [MA0PR01CA0037.INDPRD01.PROD.OUTLOOK.COM]"

Any help would be appreciated!

**Comment by fforootd** [comment]
Hm this sounds like a `starttls` problem.

We need to investigate this in more depth though before we can be certain.

**Comment by meyfa** [comment]
We're hitting the same problem with OVH (`pro2.mail.ovh.net:587`). OVH only supports STARTTLS for SMTP.

When TLS is disabled, sending mail fails with the following:

```
level=error msg="could not connect to smtp" caller="/home/runner/work/zitadel/zitadel/internal/notification/channels/smtp/channel.go:32" error="unencrypted connection"
```

When TLS is enabled, the log instead contains:

```
level=warning msg="could not connect using normal tls. trying starttls instead..." caller="/home/runner/work/zitadel/zitadel/internal/notification/channels/smtp/channel.go:121" error="tls: first record does not look like a TLS handshake"
level=error msg="could not connect to smtp" caller="/home/runner/work/zitadel/zitadel/internal/notification/channels/smtp/channel.go:32" error="504 5.7.4 Unrecognized authentication type"
```

@fforootd Do you have any idea what this could be about?

**Reply by fforootd** [reply]
Do you send some kind of authentication along or is it purely IP filter based?

**Reply by meyfa** [reply]
Yes, we're trying to use username+password authentication. Our configuration looks like this:

```yaml
DefaultInstance:
  SMTPConfiguration:
    SMTP:
      Host: pro2.mail.ovh.net:587
      User: mail@example.com
      Password: "<redacted>"
    TLS: false # or true - see different error messages above
    From: mail@example.com
    FromName: "<redacted>"
```

We know the credentials work since another application is using them as well, and is able to send mail.
