### DISCUSSION TITLE
Make client id and secret configurable

### DISCUSSION THREAD

**Discussion by skeletorXVI** [zitadel/zitadel#4349] [Ideas]
I intend to use Zitadel with OwnCloud Infinite Scale through OIDC. For the web app this works without any issues, but for the desktop and mobile clients the client ids and secrets are hardcoded. (e.g. [desktop client source code](https://github.com/owncloud/client/blob/2.11/src/libsync/theme.cpp#L628))

As @mffap pointed out in discord the OAuth spec actually states that the client identifier is supposed to be issued by the authorization server (see [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-2.2)) but in reality not all applications follow the spec perfectly (see [OwnCloud docs](https://discordapp.com/channels/927474939156643850/927866013545025566/1017780710427332790)).

I was able to overcome this shortcoming by creating a PKCE based desktop client and then modify the value in the `client_id` column in the `projections.apps2_oidc_configs` table. Fortunately both the desktop and android app don't use the client secret so I got it to work. But this is by no means a viable long term or production ready solution.

Thus I propose to support configuring at least the client_id and if possible the client_secret for cases where the administrators have no control over the target system.

**Comment by fforootd** [comment]
Oh wow that's a strange choice by the OwnCloud Team.

I am not sure if we can easily change this in ZITADEL. Whats your take @livio-a @adlerhurst @hifabienne

**Reply by adlerhurst** [reply]
It might could work using imports

**Reply by fforootd** [reply]
Good thought. You mean creating an "import client" function?

**Reply by adlerhurst** [reply]
~~For the client id the existing functionality should work.~~

Edit: Its not possible for client id

**Reply by skeletorXVI** [reply]
So I did some more digging and the OwnCloud clients actually first try [Dynamic Client Registration](https://openid.net/specs/openid-connect-registration-1_0.html) and then fall back to the hard coded client id + secret. It isn't documented yet (https://github.com/owncloud/docs/issues/3499) and it has it seems to still have some implementation problems from the various tickets found in the client repositories but it might be an feature worth looking into for other use cases as well.

**Comment by fenix01** [comment]
Hello everyone,

I was also trying to integrate Owncloud infinite scale with Zytadel. It works perfectly with the web interface but I don't know how to do with the Desktop client.
Like you, I saw it used hardcoded client_id (it is the first time I see something like this). How can I use Dynamic Client Registration with Zitadel if  we can't set arbitrary client_id ?

**Reply by skeletorXVI** [reply]
In the end I wrote a small middleware that provides this functionality using the Zitadel API.

You only need to configure your proxy to redirect `/.well-known/openid-configuration` and the registration path to the container running the dynamic client registrator.
Keep in mind that this solution is only applicable to self hosted version, not cloud deployments.

https://gitlab.com/skeletorXVI/zitadel-dynamic-client-registrator

Example using Traefik CRD:

```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel
  namespace: sso-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`example.com`,`{subdomain:[a-z]+}.example.com`)
      priority: 10
      services:
        - name: zitadel
          scheme: h2c
          port: 8080
  tls:
    certResolver: cloudflare
    domains:
      - main: example.com
        sans:
          - "*.example.com"
          - example.com
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel-dynamic-client-registrator
  namespace: sso-system
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: HostRegexp(`example.com`,`{subdomain:[a-z]+}.example.com`) && (Path(`/.well-known/openid-configuration`) || Path(`/oauth/v2/register`))
      priority: 20
      services:
        - name: zitadel-dynamic-client-registrator
          port: http
    - kind: Rule
      match: HostRegexp(`example.com`,`{subdomain:[a-z]+}.example.com`) && PathPrefix(`/origin`)
      priority: 30
      middlewares:
        - name: strip-origin-prefix
      services:
        - name: zitadel
          scheme: h2c
          port: 8080
  tls:
    certResolver: cloudflare
    domains:
      - main: example.com
        sans:
          - "*.example.com"
          - example.com
```
