### DISCUSSION TITLE
How to setup Zitadel to work with postgreSQL?

### DISCUSSION THREAD

**Discussion by wiktor-golonka** [zitadel/zitadel#4718] [Q&A] [answered]
Hi, 

I've been trying for hours to find the right configuration to simply install Zitadel along with PostgreSQL. 
And no matter what I do, it just doesn't work.

Following this guide, to install Zitadel in kubernetes: 
https://docs.zitadel.com/docs/guides/deploy/kubernetes

I wrote my `helm install` command that in my opinion just should work, but it does not,
Zitadel always attempts to use cockroachDB, no matter where I'm setting up the PostgreSQL configs - and I tried to add it everywhere, which you can see bellow...

```PowerShell
helm install zitadel zitadel/zitadel --namespace zitadel --kube-context minikube `
  --set zitadel.Log.Level="debug" `
  --set zitadel.masterkey="GsuRdRs4gXAWYQ4hz4nGE8o2ySvGdRBd" `
  --set zitadel.Database.postgres.Host="postgres" `
  --set zitadel.Database.postgres.Database="zitadel" `
  --set zitadel.Database.postgres.Port="5432" `
  --set zitadel.Database.postgres.User.Username="postgres" `
  --set zitadel.Database.postgres.User.Password="password" `
  --set zitadel.Database.postgres.User.SSL.Mode="disable" `
  --set zitadel.Database.postgres.Admin.Username="postgres" `
  --set zitadel.Database.postgres.Admin.Password="password" `
  --set zitadel.Database.postgres.Admin.SSL.Mode="disable" `
  --set zitadel.configmapConfig.ExternalSecure=false `
  --set zitadel.configmapConfig.TLS.Enabled=false `
  --set zitadel.configmapConfig.Database.postgres.Host="postgres" `
  --set zitadel.configmapConfig.Database.postgres.Database="zitadel" `
  --set zitadel.configmapConfig.Database.postgres.Port="5432" `
  --set zitadel.configmapConfig.Database.postgres.User.Username="postgres" `
  --set zitadel.configmapConfig.Database.postgres.User.Password="password" `
  --set zitadel.configmapConfig.Database.postgres.User.SSL.Mode="disable" `
  --set zitadel.configmapConfig.Database.postgres.Admin.Username="postgres" `
  --set zitadel.configmapConfig.Database.postgres.Admin.Password="password" `
  --set zitadel.configmapConfig.Database.postgres.Admin.SSL.Mode="disable" `
  --set zitadel.secretConfig.Database.postgres.Host="postgres" `
  --set zitadel.secretConfig.Database.postgres.Database="zitadel" `
  --set zitadel.secretConfig.Database.postgres.Port="5432" `
  --set zitadel.secretConfig.Database.postgres.User.Username="postgres" `
  --set zitadel.secretConfig.Database.postgres.User.Password="password" `
  --set zitadel.secretConfig.Database.postgres.User.SSL.Mode="disable" `
  --set zitadel.secretConfig.Database.postgres.Admin.Username="postgres" `
  --set zitadel.secretConfig.Database.postgres.Admin.Password="password" `
  --set zitadel.secretConfig.Database.postgres.Admin.SSL.Mode="disable" `
  --set replicaCount="1" `
  --set cockroachdb.enabled=false `
  --set cockroachdb.tls.enabled=false `
  --set zitadel.dbSslRootCrtSecret="" `
  --set zitadel.dbSslRootCrt="" `
  --set zitadel.dbSslClientCrtSecret="" `
  --values ./helm/zitadel/zitadel-secrets.yaml `
  --values ./helm/zitadel/zitadel-config-map.yaml 
```

My zitadel-secrets.yaml: 
```yaml
zitadel:

  masterkey: 'GsuRdRs4gXAWYQ4hz4nGE8o2ySvGdRBd'

  Database:
    postgres:
      Host: postgres
      Port: 5432
      Database: zitadel
      MaxOpenConns: 25
      MaxConnLifetime: 1h
      MaxConnIdleTime: 5m
      Options:
      User:
        Username: postgres
        Password: password
        SSL:
          Mode: disable
      Admin:
        Username: postgres
        Password: password
        SSL:
          Mode: disable

  secretConfig:

    Database:
      postgres:
        Host: postgres
        Port: 5432
        Database: zitadel
        MaxOpenConns: 25
        MaxConnLifetime: 1h
        MaxConnIdleTime: 5m
        Options:
        User:
          Username: postgres
          Password: password
          SSL:
            Mode: disable
        Admin:
          Username: postgres
          Password: password
          SSL:
            Mode: disable

```

My zitadel-config-map.yaml
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
zitadel:
  configmapConfig:
    Log:
      Level: 'debug'

    # Make ZITADEL accessible over HTTP, not HTTPS
    ExternalSecure: false
    ExternalDomain: localhost

    # the configmap is also passed to the zitadel binary via the --steps flag
    FirstInstance:
      Org:
        Human:
          # use the loginname root@zitadel.localhost
          Username: 'root'
          Password: 'RootPassword1!'

```

Logs from zitadel pod:
```
time="2022-11-20T01:13:16Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:54"
time="2022-11-20T01:13:16Z" level=fatal msg="at least ssl root cert has to be set" caller="/home/runner/work/zitadel/zitadel/internal/database/cockroach/config.go:117" cert set=false key set=false rootCert set=false
```

What is wrong with my configuration? Am I missing something there? 
How Zitadel decides what kind of database to use?

**Comment by eliobischof** [comment, marked as answer]
@wiktor-golonka, can you try it again with the latest release, e.g. --set image.tag=v2.12.0

If you configure something for PostgreSQL, ZITADEL uses the PostgreSQL config and dialect.

**Reply by wiktor-golonka** [reply]
Thanks, this worked. May I ask what version by default is installed with the official helm chart?

**Reply by fforootd** [reply]
I think that is a really old one https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/Chart.yaml#L5

@eliobischof I think we need to change this 😁

**Reply by eliobischof** [reply]
I opened a PR https://github.com/zitadel/zitadel-charts/pull/46 :+1: 
@wiktor-golonka it bumps v2.2.0 to v2.13.0.

**Comment by sillyfrog** [comment]
For others finding this thread to connect to Postgres, until https://github.com/zitadel/zitadel-charts/issues/91 is resolved (by someone that knows more than me about it 😄 ) this is a minimal config of the above, that can then be fleshed out:

```yaml
# Install / upgrade with:
# helm upgrade --install --create-namespace zitadel zitadel/zitadel --namespace zitadel -f minimal-values.yaml
zitadel:
  masterkey: GsuRdRs4gXAWYQ4hz4nGE8o2ySvGdRBd

  configmapConfig:
    Log:
      Level: "debug"

    # Make ZITADEL accessible over HTTP, not HTTPS
    ExternalSecure: false
    ExternalDomain: localhost

    # the configmap is also passed to the zitadel binary via the --steps flag
    FirstInstance:
      Org:
        Human:
          # use the loginname root@zitadel.localhost
          Username: "root"
          Password: "RootPassword1!"

  secretConfig:
    TLS:
      Enabled: false
    Database:
      postgres:
        Host: db-1-dev-global.cluster-chazzk96q7nu.ap-southeast-2.rds.amazonaws.com
        Database: zitadel
        Port: 5432
        User:
          Username: zitadel_user
          Password: op2iHX4iG3
          SSL:
            Mode: disable
        Admin:
          Username: zitadel_admin
          Password: op2iHX4iG3
          SSL:
            Mode: disable

  dbSslRootCrtSecret: ""
  dbSslRootCrt: ""
  dbSslClientCrtSecret: ""

replicaCount: 1
# initJob:
#   # Once ZITADEL is installed, the initJob can be disabled.
#   enabled: false
```

The DB users have to be created with:
```sql
CREATE USER zitadel_user LOGIN ENCRYPTED PASSWORD 'op2iHX4iG3';
CREATE USER zitadel_admin LOGIN ENCRYPTED PASSWORD 'op2iHX4iG3';
ALTER ROLE zitadel_admin CREATEDB;
ALTER ROLE zitadel_admin CREATEROLE;
```
