### DISCUSSION TITLE
How to host Zitadel on AWS App Runner?

### DISCUSSION THREAD

**Discussion by TakumiHaruta** [zitadel/zitadel#5035] [Q&A] [answered]
Hi ZItadel team,

I'm trying to host Zitadel on AWS App Runner backed by Aurora Serverless v2, and successfully logged in to the console.
But I got 404 error when the browser requests all endpoints under `https://<domain>/zitadel.auth.v1.AuthService/`.

<img width="1512" alt="Screen Shot 2023-01-13 at 10 35 27" src="https://user-images.githubusercontent.com/35373297/212217091-93729db9-060f-41e8-b25f-f5db461dd59d.png">

Am I missing some settings in Zitadel? Here are my configs;

### zitadel-config.yaml

```
Log:
  Level: 'info'

ExternalPort: 443
ExternalDomain: <app runner domain>
ExternalSecure: true

TLS:
  Enabled: false

Database:
  postgres:
    Host: <aurora url>
    Port: 5432
    Database: zitadel
    MaxOpenConns: 25
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options:
    User:
      Username: postgres # use admin user for testing
      Password: <password>
      SSL:
        Mode: disable
    Admin:
      Username: postgres
      Password: <password>
      SSL:
        Mode: disable

Machine:
  Identification:
    PrivateIp:
      Enabled: true
    Hostname:
      Enabled: true
    Webhook:
      Url: "${ECS_CONTAINER_METADATA_URI_V4}"
      JPath: "$.DockerId"
```

### Dockerfile

```
FROM ghcr.io/zitadel/zitadel:latest
EXPOSE 8080

COPY ./zitadel-config.yaml /zitadel-config.yaml

ENTRYPOINT ["/zitadel", "start-from-init", "--config", "/zitadel-config.yaml", "--masterkeyFromEnv", "--tlsMode", "external"]
```

### Steps to reproduce

1. Create Aurora PostgreSQL serverless v2 with a certain VPC
3. Build and push docker image to the ECR repository
4. Create App Runner with ECR and configure the network to Aurora PostgreSQL
5. Get App Runner domain and paste it on `zitadel-config.yaml` as `Database.postgres.Host`
6. Re-build and push docker image to the ECR repository
7. Create `zitadel` database in Aurora PostgreSQL
8. Deploy App Runner with the latest image
9. Login to the console with `zitadel-admin@<app runner domain>`
10. Got 404 error from `https://<domain>/zitadel.auth.v1.AuthService/`

I found someone who has experience with hosting ZItadel on App Runner, so I'm pretty sure it could be technically possible;

- #3625

But at the same time, App Runner doesn't support HTTP2, which seems to be required in Zitadel;

- [HTTP2 in App Runner? | AWS re:Post](https://repost.aws/questions/QUP8oWinyfTh-DmyEEZL4vhQ/http-2-in-app-runner)
- #4485

If ZItadel requires HTTP2, do I need to put CloudFront in front of App Runner?

> https://github.com/aws/apprunner-roadmap/issues/77#issue-1009728377
> But now we are stacked on HTTP 2 protocol. Because App Runner does not supports it. Requests from users browsers are very speed-sensitive. Right now as workaround we are using CloudFront as first layer between users and App Runner and its amazingly improves performance because HTTP2.

This is really awesome product btw. Thank you so much!
