### DISCUSSION TITLE
Unable to login in zitadel after deployment using helm chart

### DISCUSSION THREAD

**Discussion by Bhautik0110** [zitadel/zitadel#5037] [Q&A] [answered]
### Describe Issue
I want to deploy zitadel using the below-mentioned helm chart values. It's running behind Cloudflare, and Cloudflare is responsible for TLS certificate termination, and DDoS protection.

```yaml
# Default values for zitadel.
zitadel:

  # The ZITADEL config under configmapConfig is written to a Kubernetes ConfigMap
  # See all defaults here:
  # https://github.com/zitadel/zitadel/blob/v2-alpha/cmd/defaults.yaml
  configmapConfig:
    Log:
      Level: info
      Formatter:
        Format: text

    # Domain / hostname ZITADEL is exposed externally
    # !!! Changing this after initial setup breaks your system !!!
    ExternalDomain: auth.bhautik.in
    ExternalSecure: true

    DefaultInstance:
      LoginPolicy:
        DefaultRedirectURI: auth.bhautik.in

    Database:
      postgres:
        Host: terrabloom.timescaledb
        Port: 5432
        Database: zitadel
        MaxOpenConns:
        MaxConnLifetime:
        MaxConnIdleTime:
        Options:
        User:
          Username: postgres
          Password: DPYegXYnqixaCo
          SSL:
            Mode: disable
            RootCert:
            Cert:
            Key:
        Admin:
          Username: postgres
          Password: DPYegXYnqixaCo
          SSL:
            Mode: disable
            RootCert:
            Cert:
            Key:

    ## If you want to setup ZITADEL with a service account
    ## instead of a human admin user, comment the following
    ## in by deleting each lines first hash and space
    FirstInstance:
      # path used for volume mounts and to write the secret
      MachineKeyPath: /machinekey/zitadel-admin-sa.json
      Org:
        Machine: {}
          # Machine:
          #   # Creates a service account with the name zitadel-admin-sa,
          #   # which results in a secret 'zitadel-admin-sa' with a key 'zitadel-admin-sa.json'
          #   Username: zitadel-admin-sa
          #   Name: Admin
          # MachineKey:
          #   Type: 1

    # AdminUser:
    #   SSL:
    #     Mode: "disable"

  # ZITADEL uses the masterkey for symmetric encryption.
  # You can generate it for example with tr -dc A-Za-z0-9 </dev/urandom | head -c 32
  masterkey: 'dcvxhb4Snxgo9T45v6jfvPWxow9WFlli'

  # The root CA Certificate needed for establishing secure database connections
  dbSslRootCrt:

  # The Secret containing the root CA Certificate at key ca.crt needed for establishing secure database connections
  dbSslRootCrtSecret:

  # The Secret containing the client CA Certificate and key at tls.crt and tls.key needed for establishing secure database connections
  dbSslClientCrtSecret:

replicaCount: 1

image:
  repository: ghcr.io/zitadel/zitadel
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v2.15.0"

chownImage:
  repository: alpine
  pullPolicy: IfNotPresent
  tag: "3.11"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000

securityContext: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: auth.bhautik.in
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    memory: 150Mi
    cpu: 150m
  limits:
    memory: 250Mi
    cpu: 250m

nodeSelector: {}

tolerations: []

affinity: {}

initJob:
  # Once ZITADEL is installed, the initJob can be disabled.
  # If you want to setup ZITADEL with a service account instead of a human admin user
  # https://github.com/zitadel/zitadel-charts/blob/61766b5077010d223f6e0d08f937ceb6951c81a2/charts/zitadel/values.yaml#L24
  enabled: true
  resources: {}
  activeDeadlineSeconds: 300
  extraContainers: []
  podAnnotations: {}

setupJob: {}
  # resources: {}
  # activeDeadlineSeconds: 300
  # extraContainers: []
  # podAnnotations: {}
  # machinekeyWriterImage:
  #   repository: alpine/k8s
  #   tag: ""

metrics:
  enabled: false
  serviceMonitor:
    # If true, the chart creates a ServiceMonitor that is compatible with Prometheus Operator
    # https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#monitoring.coreos.com/v1.ServiceMonitor.
    # The Prometheus community Helm chart installs this operator
    # https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#kube-prometheus-stack
    enabled: false
    honorLabels: false
    honorTimestamps: true

cockroachdb:
  enabled: false
  fullnameOverride: crdb
  tls:
    enabled: false
```

Whenever I am open `https://auth.bhautik.in/ui/console/` It redirects me to the OAuth authorization endpoint (Url: `https://auth.bhautik.in/oauth/v2/authorize?response_type=code&client_id=196473338950910070%40zitadel&state=UjdaVXlGdzBzWGY0blhOeGlmeVAzZFNKWU5nZ0lVS2N1Tml4SGcxUnZGdlAz%3B20e0de9c-a820-4da7-b4e5-cd1f71ca76a8&redirect_uri=https%3A%2F%2Fauth.bhautik.in%2Fui%2Fconsole%2Fauth%2Fcallback&scope=openid%20profile%20email&code_challenge=2XYOsKCVIiNuSv8pE9aUaBlgOjnTGU83Y2wJoup6x8A&code_challenge_method=S256&nonce=UjdaVXlGdzBzWGY0blhOeGlmeVAzZFNKWU5nZ0lVS2N1Tml4SGcxUnZGdlAz`. below error render at authorization endpoint.

```
The requested redirect_uri is missing in the client configuration. If you have any questions, you may contact the administrator of the application.
```

Is that anything I missed, and any special thing need to do in ingress for gRPC endpoints?

Thanks.
