### DISCUSSION TITLE
Is it possible to disable Email verification?

### DISCUSSION THREAD

**Discussion by marknefedov** [zitadel/zitadel#5114] [Q&A] [answered]
Is it possible to disable Email verification for local development purposes?

**Comment by hifabienne** [comment, marked as answer]
This is currently not possible. We already have an open issue for removing required fields. #4386 but as removing email verification does have some impacts to the rest we are not yet sure when we implement this.

**Comment by neverstew** [comment]
This was quite annoying for me, and it took me a long time to search for this answer!

Can I request that the docs are updated so that there's a pointer to what to do there? I managed to get this running locally quite easily by running a mock SMTP service alongside my docker containers.

Here's the additional service definition
```yml
  smtp:
    image: "rnwood/smtp4dev"
    networks:
      - "zitadel"
    ports:
      - "3030:80"
      - "2525:25"
```

Which is then configured in the Instance Settings > Notification settings > SMTP Settings with:
Sender Email Address: `whatever you want`
Sender Name: `whatever you want`
TLS: `OFF`
Host and Port: `smtp:2525`
User: `-`
