### DISCUSSION TITLE
Failed to connect via load balancer

### DISCUSSION THREAD

**Discussion by domgolonka** [zitadel/zitadel#5179] [Q&A]
I am using the load balancer example on my local computer with slight altercations. 

https://zitadel.com/docs/self-hosting/deploy/loadbalancing-example

docker-compose
```
   traefik:
    networks:
      - 'intranet'
    image: "traefik:v2.7"
    ports:
      - "8070:80"
      - "43443:443"
    volumes:
      - "./.zitadel/traefik.yaml:/etc/traefik/traefik.yaml"
      - "./.zitadel:/etc/certs:ro"

  zitadel:
    restart: 'always'
    networks:
      - 'intranet'
    image: 'ghcr.io/zitadel/zitadel:stable'
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "hcnsovzVUoaGv9AzrMeb7j1z04AryrYH" --tlsMode external'
    depends_on:
      my-cockroach-db:
        condition: 'service_healthy'
    volumes:
      - './.zitadel/zitadel-config.yaml:/zitadel-config.yaml:ro'
      - './.zitadel/zitadel-secrets.yaml:/zitadel-secrets.yaml:ro'
      - './.zitadel/zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro'
```
      
   traefik.yaml   
```
     entrypoints:
  web:
    address: ":80"

  websecure:
    address: ":443"

debug: true
logLevel: "DEBUG"

#tls:
#  stores:
#    default:
#      # generates self-signed certificates
#      defaultCertificate:

providers:
  file:
    filename: /etc/traefik/traefik.yaml
tls:
  certificates:
    - certFile: "/etc/certs/local-cert.pem"
      keyFile: "/etc/certs/local-key.pem"

http:

  middlewares:
    zitadel:
      headers:
        isDevelopment: true
        allowedHosts:
          - 'my.handyapp'
    redirect-to-https:
      redirectScheme:
        scheme: https
        port: 43443
        permanent: true

  routers:
    # Redirect HTTP to HTTPS
    router0:
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      rule: 'HostRegexp(`my.handyapp`, `{subdomain:[a-z]+}.my.handyapp`)'
      service: zitadel
    # The actual ZITADEL router
    router1:
      entryPoints:
        - websecure
      service: zitadel
      middlewares:
        - zitadel
      rule: 'HostRegexp(`my.handyapp`, `{subdomain:[a-z]+}.my.handyapp`)'
      tls:
        domains:
          - main: "my.handyapp"
            sans:
              - "*.my.handyapp"
              - "my.handyapp"

  # Add the service
  services:
    zitadel:
      loadBalancer:
        servers:
          # h2c is the scheme for unencrypted HTTP/2
          - url: h2c://zitadel:8080
        passHostHeader: true
```

zitadel-config.yaml
```
Log:
  Level: 'debug'

# Make ZITADEL accessible over HTTP, not HTTPS
ExternalSecure: true
ExternalDomain: my.handyapp
ExternalPort: 43443

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    Host: 'my-cockroach-db'
```

The code that I am running:

```
	zManagementClient, err := management.NewClient("https://my.handyapp:43443",
		"my.handyapp:43443",
		[]string{oidc.ScopeOpenID, zitadel.ScopeProjectID("200185590451273735")},
		zitadel.WithOrgID("200182955807604743"),
		zitadel.WithInsecure(), // todo: remove on staging
		//- a JWT Profile source token (e.g. path to your key json), if not provided, the file will be read from the path set in env var ZITADEL_KEY_PATH
		zitadel.WithJWTProfileTokenSource(zmiddleware.JWTProfileFromPath(zitadelServiceKey)))
	if err != nil {
		log.Fatalln("could not create zitadel client", err)
	}

	healthresp, err := zManagementClient.Healthz(context.Background(), &manage.HealthzRequest{})
	if err != nil {
		log.Fatalln("call failed healty: ", err)
	}

```
I am getting an error message stating that the service can't access grpc

```
rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "text/plain; charset=utf-8"
exit status 1
```

**Comment by fforootd** [comment]
Hm the error ` received unexpected content-type "text/plain; charset=utf-8"` is known to be caused by http2 problems.

As you allowed h2c in the backend, that looks fine. But I guess you need to allow http2 as well in the frontend of traefik (although I am not sure with this)

Does accessing ZTIADEL work from browsers?

**Reply by domgolonka** [reply]
Yup, I can access ZITADEL GUI on the browser without issue.

**Reply by fforootd** [reply]
Ok that kind of confirms my suspicion this looks to me like when traefik receives a h2 connection it breaks something along the line.

Since the browser does work (you can login and see the console, right?) with http1.1 it seems that either some headers are lost or something other weird thing happens.

**Reply by fforootd** [reply]
Hm what could be is that traefik does not pass along the authority header (the h2 version of the host header)

Can you try and pass that along explicitly? Because if this is lost and the header is set to localhost zitadel will respond with a 404 text/plain containing "ID=QUERY-n0wng Message=Instance not found"

**Reply by fforootd** [reply]
```
http:
  middlewares:
    testHeader:
      headers:
        customRequestHeaders:
          :authority: "my.handyapp"
 ``` 

could be a test for this. but I have not much experience with traefik 😁 

actually I have no clue how they handle header forwarding
