### DISCUSSION TITLE
Setting Environment Variables using Docker Secrets

### DISCUSSION THREAD

**Discussion by robertcarroll** [zitadel/zitadel#5572] [Ideas]
Going to use a simplified example from the config options, but this is usually more supported on the variables that hold things like passwords or usernames.

Currently, you can set environment variables in your compose file the following way:
```environment:
      environment:
      ZITADEL_EXTERNALSECURE: "true"
```
I've seen containers set up with the following ability that allows the use of docker secrets in the compose file:
```environment:
      environment:
      ZITADEL_EXTERNALSECURE_FILE: /run/secrets/secretname
```

From what I know of the idea, it would most likely be updating the initialization script to get the values from the specified secret locations

**Comment by fforootd** [comment]
@eliobischof what is your take for this?

**Reply by eliobischof** [reply]
With docker secrets you can mount files to the container, right? So AFAIU, you should just be able to mount a ZITADEL config file with values you consider confidential using a docker secret and pass its path with the --config flag to the zitadel binary. You can pass many --config files and ZITADEL merges them.

But I never worked with docker secrets before, so there is a risk I misunderstood something

**Reply by robertcarroll** [reply]
Currently working on giving this method a shot to see if it works as expected because that does make sense based on what I know as well.

**Reply by robertcarroll** [reply]
Looks like your theory was correct, @eliobischof. I was able to spin up a local setup similar to my previous experiment with the following config:
```
version: "3.8"

secrets:
  zitadel-config:
    external: true
  zitadel-pg-admin-user:
    external: true
  zitadel-pg-admin-password:
    external: true

services:
  app:
    secrets:
      - zitadel-config
    networks:
      - zitadel
      - traefik-public
    image: ghcr.io/zitadel/zitadel:v2.21.4
    command: 'start-from-init --config /run/secrets/zitadel-config --masterkey "${ZITADEL_MASTERKEY}" --tlsMode external'
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        traefik.enable: "true"
        traefik.http.routers.zitadel.rule: Host(`domain.local`)
        traefik.http.routers.zitadel.entrypoints: websecure
        traefik.http.routers.zitadel.tls.domains[0].main: "domain.local"
        traefik.http.routers.zitadel.tls.domains[0].sans: "*.domain.local"
        traefik.http.services.zitadel.loadbalancer.server.port: 8080
        traefik.http.services.zitadel.loadbalancer.server.scheme: h2c
    volumes:
      - "./certs:/certs:ro"
  
  postgres:
    secrets:
      - zitadel-pg-admin-user
      - zitadel-pg-admin-password
    image: postgres:15-alpine
    ports:
      - 5432:5432
    networks:
      - zitadel
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/zitadel-pg-admin-user
      POSTGRES_PASSWORD_FILE: /run/secrets/zitadel-pg-admin-password
      POSTGRES_DB: zitadel
    deploy:
      placement:
        constraints:
          - node.role == manager


networks:
  traefik-public:
    external: true
  zitadel:
    external: true
```
