### DISCUSSION TITLE
Allow insecure STMP configurations

### DISCUSSION THREAD

**Discussion by masewo** [zitadel/zitadel#5672] [Ideas]
The mail server that we are using has a self signed certificate and works fine for all our usecases.
But we cannot use it as a notification channel for ZITADEL.

Our wish would be that it is possible via ZITADEL configuration to allow insecure SMTP configurations.

Example configuration:
```
SMTPConfiguration:
    SMTP:
      Host:
      User:
      Password:
    TLS:
    InsecureSkipVerify:
    From:
    FromName:
```
With default value set to false.

Code that could need to be changed:
https://github.com/zitadel/zitadel/blob/2ec36bd63baf966d338a07ba17dbc3ac5a9fd689/internal/notification/channels/smtp/channel.go#L122

To:
```
conn, err := tls.Dial("tcp", smtpConfig.Host, &tls.Config{InsecureSkipVerify: smtpConfig.InsecureSkipVerify})
```
