### DISCUSSION TITLE
Unable to read CA file using CockroachCloud config

### DISCUSSION THREAD

**Discussion by aPaladinesEC** [zitadel/zitadel#5759] [Q&A] [answered]
Hi,
In first intance let me congratulate the zitadel team and contributors for such a great product.

I'm was able to testing using default example configuration using docker and it works.
Ubuntu 22 and Docker.

But when I try to use custom DB info using CockroachCloud I get in logs this error: 

`level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:65" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse 'host=myname-cloud-XXX.g8z.cockroachlabs.cloud port=26257 user=XXXXXXXXXX dbname=domain_auth application_name=zitadel sslmode=verify-full password=xxxxx sslrootcert=root.crt': failed to configure TLS (unable to read CA file: open root.crt: no such file or directory))`

This are my config files:

docker-compose.yaml
```
version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:stable"
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "XXXXXXXXXXXXXXXXXXXXXXXXXXX" --tlsMode external'
    ports:
      - "8080:8080"
    volumes:
      - "./zitadel-config.yaml:/zitadel-config.yaml:ro"
      - "./zitadel-secrets.yaml:/zitadel-secrets.yaml:ro"
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro"

networks:
  zitadel:
```
zitadel-config.yaml | Using nginx to proper domain configuration. With default docker example everything works normally.
```
Log:
  Level: 'info'

ExternalSecure: true
ExternalDomain: 'auth.mydomain.com'
ExternalPort: 443

Database:
  cockroach:
    Host: 'myname-cloud-XXX.g8z.cockroachlabs.cloud'
    Port: 26257
    Database: 'domain_auth'
    MaxOpenConns: 20
    MaxConnLifetime: '30m'
    MaxConnIdleTime: '30m'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: ".postgresql/root.crt"
    Admin:
      SSL:
        Mode: 'verify-full'
        RootCert: ".postgresql/root.crt"
```
zitadel-secrets.yaml
```
Database:
  cockroach:
    User:
      Username: 'new_user'
      Password: 'XXXXXXXXXXX'
    Admin:
      Username: 'alexander.paladines'
      Password: 'XXXXXXXXXXXXXX'
```

CockroachDB in my console give me a curl url to download a root.crt file, somethig like this:
`curl --create-dirs -o $HOME/.postgresql/root.crt 'https://cockroachlabs.cloud/clusters/XX-XXX-XXXX-XXXX-XXXX-XXXXXXX/cert'`

This folder and file is already in same path as docker-compose.yaml, so the structure is:
```
/home/myaccount
   ->.postgresql/root.crt
   ->docker-compose.yaml
   ->the other three config files .yaml
```
I thought that using CockroachCloud will result in a easy process to config, but obviously i'm missing something important that I don't know where to start.

Thanks in advance.

**Comment by hifabienne** [comment]
Thank. Great to hear that you like ZITADEL.
@eliobischof Can you help here?

**Comment by eliobischof** [comment, marked as answer]
You have to mount the certificate to the container

```
version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:stable"
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "XXXXXXXXXXXXXXXXXXXXXXXXXXX" --tlsMode external'
    ports:
      - "8080:8080"
    volumes:
      - "./zitadel-config.yaml:/zitadel-config.yaml:ro"
      - "./zitadel-secrets.yaml:/zitadel-secrets.yaml:ro"
      - "./zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro"
      - "./.postgresql/root.crt:/.postgresql/root.crt:ro"

networks:
  zitadel:
```

**Reply by aPaladinesEC** [reply]
Hi, thank for that.
Now I get another error, without know exactly what to do:

`level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:65" error="ERROR: at or near \".\": syntax error (SQLSTATE 42601)"`

Same config, I have check the credentials, the host.
Even in cockroachcloud dashboard in Monitoring->SQL Activity menu and Sessions, I can see the connection from my server IP, with status con Closed, but that give the idea that server tries to connect.
![image](https://user-images.githubusercontent.com/54280877/234989514-6f480353-df33-4cef-85cc-c5492f3ddf8f.png)

**Reply by aPaladinesEC** [reply]
Sorry, my bad.
I already get connection:

I don't know if this is the normal configuration.

In file zitadel-secrets.yaml user and admin I put same credentials.
```
Database:
  cockroach:
    User:
      Username: 'user_zitadel'
      Password: 'XXXXXXXXXXXXX'
    Admin:
      Username: 'user_zitadel'
      Password: 'XXXXXXXXXXXXX'
```

Now I get activity on Sessions and the database has all tables.

Thanks.
