### DISCUSSION TITLE
Mapping of roles in e.g. Kimai App

### DISCUSSION THREAD

**Discussion by rhizoet** [zitadel/zitadel#5872] [Q&A] [answered]
Hey guys,

I am currently testing Zitadel and would like to connect this to Kimai TimeTracking via SAML. The login works as far as it goes. However, I am not able to synchronize the roles I have created in the project.

By this I mean that I create for example an admin role and this should then be mapped to the admin role within Kimai. So that is so in Zitadel can determine who is admin and who is not.

In Kimai I have tried it with
```
roles:
  resetOnLogin: true
  attribute: Roles
  mapping:
    - { saml: admin, kimai: ROLE_ADMIN }
    - { saml: management, kimai: ROLE_TEAMLEAD }
```
But that does not work. Also `attribute: Groups` does not work.

Do you have a hint for me how to map the roles correctly? I could not find anything in the documentation.

Thanks in advance.
