### DISCUSSION TITLE
How can I test locally with ngrok?

### DISCUSSION THREAD

**Discussion by carolpettirossi** [zitadel/zitadel#6073] [Q&A]
I have a docksal (docker) running Drupal and I have used the `docker-compose.yaml` to start a zitadel on `localhost:8080`. 
I tried using **ngrok http 8080** . However, when I try to access the exposed URL I get a blank screen with this message

`ID=QUERY-n0wng Message=Instance not found`

**Comment by carolpettirossi** [comment]
Even if I try to access {container_ip}:8080 (http://192.168.112.3:8080/) I see the message with Instance not found.

**Comment by carolpettirossi** [comment]
I also tried using the ExternalDomain configuration and I couldn't make it work.

Here's my docker-compose.yaml:

```
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --config /zitadel-config.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.2.2'
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'

networks:
  zitadel:

```

Here's my zitadel-config.yaml:

```
ExternalSecure: true
ExternalDomain: 'zitadel.my.domain'
ExternalPort: 443
```

My folder structure:
```
- zitadel
-- docker-compose.yaml
-- zitadel-config.yaml
```
