### DISCUSSION TITLE
zitadel docker image for rasberry pi 4

### DISCUSSION THREAD

**Discussion by masoncole1994** [zitadel/zitadel#6527] [General]
Hello everyone,

I've attempted to run the quickstart examples https://zitadel.com/docs/self-hosting/deploy/compose on my Raspberry Pi 4, but it seems that the image is not prepared for arm-v8:

```shell
foo@rpi:~/AH-HH $ docker compose -f docker-composel.yml up
[+] Running 0/1
 ⠦ zitadel Pulling                                                                                                                                                              1.6s 
no matching manifest for linux/arm/v8 in the manifest list entries
```

I also tried to build the image from this Dockerfile myself, which is located here: [link](https://github.com/zitadel/zitadel/blob/main/build/Dockerfile), using the following command: `docker build -t zitadel:v1 .`

However, this didn't work either, and I encountered the following error:

```shell
Error response from daemon: failed to create a task for the container: failed to create a shim task: OCI runtime create failed: runc create failed: unable to start the container process: exec: "/app/zitadel": permission denied: unknown
```

<details>
<summary>Raspberry Pi (rpi) Info</summary>

```shell
# OS Info
uname -mrs
Linux 6.1.21-v8+ aarch64

# CPU Info
lscpu
Architecture:                    aarch64
Byte Order:                      Little Endian
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
Vendor ID:                       ARM
Model:                           3
Model name:                      Cortex-A72
Stepping:                        r0p3
CPU max MHz:                     1800.0000
CPU min MHz:                     600.0000
BogoMIPS:                        108.00
L1d cache:                       128 KiB
L1i cache:                       192 KiB
L2 cache:                        1 MiB
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigated; __user pointer sanitization
Vulnerability Spectre v2:        Vulnerable
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected
Flags:                           fp asimd evtstrm crc32 cpuid
```

</details>

I'll appreciate any help

**Comment by livio-a** [comment]
Hey @masoncole1994 

Looks like the platform variant is not resolved / is missing in the manifest.

Can you try to pull and run the `linux/arm64` image:
``` docker pull --platform linux/arm64 ghcr.io/zitadel/zitadel```

**Reply by masoncole1994** [reply]
Hi @livio-a ,

Thank you for reply

You were right, I've been able to launch zitadel with that flag. Seems like docker client resolve platform for docker.io registry itself, but for other regestries you have to specify it.

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3.8'

services:
  zitadel:
    # restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    platform: linux/arm64
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    # restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.2.2'
    platform: linux/arm64
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'

networks:
  zitadel:

``` 

</details>

However I still have an error:

```shell
docker compose up
[+] Building 0.0s (0/0)                                                                                                                                                                                           
[+] Running 2/2
 ✔ Container ah-hh-crdb-1     Recreated                                                                                                                                                                      1.1s 
 ✔ Container ah-hh-zitadel-1  Recreated                                                                                                                                                                      0.5s 
Attaching to ah-hh-crdb-1, ah-hh-zitadel-1
dependency failed to start: container ah-hh-crdb-1 exited (159)
```

I'll try to get help from crdb https://github.com/cockroachdb/cockroach/discussions/110398
