### DISCUSSION TITLE
DEFAULT BACKEND - 404 when trying access to deployed zitadel

### DISCUSSION THREAD

**Discussion by drsilva95** [zitadel/zitadel#6539] [Q&A]
Hi, everyone

I have a EKS cluster and I deployed zitadel as default using  the documentation (https://zitadel.com/docs/self-hosting/deploy/kubernetes).

By default, I think that is runnig in port 8080 (check image below):

<img width="704" alt="image" src="https://github.com/zitadel/zitadel/assets/142890796/2fd5df77-3595-4f17-8815-ee8a6d19c20b">

I have a domain that is pointing for 8080 port and I created this ingress: 

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-zitadel-ingress
  namespace: zitadel
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - example.com
  rules:
  - host: example.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: zitadel
            port:
              number: 8080
   ```          
             
Conclusion, after that when I trying to acess https://example.com/ I'm redirected for https://example.com/ui/login (I think that's expectable) but I receive that:

![image](https://github.com/zitadel/zitadel/assets/142890796/0bca1c7f-879c-48b2-96ec-5083b4d74d86)

Anyone can help me ?

Thank you all
