### DISCUSSION TITLE
Zitadel behind haproxy as load balancer sometimes reachable, sometimes not

### DISCUSSION THREAD

**Discussion by meinrecht** [zitadel/zitadel#6627] [Q&A]
I use `haproxy` as load balancer for a `zitadel` instance running inside docker-compose and was initially able to have a working setup, so I did some experiments with users and organizations already.

However, when I try to login after some time, I get the error "504 - gateway Time-out". I don't see any errors in the logs and did not change the `haproxy` config.

`haproxy` is configured to use `h2` in the frontend as well as in the backend. It is not able to use `h2c`. 
When I use `haproxy` in debug mode I can see that it tries to establish a connection is to `zitadel` using http2 which times out.

The logs show me that zitadel is up with a message like this:
> Version          : v2.35.1
> zitadel_1  |  TLS enabled      : false
> zitadel_1  |  External Secure  : true
> zitadel_1  |  Console URL      : https://zitadel.mydomain.tld:443/ui/console
> zitadel_1  |  Health Check URL : https://zitadel.mydomain.tld:443/debug/healthz

No errors concerning crdb.

After fiddling around with some settings, now it works again (I wanted to see what happens, when I use a wrong masterkey, - that leads to DB connection errors - and when I restored the correct one, suddenly everything is ok). 

It's a bit disturbing to have a running configuration break just with time passing and being restored just by changing something and then changing it back.

I do get some error messages when the setup works concerning mail, like "Message=could not set recipient: root@zitadel.zitadel.mydomain.tld").

Does anybody have an idea how this happens or how I can debug it? 

Unfortunately the zitadel container does not allow any kind of introspection as there seems to be no `bash` or any other tooling.

This is my config:
```
Log:
  Level: 'debug'

ExternalPort: 443
ExternalSecure: True
ExternalDomain: zitadel.mydomain.tld

Database:
  cockroach:
    Host: 'crdb'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
        Cert: "/crdb-certs/client.zitadel_user.crt"
        Key: "/crdb-certs/client.zitadel_user.key"
    Admin:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
        Cert: "/crdb-certs/client.root.crt"
        Key: "/crdb-certs/client.root.key"

```
And this is the docker-compose file:
```
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:stable'
    command: 'start-from-init --masterkeyFromEnv --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --tlsMode external'
    depends_on:
      certs:
        condition: "service_completed_successfully"
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_MASTERKEY=${ZITADEL_MASTERKEY}'
      - 'DEBUG_MODE=true'
    volumes:
      - "${PWD}/config/zitadel-config.yaml:/zitadel-config.yaml:ro"
      - "${PWD}/config/zitadel-secrets.yaml:/zitadel-secrets.yaml:ro"
      - "${PWD}/config/zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro"
      - "zitadel-certs:/crdb-certs:ro"
    ports:
      - '127.0.0.1:${PORT}:8080'

  certs:
    image: "cockroachdb/cockroach:v22.2.2"
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "cp /certs/* /zitadel-certs/ && cockroach cert create-client --overwrite --certs-dir /zitadel-certs/ --ca-key /zitadel-certs/ca.key zitadel_user && chown 1000:1000 /zitadel-certs/*",
      ]
    volumes:
      - "certs:/certs:ro"
      - "zitadel-certs:/zitadel-certs:rw"
    depends_on:
      crdb:
        condition: "service_healthy"
  
  crdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.2.2'
    command: "start-single-node --advertise-addr crdb"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://crdb:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    volumes:
      - "certs:/cockroach/certs:rw"
      - "data:/cockroach/cockroach-data:rw"
    ports:
      - '127.0.0.1:${COCKROACH_PORT}:8080'
      - '26257:26257'

networks:
  zitadel:

volumes:
  certs:
  zitadel-certs:
  data:
```
