### DISCUSSION TITLE
Zitadel deployed in AWS EKS - how do I find the JWT token for the terraform provider?

### DISCUSSION THREAD

**Discussion by Cr4ig101** [zitadel/zitadel#6708] [Q&A] [answered]
I am deploying Zitadel into an AWS EKS cluster using Terraform Helm resource and I have configured it to create a machine user. Now I want to use the Zitadel terraform provider to deploy orgs and human users. I am unable to work out where I get the JWT token from for the provider as either a jwt_profile_json or jwt_profile_file is required. I am unable to log into the Zitadel application as all I have is a machine user. 

Please help. 

```
`provider "zitadel" {
  domain           = "localhost"
  insecure         = "true"
  port             = "8080"
  project          = "170832731415117995"
  jwt_profile_file = "local-token"
}`
```

**Comment by eliobischof** [comment]
The [Helm chart](https://github.com/zitadel/zitadel-charts) writes the machine key to a kubernetes secret when you install it

**Reply by Cr4ig101** [reply]
Hi, 
I have tried to use the machine key, but this is not in the right format, from what I understand a JWT needs to have a Header Payload and Signature.... How do I use the machine key in the Terraform provider?

**Reply by Cr4ig101** [reply]
@eliobischof apologies I now see what you mean... however my helm deployment is not adding a machine key secret, I only have the zitadel-masterkey, could this be my values.yaml file being miss configured?  

```
resource "helm_release" "zitadel_release" {

  name                = "zitadel"
  repository          = "oci://${data.aws_caller_identity.current.account_id}.dkr.ecr.${var.aws_region}.amazonaws.com"
  repository_username = data.aws_ecr_authorization_token.token.user_name
  repository_password = data.aws_ecr_authorization_token.token.password
  chart               = "zitadel/zitadel"
  version             = "6.2.0"
  namespace           = var.namespace

  values = [
    "${file("${path.module}/zitadel-config.yaml")}"
  ]

  set {
    name  = "zitadel.masterkey"
    value = data.aws_ssm_parameter.zitadel_master.value
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.Host"
    value = var.db_host
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.Port"
    value = "5432"
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.Database"
    value = "zitadel"
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.Admin.Username"
    value = "postgres"
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.Admin.Password"
    value = data.aws_ssm_parameter.rds_admin.value
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.User.Username"
    value = "zitadel"
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.User.Password"
    value = data.aws_ssm_parameter.rds_user.value
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.Admin.SSL.Mode"
    value = "disable"
  }

  set {
    name  = "zitadel.configmapConfig.Database.postgres.User.SSL.Mode"
    value = "disable"
  }

  set {
    name  = "zitadel.log.level"
    value = "debug"
  }

  set {
    name  = "zitadel.configmapConfig.TLS.Enabled"
    value = "false"
  }

  set {
    name  = "zitadel.configmapConfig.ExternalDomain"
    value = var.externaldomain
  }

  set {
    name  = "zitadel.FirstInstance.Org.Machine.Machine.Username"
    value = "zitadel-admin-sa"
  }

  set {
   name  = "zitadel.FirstInstance.Org.Machine.Machine.Name"
    value = "Admin"
  }
}

```

My config file 

```
zitadel:
  FirstInstance:
    MachineKeyPath: '/machinekey/zitadel-admin-sa.json'
    Org:
     Machine:
       MachineKey:
         Type: 1
       Machine:
         Username:
         Name:
  masterkey:
  Log:
    Level:
  configmapConfig:
    TLS:
      Enabled:
    port: 8080
    ExternalDomain:
    ExternalPort: 443
    ExternalSecure: true
    Database:
      postgres:
        Host:
        Port:
        Database:
        MaxOpenConns: 25
        MaxConnLifetime: 1h
        MaxConnIdleTime: 5m
        Options:
        User:
          Username:
          Password:
          SSL:
            Mode:
        Admin:
          Username:
          Password:
          SSL:
            Mode:
```
