### DISCUSSION TITLE
Zitadel on EKS

### DISCUSSION THREAD

**Discussion by aavandry** [zitadel/zitadel#6894] [Q&A]
Hi,

i started zitadel on aws EKS via helm chart with follow parameters -

```
    fullnameOverride: zitadel
    nameOverride: zitadel
    replicaCount: 1
    zitadel:
      masterkeySecretName: zitadel-masterkey
      configmapConfig:
        ExternalSecure: true
        ExternalDomain: zitadel.dev.slyngshot.io
        Port: 8080
        ExternalPort: 443
        Log:
          Level: debug
        TLS:
          Enabled: false
        Database:
          Postgres:
            Host: slyngshot-dev-db.c51susevcmpg.us-east-2.rds.amazonaws.com
            Port: 5432
            Database: zitadel
            MaxOpenConns: 20
            MaxIdleConns: 10
            MaxConnLifetime: 30m
            MaxConnIdleTime: 5m
            User:
              Username: postgres
              SSL:
                Mode: disable
            Admin:
              Username: postgres
              SSL:
                Mode: disable
      configSecretName: zitadel-secrets-yaml
      configSecretKey: zitadel-secrets-yaml
    ingress:
      enabled: true
      className: "alb"
      annotations:
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
        alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=300
        alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-2021-06
        alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-2:837223769016:certificate/1983a4ae-d112-44d8-a520-4022759c1790
        alb.ingress.kubernetes.io/backend-protocol: HTTP
        alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
        alb.ingress.kubernetes.io/ssl-redirect: '443'
      hosts:
        - host: zitadel.dev.slyngshot.io
          paths:
            - path: /
              pathType: Prefix
```

image: ghcr.io/zitadel/zitadel:v2.35.0
helm chart: zitadel-7.1.0

no errors in the logs, postgresql db is initialised from zero, looks good, but i can not login as default admin user via https://zitadel.dev.slyngshot.io/ui/console url. It shows /ui/console interface for a while, then redirects me https://zitadel.dev.slyngshot.io/ui/login.

Did i missed something?

Thank you in advance.

**Comment by mffap** [comment]
Console is an application that redirects you to the login page. As soon as you log in you should get redirected back to Console. Can you login with the Admin credentials?

Not sure what you expected to be different. Can you explain?

**Comment by aavandry** [comment]
No, i can not login, it shows me
"User could not be found"

with default FirstInstance values. Also, i tried to replace default admin credentials like follow -

```
      FirstInstance:
        Org:
          Human:
            UserName: andreyareshchenko@singletonfoundation.or
            Email:
              Address: andreyareshchenko@singletonfoundation.org
              Verified: true
            Password: "Password1!"
```
it did not helped. It returns "user not found" for all usernames (zitadel-admin, zitadel-admin@zitadel.localhost, andreyareshchenko@singletonfoundation.or, andreyareshchenko@singletonfoundation.org).
