### DISCUSSION TITLE
Unable to access Zitadel Console through Traefik

### DISCUSSION THREAD

**Discussion by urihani** [zitadel/zitadel#6950] [Q&A] [answered]
Hi,

I have a Bad Gateway error when tring to access Zitadel's console with https://zitadel.mydomain.com

I have DNS proxy enabled for this subdomain in Cloudflare and traefik SSL is done via letsencrypt.

Here is my traefik docker compose file:
```yaml
  version: '3'
  
  services:
    traefik:
      image: traefik:v3.0
      container_name: traefik
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /srv/config/traefik/acme.json:/acme/acme.json 
        - /srv/config/traefik/traefik.yml:/traefik.yml:ro
        - /srv/logs/traefik:/logs
      environment:
        - CLOUDFLARE_EMAIL={{ cf_email }}
        - CLOUDFLARE_API_KEY={{ cf_api_key }}
      labels:
        - traefik.enable=true
        - traefik.http.routers.thisproxylocal.rule=Host(`{{ traefik_host_name }}`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
        - traefik.http.routers.thisproxylocal.entryPoints=web
        - traefik.http.routers.thisproxylocal.service=api@internal
        - traefik.http.services.thisproxytls.loadbalancer.server.port=8086
        - traefik.http.routers.thisproxytls.rule=Host(`{{ traefik_host_name }}`)
        - traefik.http.routers.thisproxytls.entrypoints=websecure
        - traefik.http.routers.thisproxytls.service=api@internal
        - traefik.http.routers.thisproxytls.tls.certresolver=letsencrypt
      restart: always
      networks:
        - proxy
  
  networks:
    proxy:
      external: true
      name: proxy 
```

Traefik config (traefik.yml):
```yaml
  global:
    checkNewVersion: true
    sendAnonymousUsage: false
  
  log:
    level: {{ log_level }}
    filePath: "/logs/traefik.log"
    format: json
  
  accessLog:
    filePath: "/logs/access.log"
    format: json
    bufferingSize: 100
  
  api:
    dashboard: true
  
  entrypoints:
    web:
      address: ":80"
  
    websecure:
      address: ":443"
  
  providers:
    docker:
      endpoint: "unix:///var/run/docker.sock"
      exposedByDefault: false
    file:
      filename: /traefik.yml
  
  certificatesResolvers:
    letsencrypt:
      acme:
        email: "{{ cf_email }}"
        storage: "/acme/acme.json"
        caServer: "https://acme-v02.api.letsencrypt.org/directory"
        dnsChallenge:
          provider: cloudflare
```

My docker compose file for zitadel stack:
```yaml
version: '3.8'
services:
  zitadel:
    container_name: zitadel
    restart: 'always'
    networks:
      - proxy
    ports:
      - '8080:8080'
    image: 'ghcr.io/zitadel/zitadel:stable'
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "MyMasterKey" --tlsMode external'
    depends_on:
      certs:
        condition: 'service_completed_successfully'
    volumes:
      - './zitadel-config.yaml:/zitadel-config.yaml:ro'
      - './zitadel-secrets.yaml:/zitadel-secrets.yaml:ro'
      - './zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro'
      - 'zitadel-certs:/crdb-certs:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.entrypoints=web"
      - "traefik.http.routers.zitadel.rule=Host(`zitadel.mydomain.com`)"
      - "traefik.http.middlewares.zitadel-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.routers.zitadel.middlewares=zitadel-https-redirect"
      - "traefik.http.routers.zitadel-secure.entrypoints=websecure"
      - "traefik.http.routers.zitadel-secure.rule=Host(`zitadel.mydomain.com`)"
      - "traefik.http.routers.zitadel-secure.tls=true"
      - "traefik.http.routers.zitadel-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"

  certs:
    container_name: zitadel-certs
    image: 'cockroachdb/cockroach:v22.1.0'
    entrypoint: [ '/bin/bash', '-c' ]
    command: [ 'cp /certs/* /zitadel-certs/ && cockroach cert create-client --overwrite --certs-dir /zitadel-certs/ --ca-key /zitadel-certs/ca.key zitadel_user && chown 1000:1000 /zitadel-certs/*' ]
    networks:
      - proxy
    volumes:
      - 'certs:/certs:ro'
      - 'zitadel-certs:/zitadel-certs:rw'
    depends_on:
      zid-cockroach-db:
        condition: 'service_healthy'

  zid-cockroach-db:
    container_name: zitadel-cockroach
    restart: 'always'
    networks:
      - proxy
    image: 'cockroachdb/cockroach:v22.1.0'
    command: 'start-single-node --advertise-addr zid-cockroach-db'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '38081:8080'
      - '26257:26257'
    volumes:
      - 'certs:/cockroach/certs:rw'
      - 'data:/cockroach/cockroach-data:rw'

networks:
  proxy:
    external: true
    name: proxy

volumes:
  certs:
  zitadel-certs:
  data:
```

Is there anything wrong with my config? 
Any help would be gladly appreciated

Thanks a lot :)

**Comment by lumpidu** [comment]
I have setup zitadel recenty with a very similar setup.

Looking over your config doesn't really show blatantly problematic issues. What I definitely would change is to not put Cr-db on the same network as the proxy. I'd add another internal network for the Zitadel => Cr-DB communication and add both networks to the Zitadel service. This way, only Zitadel is exposed to the proxy.

Furthermore: you probably won't expose the Cr-DB port on all interfaces on your host as well, but only to Zitadel, right ? So an `expose: ....` should suffice.

Then (opinionated) I'd rename your volumes to sth. less generic and prefix them with `zitadel`/`zitadel-cr-` so that after some while you don't accidently delete them when pruning your docker instance from unwanted images/volumes/etc.

**Reply by lumpidu** [reply]
Related to your issue: can you reach your Zitadel instance from within traefik via `ping zitadel` ?

You can test this via:

```bash
docker exec -it traefik sh
```

and then

```bash
ping zitadel
```

**Reply by urihani** [reply]
Yes i can ping zitadel from traefik:

```bash
/ # ping zitadel
PING zitadel (172.18.0.17): 56 data bytes
64 bytes from 172.18.0.17: seq=0 ttl=64 time=0.160 ms
64 bytes from 172.18.0.17: seq=1 ttl=64 time=0.063 ms
64 bytes from 172.18.0.17: seq=2 ttl=64 time=0.076 ms
64 bytes from 172.18.0.17: seq=3 ttl=64 time=0.056 ms
```

I modified the docker compose file to apply some of your suggestions:

```yaml
version: '3.8'
services:
  zitadel:
    container_name: zitadel
    restart: 'always'
    networks:
      - proxy
      - cr
    ports:
      - '8080:8080'
    image: 'ghcr.io/zitadel/zitadel:stable'
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "MyMasterKey" --tlsMode external'
    depends_on:
      certs:
        condition: 'service_completed_successfully'
    volumes:
      - './zitadel-config.yaml:/zitadel-config.yaml:ro'
      - './zitadel-secrets.yaml:/zitadel-secrets.yaml:ro'
      - './zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro'
      - 'zitadel-certs:/crdb-certs:ro'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.entrypoints=web"
      - "traefik.http.routers.zitadel.rule=Host(`zitadel.mydomain.com`)"
      - "traefik.http.middlewares.zitadel-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.routers.zitadel.middlewares=zitadel-https-redirect"
      - "traefik.http.routers.zitadel-secure.entrypoints=websecure"
      - "traefik.http.routers.zitadel-secure.rule=Host(`zitadel.mydomain.com`)"
      - "traefik.http.routers.zitadel-secure.tls=true"
      - "traefik.http.routers.zitadel-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"

  certs:
    container_name: zitadel-certs
    image: 'cockroachdb/cockroach:v22.1.0'
    entrypoint: [ '/bin/bash', '-c' ]
    command: [ 'cp /certs/* /zitadel-certs/ && cockroach cert create-client --overwrite --certs-dir /zitadel-certs/ --ca-key /zitadel-certs/ca.key zitadel_user && chown 1000:1000 /zitadel-certs/*' ]
    networks:
      - cr
    volumes:
      - 'certs:/certs:ro'
      - 'zitadel-certs:/zitadel-certs:rw'
    depends_on:
      zid-cockroach-db:
        condition: 'service_healthy'

  zid-cockroach-db:
    container_name: zitadel-cockroach
    restart: 'always'
    networks:
      - cr
    expose:
      - '26257'
    image: 'cockroachdb/cockroach:v22.1.0'
    command: 'start-single-node --advertise-addr zid-cockroach-db'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '38081:8080'
    volumes:
      - 'certs:/cockroach/certs:rw'
      - 'zitadel-cr-data:/cockroach/cockroach-data:rw'

networks:
  proxy:
    external: true
    name: proxy
  cr:
    internal: true

volumes:
  certs:
  zitadel-certs:
  zitadel-cr-data:
```

Now i've got a gateway timeout:
<img width="730" alt="image" src="https://github.com/zitadel/zitadel/assets/11816614/379b984c-6a3d-47a2-8ce4-a795bef189a7">

Zitadel logs (i don't know if the service completed the migration):

```json
time="2023-11-21T18:49:34Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2023-11-21T18:49:34Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel_user
time="2023-11-21T18:49:35Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2023-11-21T18:49:35Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel_user
time="2023-11-21T18:49:35Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
time="2023-11-21T18:49:35Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:63"
time="2023-11-21T18:49:35Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=01_tables
time="2023-11-21T18:49:35Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=01_tables
time="2023-11-21T18:49:37Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=02_assets
time="2023-11-21T18:49:37Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=02_assets
time="2023-11-21T18:49:37Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=03_default_instance
time="2023-11-21T18:49:37Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=03_default_instance
time="2023-11-21T18:49:40Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=04_eventstore_indexes
time="2023-11-21T18:49:40Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=04_eventstore_indexes
time="2023-11-21T18:49:42Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=05_last_failed
time="2023-11-21T18:49:42Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=05_last_failed
time="2023-11-21T18:49:46Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=06_resource_owner_columns
time="2023-11-21T18:49:46Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=06_resource_owner_columns
time="2023-11-21T18:49:50Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=07_logstore
time="2023-11-21T18:49:50Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=07_logstore
time="2023-11-21T18:49:50Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=08_auth_token_indexes
time="2023-11-21T18:49:50Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=08_auth_token_indexes
time="2023-11-21T18:49:52Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=09_optimise_indexes
time="2023-11-21T18:49:52Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=09_optimise_indexes
time="2023-11-21T18:49:54Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=10_correct_creation_date
time="2023-11-21T18:49:54Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=10_correct_creation_date
time="2023-11-21T18:49:54Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=11_event_created_at
time="2023-11-21T18:49:54Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=11_event_created_at
I don't see any errors in cockroach db logs.
```

**Reply by urihani** [reply]
Also when restarting the container i saw that zitadel was stuck in this loop

```json
time="2023-11-21T21:31:22Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-21T21:31:27Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-21T21:31:32Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-21T21:31:37Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-21T21:31:42Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-21T21:31:47Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
```

**Reply by lumpidu** [reply]
I have the following labels in my traefik configuration of the zitadel service:

```yaml
labels:
      # exposing app externally via Traefik
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'traefik.http.routers.zitadel.rule=Host(`zitadel.mydomain.com`)'
      - 'traefik.http.routers.zitadel.tls=true'
      - 'traefik.http.routers.zitadel.tls.certresolver=main'
      - 'traefik.http.services.zitadel.loadbalancer.server.port=8080'
      # Redirect to https
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
      - 'traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true'
      - 'traefik.http.routers.redirect-to-https.rule=!PathPrefix(`/.well-known/acme-challenge/`)'
      - 'traefik.http.routers.redirect-to-https.middlewares=redirect-to-https'
```

I think, you need to add at least `'traefik.docker.network=proxy'`.

**Reply by urihani** [reply]
I did that to no effect. 
I'm beginning to doubt that the migration process is complete. It's still stuck on step 11. I think i should see a message for when the console is available?

```json
time="2023-11-22T17:27:06Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-22T17:27:11Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-22T17:27:16Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-22T17:27:21Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
time="2023-11-22T17:27:26Z" level=warning msg="migration already started, will check again in 5 seconds" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:118" migration step=11_event_created_at
```

**Reply by lumpidu** [reply]
Interesting. I tested to upgrade from `2.37.3` to `2.41.3`, but there I got always a `Page not found` error afterwards, which seem to be related to https://zitadel.com/docs/support/advisory/a10006 and probably https://zitadel.com/docs/support/advisory/a10007 as well. So for the moment, I don't upgrade and wait until the next stable version and then carefully read the release notes :).

And one should make a backup of all related Docker volumes before upgrading.

**Reply by urihani** [reply]
I tried downgrading to 2.37.3 but i still get a gateway error and my migration is still stuck.

**Comment by urihani** [comment, marked as answer]
I rewrote the whole thing and now it works fine.

Docker-compose:
```yaml
version: '3.8'

services:
  zitadel-external-tls:
    container_name: zitadel
    image: 'ghcr.io/zitadel/zitadel:v2.37.3'
    networks:
      - proxy
      - cr
    command: 'start-from-setup --masterkey "{{ zitadel_master_key }}" --config /zitadel-config.yaml --steps /zitadel-init-steps.yaml'
    environment:
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_TLS_ENABLED=false
      - ZITADEL_EXTERNALDOMAIN={{ zitadel_host_name }}
      - ZITADEL_DATABASE_COCKROACH_HOST=zitadel-db
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.entrypoints=web"
      - "traefik.http.routers.zitadel.rule=Host(`{{ zitadel_host_name }}`)"
      - "traefik.http.middlewares.zitadel-https-redirect.redirectscheme.scheme=websecure"
      - "traefik.http.routers.zitadel.middlewares=zitadel-https-redirect"
      - "traefik.http.routers.zitadel-secure.entrypoints=websecure"
      - "traefik.http.routers.zitadel-secure.rule=Host(`{{ zitadel_host_name }}`)"
      - "traefik.http.routers.zitadel-secure.tls=true"
      - "traefik.http.routers.zitadel-secure.tls.certresolver=letsencrypt"
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    depends_on:
      zitadel-init:
        condition: 'service_completed_successfully'
      zitadel-db:
        condition: 'service_healthy'

  zitadel-init:
    container_name: zitadel-init
    user: '$UID'
    image: 'ghcr.io/zitadel/zitadel:v2.37.3'
    networks:
      - cr
    command: 'init --config /zitadel-config.yaml'
    depends_on:
      zitadel-db:
        condition: 'service_healthy'
    environment:
      # Using an external domain other than localhost proofs, that the proxy configuration works.
      # If ZITADEL can't resolve a requests original host to this domain,
      # it will return a 404 Instance not found error.
      - ZITADEL_EXTERNALDOMAIN={{ zitadel_host_name }}
      # ZITADEL accesses the database via the docker network.
      - ZITADEL_DATABASE_COCKROACH_HOST=zitadel-db
      # In case something doesn't work as expected,
      # it can be handy to be able to read the access logs.
      - ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=true
      # For convenience, ZITADEL should not ask to change the initial admin users password.
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED=false
    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: '10s'
      timeout: '5s'
      retries: 5
      start_period: '10s'

  zitadel-db:
    container_name: zitadel-db
    restart: 'always'
    image: 'cockroachdb/cockroach:latest'
    networks:
      - cr
    command: 'start-single-node --insecure --http-addr :9090'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9090/health?ready=1']
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - "26257:26257"
      - "9090:9090"

networks:
  proxy:
    external: true
    name: proxy
  cr:
    internal: true
```

zitadel-config.yaml:
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
Log:
  Level: 'info'

# Make ZITADEL accessible over HTTP, not HTTPS
ExternalSecure: true
ExternalDomain: {{ zitadel_host_name }}
ExternalPort: 443

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    Host: 'zid-cockroach-db'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
        Cert: "/crdb-certs/client.zitadel_user.crt"
        Key: "/crdb-certs/client.zitadel_user.key"
    Admin:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
        Cert: "/crdb-certs/client.root.crt"
        Key: "/crdb-certs/client.root.key"

LogStore:
  Access:
    Stdout:
      Enabled: true
```

zitadel-init-steps.yaml:
```yaml
FirstInstance:
  Org:
    Name: {{ zitadel_instance_name }}
    Human:
      # use the loginname root@somename.id.domain.com
      Username: {{ zitadel_username }}
      Password: {{ zitadel_password }}
```
