### DISCUSSION TITLE
Persisting config/data using Docker

### DISCUSSION THREAD

**Discussion by Chaz6** [zitadel/zitadel#7089] [Q&A]
It is customary when deploying applications and services to provide paths to configuration and/or data so that they can be managed independently of the containers.

The example [docker-compose.yml](https://raw.githubusercontent.com/zitadel/zitadel/main/docs/docs/self-hosting/deploy/docker-compose.yaml) does not have any Docker volumes listed, and I could not find the answer on the [Zitadel website](https://zitadel.com/docs/self-hosting/deploy/compose).

An example configuration would be:

```yaml
services:
  frontend:
    image: node:lts
    volumes:
      - myapp:/home/node/app
volumes:
  myapp:
    external: true
```

What paths should I be using with my Zitadel and CockroachDB containers?
