### DISCUSSION TITLE
Provide client_id instead of auto-generated

### DISCUSSION THREAD

**Discussion by nareshkbohra** [zitadel/zitadel#7219] [Q&A] [answered]
Hi,
In zitadel, when creating a oidc client, client_id is autogenerated in format <some number>@<project name> . Can we change or provide the client_id beforehand? 

This will be helpful when doing multi-tenant setup where you want to have same client_id for all clients but client secret can be picked by secret configuration based on the domain.

For e.g.
While using envoy oauth2 filter, i can just use below configuration:
```
  credentials:
    client_id: foo
    token_secret:
      name: token
      sds_config:
        path: "/etc/envoy/<:HOST>/token-secret.yaml"
 ```
