### DISCUSSION TITLE
User could not be found

### DISCUSSION THREAD

**Discussion by hopewise** [zitadel/zitadel#7569] [Q&A]
I have started fresh deployment as:

```
sudo zitadel start-from-init --masterkey "..." --tlsMode external  --config /opt/zitadel/config_local.yaml --steps /opt/zitadel/init.yaml --init-projections=true
```

then did setup:

```
sudo zitadel setup --masterkey "..." --tlsMode external  --config /opt/zitadel/config_local.yaml --steps /opt/zitadel/init.yaml --init-projections=true
```

the started zitadel:
```
sudo zitadel start --masterkey "..." --tlsMode external  --config /opt/zitadel/config_local.yaml
```

but when I enter the user name `root@zitadel.localhost`  I get error `User could not be found`

Please advice, as user was defined in the --steps /opt/zitadel/init.yaml

```
#/opt/zitadel/init.yaml
FirstInstance:
  Org:
    Human:
    # use the loginname root@zitadel.localhost
      Username: 'root'
      Password: 'RootPassword1!'
```

```
#/opt/zitadel/config_local.yaml

ExternalSecure: true
ExternalDomain: mydomain.com
ExternalPort: 443
Port: 8090
Database:
    postgres:
        Host: 127.0.0.1
        Port: 5432
        Database: zitadel
        MaxOpenConns: 25
        MaxConnLifetime: 1h
        MaxConnIdleTime: 5m
        Options:
        User:
            Username: zitadel
            Password: mypass
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key:
        Admin:
            Username: zitadel
            Password: mypass
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key:
```

**Comment by hifabienne** [comment]
hei @hopewise 
Can you try using only root as username?
IT depends on the settings configured if you need only the username itself or if you need to suffix with the domain

**Comment by hopewise** [comment]
I tried root without domain and didn't work.
Is there any thing wrong with my installation steps as I shared?

How can I set the initial user from the db it self?

**Comment by hopewise** [comment]
oh @hifabienne  ,I found that it uses the external domain I set, so its `root@zitadel.mydomain.com`
I have passed the first step, now it asks me to activate the user, `Verify your e-mail with the code below and set your password.`

But I did not set any email to send the code to, also, I did not provide any SMTP settings.
Can I set the initial user to any email? or it has to start with zitadel? ex: zitadel.mydomain.com

Also, I noticed that it did not ask for the initial password **RootPassword1!** I put at `init.yaml` but rather went to the registration page

it seems that it did not use the `init.yaml` file at --steps option?
```
FirstInstance:
  Org:
    Human:
    # use the loginname root@zitadel.localhost
      Username: 'root'
      Password: 'RootPassword1!'
      Email:
        Address: 'info@mydomain.com'
          Verified: true
```
