### DISCUSSION TITLE
Zitadel as OIDC provider creates issue with matrix username like @=22username=22:somedomain.tld

### DISCUSSION THREAD

**Discussion by jessebot** [zitadel/zitadel#7596] [Q&A] [answered]
Hi Zitadel team and community!

Long time no see :) I hope you're all doing well.

The main issue today is that I can login to element (web frontend for matrix) via zitadel just fine, but the username generated looks like this `@=22username=22:somedomain.tld` instead of the expected `@username:somedomain.tld` or just `@username`.

This is the OIDC section of my homeserver.yaml (the config file for synapse, the home server for matrix):

```yaml
oidc_providers:
  - idp_id: zitadel
    idp_name: zitadel
    scopes:
      - openid
      - profile
    user_mapping_provider:
      config:
        display_name_template: '"{{ user.name }}"'
        localpart_template: '"{{ user.preferred_username }}"'
    issuer: https://zitadel.domain.tld
    client_id: 123456789012345@core
    client_secret: jfdaf1hjdsakhflkadshfjkldahsjkfldhsajklfh4sajklfhjdksalhfjkds
```

I had followed the [docs for keycloak from synapse here](https://github.com/element-hq/synapse/blob/develop/docs/openid.md#keycloak).
You can see my cross posted issue with synapse here: https://github.com/element-hq/synapse/issues/17011

<details>
<summary>screenshots of my matrix application in zitadel</summary>

<img width="725" alt="Screenshot of matrix config 1" src="https://github.com/zitadel/zitadel/assets/2389292/5ce9f76d-cab3-47c6-a880-dce223e6ea36">
<img width="731" alt="Screenshot of matrix config 2" src="https://github.com/zitadel/zitadel/assets/2389292/5c67b185-19f3-42f4-92b5-0450cbc55030">

</details>

Any ideas on how to make it not have `=22` in the username? 🤔
