### DISCUSSION TITLE
Customize console UI

### DISCUSSION THREAD

**Discussion by Tomomi-K1** [zitadel/zitadel#7644] [Q&A] [answered]
Can I customize this page? I want to add company logo and possibly a back link to go back to our application. Thanks!
I saw this [link](https://github.com/zitadel/zitadel/discussions/1916#discussioncomment-1063890) but I cannot find any information about branding zitadel console.
![image](https://github.com/zitadel/zitadel/assets/31785367/24f74f06-5420-4666-9be6-6da3ed909e36)

**Comment by hifabienne** [comment]
Hi @Tomomi-K1 
There is no possibility to customize this page.
In earlier versions it was possible to also change the branding and this was also used for the management console.
Now In the management console only the logo and icon will change according to branding.
 
If you need a customized page, we recommend building it in your own application by using our APIs.

**Comment by Tomomi-K1** [comment]
@hifabienne Thank you so much for quickly responding!! I'm sorry but I don't understand the difference between the screenshot page and the management console. What's management console?
So even a logo cannot be changed on the above screenshot?

**Reply by hifabienne** [reply]
The screenshot page you have sent is part of the management console. It is the application where you can manage all the resources of ZITADEL and also where you have the user profile page.
Logo and icon are possible to change for that page, by configuring the branding. But the colors will not be taken.

**Reply by Tomomi-K1** [reply]
@hifabienne I see! I went to `/ui/console/org-settings?id=branding` and uploaded the logo and applied the setting but top left logo is still Zitadel logo. Is there any other url that I need to go and change the branding or management console?
we are self-hosting the zitadel so we have config.yml file. Where do I put logo information and how do I point to the logo in the folder of the application?
I tried adding logo like this, but did not work.
```
LabelPolicy:
    PrimaryColor: '#6544C9' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_PRIMARYCOLOR
    BackgroundColor: '#fafafa' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_BACKGROUNDCOLOR
    WarnColor: '#cd3d56' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_WARNCOLOR
    FontColor: '#000000' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_FONTCOLOR
    PrimaryColorDark: '#6544C9' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_PRIMARYCOLORDARK
    BackgroundColorDark: '#111827' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_BACKGROUNDCOLORDARK
    WarnColorDark: '#ff3b5b' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_WARNCOLORDARK
    FontColorDark: '#ffffff' # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_FONTCOLORDARK
    HideLoginNameSuffix: true # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_HIDELOGINNAMESUFFIX
    ErrorMsgPopup: false # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_ERRORMSGPOPUP
    DisableWatermark: true # ZITADEL_DEFAULTINSTANCE_LABELPOLICY_DISABLEWATERMARK
    LogoUrl: '/direct-path-to-the-img'
    IconUrl: '/direct-path-to-the-img'
    LogoUrlDark: '/direct-path-to-the-img'
    IconUrlDark:'/direct-path-to-the-img'
```
