### DISCUSSION TITLE
Correct value for "KeyData" in the "SystemAPIUsers" config section

### DISCUSSION THREAD

**Discussion by ratermir** [zitadel/zitadel#7715] [Q&A] [answered]
I installing Zitadel in kubernetes (microk8s). I tried to let Zitadel to create system account to be able to call system API. I followed procedure here: https://zitadel.com/docs/guides/integrate/zitadel-apis/access-zitadel-system-api, I added part to the configmap of zitadel config file as follow:
```
SystemAPIUsers:
  - myusername:
      KeyData: <base64 encoded value of system-user-1.pub>
```

But if I put content of the public key file wrapped into base64 in place of "\<base64 encoded value of system-user-1.pub\>", setup container ended with error and I got following mwssage in the "zitadel-setup-XXXXXX" container (i.e. setup procedure): 

```
time="2024-04-07T20:47:53Z" level=fatal msg="unable to read default config" caller="/home/runner/work/zitadel/zitadel/cmd/setup/config.go:75" error="1 error(s) decoding:\n\n* 'SystemAPIUsers[0][keydata]' expected a map, got 'string'"
```

Here is the whole config map:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-config-yaml
  labels:
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: ar-idp
    app.kubernetes.io/version: "v2.46.0"
data:
  zitadel-config-yaml: |-
    
    Database:
      Postgres:
        Admin:
          SSL:
            Mode: disable
          Username: zitadel
          Password: zitadeluspwd
        Database: zitadel
        Host: db
        MaxConnIdleTime: 5m
        MaxConnLifetime: 30m
        MaxIdleConns: 10
        MaxOpenConns: 20
        Port: 5432
        User:
          SSL:
            Mode: disable
          Username: zitadel
          Password: zitadeluspwd
    ExternalDomain: dev.anirad.cz
    ExternalPort: 32400
    ExternalSecure: false
    Machine:
      Identification:
        Hostname:
          Enabled: true
        Webhook:
          Enabled: false
    TLS:
      Enabled: false
    SystemAPIUsers:
      - myusername:
        KeyData: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6ZWZsbUJYMnVIaldmTjczbDRSVwp2dWl5WEIwMXp0ZTQyTUd3ODJBdDN6aGJ0MG44Wmx0anM1ejdkNGdtb0kva245N3hNd0VoSzhEbEZHbVRyRUxqCjBWeUtzT2FlZTJ5d3lsSmZGUHVaeTBxUmxZNGRGSm9pNExrVFp5bzhLNmR5STVmVUpCWEF0RzBQVGcxWk9ZWmMKeE1JbHg0SlR4dEppMTlqUmdFQTBINHlHR2h1bm9mWFkvcFVxUXdRN0NnRGloRm1wZXNuQjlnYVlJZGtub3VTNAplV3JsNlY3ZjdjS1hEWDB3YzdIQzMvbW1lUGE1U1pDZ0VJcHVpdUhZSllkc2FucWFVNGlnQndKYlBYeUpxME9JCko3Yk1DZm1NeHRlUkRlMDJmeU16cTRiVENCRklWaGtCOVpuSXJvYlE3dGJGc2t5NGtUNjJYNHRJUnFkYTM0N1kKOFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

```

Can someone help me what I am doing wrong? Is there any detailed documentation os the "SystemAPIUsers" part of config?
Thx

**Comment by fforootd** [comment, marked as answer]
Hm that is a weird one.

Mabye @eliobischof has an idea, but from looking at it I got the feeling that indenting could be an issue.

Does it work if you indent `keyData`?

```yaml
SystemAPIUsers:
      - myusername:
          KeyData: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF6ZWZsbUJYMnVIaldmTjczbDRSVwp2dWl5WEIwMXp0ZTQyTUd3ODJBdDN6aGJ0MG44Wmx0anM1ejdkNGdtb0kva245N3hNd0VoSzhEbEZHbVRyRUxqCjBWeUtzT2FlZTJ5d3lsSmZGUHVaeTBxUmxZNGRGSm9pNExrVFp5bzhLNmR5STVmVUpCWEF0RzBQVGcxWk9ZWmMKeE1JbHg0SlR4dEppMTlqUmdFQTBINHlHR2h1bm9mWFkvcFVxUXdRN0NnRGloRm1wZXNuQjlnYVlJZGtub3VTNAplV3JsNlY3ZjdjS1hEWDB3YzdIQzMvbW1lUGE1U1pDZ0VJcHVpdUhZSllkc2FucWFVNGlnQndKYlBYeUpxME9JCko3Yk1DZm1NeHRlUkRlMDJmeU16cTRiVENCRklWaGtCOVpuSXJvYlE3dGJGc2t5NGtUNjJYNHRJUnFkYTM0N1kKOFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
```
