### DISCUSSION TITLE
Forward Auth (Traefik)

### DISCUSSION THREAD

**Discussion by Aurel004** [zitadel/zitadel#7716] [Q&A]
Hi,

I'm trying to switch from Authentik to Zitadel and I've seen that it does not support forward auth (it may have changed ?) but instead I can use OAuth2 proxy. My question then is, do I have to run 1 individual OAuth2 Proxy container for each service I want behind it?
Thinking of things like one for Sonarr, one for Radarr etc

There is no easier solution ?

Thank you

**Comment by fforootd** [comment]
Hey

You could deploy one oauth proxy and attach multiple apps behind it based on their paths (your proxy would need to handle this).
Another option would be to use caddy with the openid plugin and then route to the backends by config.

https://github.com/greenpau/caddy-security

**Comment by Aurel004** [comment]
> Hey
> 
> 
> 
> You could deploy one oauth proxy and attach multiple apps behind it based on their paths (your proxy would need to handle this).
> 
> Another option would be to use caddy with the openid plugin and then route to the backends by config.
> 
> 
> 
> https://github.com/greenpau/caddy-security

With OAuth proxy is it only by path ? As everything runs under subdomains (sonarr.mydomain.com, radarr.mydomain.com etc)
Or maybe I can redirect a path to the subdomain

I do not use Caddy but Traefik, do you know if it's possible with it ? I've seen it might only be with Traefik Enterprise..

Thanks

**Reply by fforootd** [reply]
Ah its separated by domain, got it.

I think you could make it work with one oauth proxy. Have you looked into this blog https://joeeey.com/blog/selfhosting-sso-with-traefik-oauth2-proxy-part-2/ ?

Especially this piece looks like you can reuse the auth middleware https://joeeey.com/blog/selfhosting-sso-with-traefik-oauth2-proxy-part-2/#configuring-oauth2-proxy-with-traefik

**Comment by Aurel004** [comment]
> Ah its separated by domain, got it.
> 
> I think you could make it work with one oauth proxy. Have you looked into this blog https://joeeey.com/blog/selfhosting-sso-with-traefik-oauth2-proxy-part-2/ ?
> 
> Especially this piece looks like you can reuse the auth middleware https://joeeey.com/blog/selfhosting-sso-with-traefik-oauth2-proxy-part-2/#configuring-oauth2-proxy-with-traefik

Okay I might be on a lucky day, I made it working for whoami on almost first shot (2nd shot...)
But for Sonarr, I would like to use Header HTTP-Basic Authentication and I can't make it working as I do not know where to put the username and password, do you have any idea ?

I'm adding config files for whoever needs it working for whoami :
docker-compose.yml (oauth2proxy)
```
version: "3.2"
services:
  oauth2proxy:
    # internal: oauth2proxy on port 4180
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2_proxy
    restart: unless-stopped
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      OAUTH2_PROXY_COOKIE_SECRET: 'XXXX' #Generated with the doc of OAuth2 Proxy
      OAUTH2_PROXY_COOKIE_DOMAINS: '.mydomain.com' # Required so cookie can be read on all subdomains.
      OAUTH2_PROXY_WHITELIST_DOMAINS: '.mydomain.com' # Required to allow redirection back to original requested target.
      # Configure to use Zitadel
      OAUTH2_PROXY_PROVIDER: 'oidc'
      OAUTH2_PROXY_CLIENT_ID: 'XXXX' #Client ID given by Zitadel
      OAUTH2_PROXY_CLIENT_SECRET: 'XXXX' #Client Secret given by Zitadel
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_OIDC_ISSUER_URL: 'https://zitadel.mydomain.com'
      OAUTH2_PROXY_REDIRECT_URL: 'https://auth1.mydomain.com/oauth2/callback'
      OAUTH2_PROXY_FORCE_CODE_CHALLENGE_METHOD: 'S256'
      #
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: true
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: '5m'
      OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR: "/templates"
      OAUTH2_PROXY_REVERSE_PROXY: true
    volumes:
      - ./config/templates:/templates:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route-authproxy.rule=(Host(`auth1.mydomain.com`) && PathPrefix(`/oauth2/`)) || (PathPrefix(`/oauth2/`))"
      - "traefik.http.services.route-authproxy.loadbalancer.server.port=4180"
    networks:
      - oauth2-proxy
#For traefik, I use one network for each service for security reasons
networks:
  oauth2-proxy:
    external: true
```

oauth2proxy_middleware.yml (dynamic traefik config)
```
http:
  middlewares:
    oauth:
      chain:
        middlewares:
          - oauth-signin
          - oauth-verify

    oauth-verify:
        forwardAuth:
            address: "http://oauth2proxy:4180/oauth2/auth"
    oauth-signin:
        errors:
            service: route-authproxy@docker
            status: "401"
            query: "/oauth2/sign_in"
```

docker-compose.yml (whoami)
```
version: "3.2"
services:
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.mydomain.com`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.middlewares=oauth@file" #Match name in http: middlewares: in the dynamic traefik config
```
