### DISCUSSION TITLE
External Login Provider not allowed

### DISCUSSION THREAD

**Discussion by kuroki-kael** [zitadel/zitadel#7738] [Q&A] [answered]
Hi,
I successfully installed Zitadel using Docker. I set up a few service that support Oauth2 natively and it worked just fine.
Lastly I set up Oauth2-Proxy for the services that don't have Oauth2. First it worked, i didn't even see the Oauth2-Proxy when connecting to some services, so to test it properly I logged out of Zitadel but since then I can't log in anymore. It just says: "External Login Provider not allowed"

Can someone help me please?

Edit: I can't even use Google or GitHub, that I also have to set up as Oauth methods in Zitadel. The option for those does not show up either.

**Comment by fforootd** [comment]
Hm weird, what happens if you try incognito mode?

**Reply by kuroki-kael** [reply]
Still exactly the same. I also tried in another browser, from another device and from outside my network over my Zitadel domain.

**Comment by kuroki-kael** [comment]
Got it somehow working after fiddeling around and setting up Zitadel and Oauth2-Proxy from scratch. Tho the upstream from the proxy doesn't work

**Reply by fforootd** [reply]
Oh that is great to hear, can you share config?

I think this could help others (and me) 😁

**Reply by kuroki-kael** [reply, marked as answer]
Sure, I mostly copied it from some guys but I sadly don't rember who, so no credits 😞 
If you get the upstream working, I'd appreciate to know how because for me it doesn't work as mentioned.
Edit: Found some credit @Aurel004

Edit: Maybe tho I got something in the Zitadel config wrong as well. Everytime I log out of for example portainer, I get redirect to the logout screen from Zitadel but can't get redirected back to portainer again.

Here is my docker compose from portainer:

```
version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
      - "proxy"
    image: "ghcr.io/zitadel/zitadel:stable"
    # ZITADEL_MASTERKEY:  # run tr -dc A-Za-z0-9 </dev/urandom | head -c 32 // 
    command: 'start-from-init --config /example-zitadel-config.yaml --config /example-zitadel-secrets.yaml --steps /example-zitadel-init-steps.yaml --masterkey "${MASTERKEY}" --tlsMode external'
    depends_on:
      certs:
        condition: "service_completed_successfully"
    environment:
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: Admin1!@oauth2.[domain.com]
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: Password1!
    ports:
      - "8080:8080"
    volumes:
      - "/container/zitadel/example-zitadel-config.yaml:/example-zitadel-config.yaml:ro"
      - "/container/zitadel/example-zitadel-secrets.yaml:/example-zitadel-secrets.yaml:ro"
      - "/container/zitadel/example-zitadel-init-steps.yaml:/example-zitadel-init-steps.yaml:ro"
      - "zitadel-certs:/crdb-certs:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.entrypoints=http" #required even with redirecting to https in config file
      - "traefik.http.routers.zitadel.rule=Host(`zitadel.[domain.com]`)"
      - "traefik.http.middlewares.zitadel-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.zitadel.middlewares=zitadel-https-redirect"
      - "traefik.http.routers.zitadel-secure.entrypoints=https"
      - "traefik.http.routers.zitadel-secure.rule=Host(`zitadel.[domain.com]`)"
      - "traefik.http.routers.zitadel-secure.tls=true"
      - "traefik.http.routers.zitadel-secure.service=zitadel"
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"

  certs:
    image: "cockroachdb/cockroach:latest"
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "cp /certs/* /zitadel-certs/ && cockroach cert create-client --overwrite --certs-dir /zitadel-certs/ --ca-key /zitadel-certs/ca.key zitadel_user && chown 1000:1000 /zitadel-certs/*",
      ]
    volumes:
      - "/container/zitadel/data/certs:/certs:ro"
      - "zitadel-certs:/zitadel-certs:rw"
    depends_on:
      my-cockroach-db:
        condition: "service_healthy"

  my-cockroach-db:
    restart: "always"
    networks:
      - "zitadel"
    image: "cockroachdb/cockroach:latest"
    command: "start-single-node --advertise-addr my-cockroach-db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    #ports:
    #  - "9090:8080"
    #  - "26257:26257"
    volumes:
      - "/container/zitadel/data/certs:/cockroach/certs:rw"
      - "/container/zitadel/data/cockroach:/cockroach/cockroach-data:rw"
      
  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: '0.0.0.0:4180'
      #OAUTH2_PROXY_COOKIE_SECURE: false
      OAUTH2_PROXY_COOKIE_SECRET: '${SECRET_KEY}' #Generated with the doc of OAuth2 Proxy
      OAUTH2_PROXY_COOKIE_DOMAINS: '[domain.com]' # Required so cookie can be read on all subdomains.
      OAUTH2_PROXY_WHITELIST_DOMAINS: '[domain.com]' # Required to allow redirection back to original requested target.
      OAUTH2_PROXY_UPSTREAMS: 'https://homarr.local.[domain.com]'
      # Configure to use Zitadel
      OAUTH2_PROXY_PROVIDER: 'oidc'
      OAUTH2_PROXY_CLIENT_ID: '${CLIENT_ID}' #Client ID given by Zitadel
      OAUTH2_PROXY_CLIENT_SECRET: '${CLIENT_SECRET}' #Client Secret given by Zitadel
      OAUTH2_PROXY_EMAIL_DOMAINS: '*'
      OAUTH2_PROXY_OIDC_ISSUER_URL: 'https://zitadel.[domain.com]'
      OAUTH2_PROXY_REDIRECT_URL: 'https://auth.[domain.com]/oauth2/callback'
      OAUTH2_PROXY_FORCE_CODE_CHALLENGE_METHOD: 'S256'
      #
      OAUTH2_PROXY_COOKIE_CSRF_PER_REQUEST: true
      OAUTH2_PROXY_COOKIE_CSRF_EXPIRE: '5m'
      OAUTH2_PROXY_CUSTOM_TEMPLATES_DIR: "/templates"
      OAUTH2_PROXY_REVERSE_PROXY: true
    volumes:
      - /zitadel/data/oauth/templates:/templates:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.route-authproxy.entrypoints=https"
      - "traefik.http.routers.route-authproxy.middlewares=secHeaders@file"
      - "traefik.http.routers.route-authproxy.tls=true"
      - "traefik.http.routers.route-authproxy.tls.certresolver=cloudflare"
      - "traefik.http.routers.route-authproxy.rule=(Host(`auth.[domain.com]`) && PathPrefix(`/oauth2/`) || PathPrefix(`/oauth2/`))"
      - "traefik.http.services.route-authproxy.loadbalancer.server.port=4180"
      - "traefik.docker.network=proxy"
    networks:
        - "proxy"

networks:
  zitadel:
  proxy:
    external: true
    
volumes:
  zitadel-certs:
``` 

And that's my middleware config in traefik, if needed:

```
http:
    oauth:
      chain:
        middlewares:
          - oauth-signin
          - oauth-verify
    oauth-verify:
        forwardAuth:
            address: "https://auth.[domain.com]/oauth2/auth"
    oauth-signin:
        errors:
            service: route-authproxy@docker
            status: "401"
            query: "/oauth2/sign_in"
```
