### DISCUSSION TITLE
Zitadel with Hasura

### DISCUSSION THREAD

**Discussion by jeffdev11** [zitadel/zitadel#8013] [Q&A]
Does anyone know how to integrate Hasura with Zitadel?

**Comment by mffap** [comment]
We don't have an official guide yet, but an integration guide with Hasura is on our roadmap. Is there certain aspects that we should cover?

**Reply by jeffdev11** [reply]
I understand, thank you. I just need a simple example of integrating authentication with Zitadel and authorization with Hasura.

**Reply by mffap** [reply]
I know that we have some users and customers that integrated with [Hasura JWT authentication](https://hasura.io/docs/latest/auth/authentication/jwt/) successfully. The key here is to configure ZITADEL's app to use JWT (instead of bearer tokens) and then provide the `x-hasura-*` custom claims,I think. You can use [Actions](https://zitadel.com/docs/apis/actions/introduction) to complement a token with your custom claims, see the examples on how to [customize oidc response](https://zitadel.com/docs/apis/actions/code-examples#customize-oidc-response) with Actions.

Does that make sense?

**Reply by jeffdev11** [reply]
I think so, i'll give it a try, thanks for the help!

**Comment by Kalcode** [comment]
Curious also, it seems Hasura just wants the PUBLIC key, but we only get the PRIVATE KEY and not the pair when we make a key. Did you find a solution?

**Reply by fforootd** [reply]
I am not following, can you share docs or screenshots?

Does Hasura want the public key that Zitadel uses to sign the tokens?
Because this is documented here https://zitadel.com/docs/apis/openidoauth/endpoints#jwks_uri

**Reply by Kalcode** [reply]
Yah, you are correct. This seems to be the path forward but I couldn't get it to work. 

Zitadel blocks anything that's not it's custom domain "localhost", and zitadel is "zitadel:8050" in the docker compose and it keeps saying that origin not supported. 

Was gonna report back if I could get that unblocked but I did.

**Reply by fforootd** [reply]
How did you deploy Zitadel?

You can configure the domains Zitadel listens to with the `EXTERNAL_DOMAIN` env.

**Reply by Kalcode** [reply]
Got it working. I deployed zitadel and hasura in the same docker-compose.

I use `zitadel` inside the container to reference it. So `http://zitadel:8050/oauth/v2/keys`

But the since the external domain is `localhost`, I get a `Instance not found` error. With the externaldomain it has `localhost` not `zitadel`

I can't do `http://localhost:8050/oauth/v2/keys`, because localhost is not the same in the container, its `host.docker.internal`, which doesn't match the the external domain. Error.

So I had to change the hostname of the container, and then I found if I had the domain as `zitadel.localhost` is doesn't like `zitadel.localhost:8050` either. So then I had to put the port `ZITADEL_EXTERNALDOMAIN: zitadel.localhost:8050` and now it seems to be working and hasura can access the public keys. Which seems very, I don't janky. 

```sh
 Version                : v2.65.1
 TLS enabled            : false
 External Secure        : false
 Machine Id Method      : Private Ip
 Console URL            : http://zitadel.localhost:8050:8050/ui/console
 Health Check URL       : http://zitadel.localhost:8050:8050/debug/healthz
```

So now it thinks it endpoint is `http://zitadel.localhost:8050:8050/ui/console` but I can still reach it at `http://zitadel.localhost:8050/ui/console` So I am gonna see if this unblocks me without side-effect.

Why wouldn't it just care about the domain? 

```yaml
name: hjord-api
services:
  postgres:
    container_name: postgres
    image: postgis/postgis:15-3.4
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

  graphql-engine:
    container_name: graphql-engine
    image: hasura/graphql-engine:v2.44.0
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      # postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres?sslmode=disable
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres?sslmode=disable
      HASURA_GRAPHQL_ENABLE_SPATIAL_TYPES: 'true'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"jwk_url":"http://zitadel.localhost:8050/oauth/v2/keys"}'
  
  zitadel:
    hostname: zitadel.localhost
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      ZITADEL_EXTERNALDOMAIN: zitadel.localhost:8050
      ZITADEL_EXTERNALPORT: 8050
      ZITADEL_PORT: 8050
      ZITADEL_DATABASE_POSTGRES_HOST: postgres
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: postgrespassword
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgrespassword
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: false
    depends_on:
      postgres:
        condition: 'service_healthy'
    ports:
      - '8050:8050'
```


How else do you do a cluster together where the external name is different from the internal name?
