### DISCUSSION TITLE
Custom font and logo on self hosted Zitadel

### DISCUSSION THREAD

**Discussion by musicformellons** [zitadel/zitadel#8216] [Q&A]
I see in the docs the possilibity of uploading custom font and logo (e.g. using the Assets API). AFAICT it seems all to refer to the hosted Zitadel. When self hosting will this still work, or how should that be configured?

**Comment by fforootd** [comment]
This feature works in the cloud and self-hosted. 

You can set instance wide settings under this path `/ui/console/instance?id=branding`

Docs are here https://zitadel.com/docs/guides/manage/customize/branding

**Comment by musicformellons** [comment]
Ah yeah, I tested with the 'human admin user' and indeed that works nicely for both a logo and a custom font when setting these via the GUI. As I'm using a 'self bootstrapping instance' I tried to get it into my `zitadel-config.yaml` like this (excerpt):
```
DefaultInstance:
    LabelPolicy:
        PrimaryColor: '#e0da8e'
        BackgroundColor: '#ffffff'
        WarnColor: '#db2828'
        FontColor: '#555555'
        PrimaryColorDark: '#e0ba8e'
        BackgroundColorDark: '#555555'
        WarnColorDark: '#db2828'
        FontColorDark: '#ffffff'
        HideLoginNameSuffix: true
        ErrorMsgPopup: false
        DisableWatermark: true
        LogoURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
        IconURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
        LogoDarkURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
        IconDarkURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
        Font: https://github.com/mygithubaccount/assets/raw/main/customfont.ttf
```
The LabelPolicy properties are all picked up except from the last 5 (`LogoURL` till `Font`). The repository urls are public BTW. I don't find any related errors AFAICT (in the docker container output). Is there a way to set these via config file, or am I doing something wrong?

I tried also to put them in into single quotes, still not working.
