### DISCUSSION TITLE
Creating initial data using the API

### DISCUSSION THREAD

**Discussion by atreya2011** [zitadel/zitadel#8296] [Q&A] [answered]
Amazing work on the documentation. However, I was unable find info on how to create initial data after setting skip to false in the steps.yml.

The API requires some sort of token when calling it. So how do I create just the data with the API when there is no user or machine user already present in the system?

**Comment by hifabienne** [comment, marked as answer]
Hi @atreya2011 
In an instance you will always need a user to create data.

One possibility is to take a system user, the system user is above all the instances and can also create data. but this is not the recommended way. 
So the way would be to create a new instance with the system user, with an initial human or machine user, and after that use the created first user the setup the rest of the data.

So the skip flag makes only sense to set to true, if you want to setup multiple instance all in the same way with the system user.

**Reply by atreya2011** [reply]
Hi @hifabienne 

Thank you for the quick response. Correct me if my understanding is incorrect.
The recommended way would be to

- Create a new instance with either a human or machine user
- Use the created human or machine user to set the rest of the data

Following your recommendation, I created an initial machine user using the following env settings in the docker-compose file.

```yaml
  zitadel:
    container_name: zitadel
    restart: always
    image: "ghcr.io/zitadel/zitadel:v2.56.0"
    command: "start-from-init --masterkey 'MasterkeyNeedsToHave32Characters' --tlsMode disabled"
    environment:
      - "ZITADEL_DATABASE_COCKROACH_HOST=db"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/machinekey/zitadel-admin-sa.json"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=zitadel-admin-sa"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Admin"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./machinekey:/machinekey
    networks:
      - "zitadel"
 ```

This creates a JSON file which I should use to generate a JWT which in turn is used to create an access token
Following the guide in the below link, I could generate a JWT successfully.
https://zitadel.com/docs/guides/integrate/service-users/private-key-jwt#3-create-a-jwt-and-sign-with-private-key

However, when I use this JWT to generate an access token by using the following command
```shell
curl --request POST \
  --url http://localhost:8080/oauth/v2/token \
  --header 'Content-Type: application/x-www-form-urlencoded' \
  --data grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer \
  --data scope='openid' \
  --data assertion=eyJ0eXAiOiJKV1QiL...
```

I get the following error:
```shell
zitadel                        | time=2024-07-16T05:11:23.007Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(audience is not valid: Audience must contain client_id \"http://localhost:8080\")" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
```

I may be missing something fundamental here... Any help would be greatly appreciated 🙇🏼 

The Machine Key JSON file is like this
```json
{
  "type": "serviceaccount",
  "keyId": "276168082740346883",
  "key": "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEA1J8BwYOQmCc4j...",
  "userId": "276168082740281347"
}
```
