### DISCUSSION TITLE
Error: This client's redirect_uri is http and is not allowed.

### DISCUSSION THREAD

**Discussion by firstdorsal** [zitadel/zitadel#8308] [Q&A] [answered]
Hi! I installed zitadel like this
```yaml
repositories:
    - name: zitadel
      url: https://charts.zitadel.com

releases:
    - name: mows-cloud-apis-zitadel
      namespace: mows-cloud-apis-zitadel
      chart: zitadel/zitadel
      createNamespace: true
      version: 8.0.0
      values:
          - replicaCount: 1
            zitadel:
                masterkey: "huiwerfuhiewuihefwhuiiuihefwhuii"
                configmapConfig:
                    TLS:
                        Enabled: false
                    ExternalSecure: false
                    ExternalDomain: svc.rhv36zxe
                    ExternalPort: 80
                    Database:
                        postgres:
                            Host: zitadel-postgres-rw
                            Port: 5432
                            Database: app
                            MaxOpenConns: 25
                            MaxIdleConns: 10
                            MaxConnLifetime: 1h
                            MaxConnIdleTime: 5m
                            Options:
                            User:
                                Username: YXBw
                                Password: GyvhcHqzBw17szJOJ3OvfGGhbyOSxSG6VNtzx9vofxcNXIED8W4N5E2rp3abdaiO
                                SSL:
                                    Mode: disable
                                    RootCert:
                                    Cert:
                                    Key:
                            Admin:
                                Username: postgres
                                Password: uN3i1Hh0bYbCc4TyVAacBhmSzgqtzqxmOVjAn0QIChsJrSmu9PY2fw2q8EKKLpZ9
                                SSL:
                                    Mode: disable
                                    RootCert:
                                    Cert:
                                    Key:

```

 and created this traefik ingress route

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
    name: zitadel
    namespace: mows-cloud-apis-zitadel
spec:
    entryPoints:
        - web
    routes:
        - kind: Rule
          match: PathPrefix(`/`)
          services:
              - kind: Service
                namespace: mows-cloud-apis-zitadel
                name: mows-cloud-apis-zitadel
                port: 8080
```

When opening the page http://svc.rhv36zxe/ I now get the following error:

```json
{
  "error": "invalid_request",
  "error_description": "This client's redirect_uri is http and is not allowed. If you have any questions, you may contact the administrator of the application."
}
```

Do you have an idea why?

Thanks!
