### DISCUSSION TITLE
SA jwt token for api application doesn't work

### DISCUSSION THREAD

**Discussion by miran248** [zitadel/zitadel#8366] [Q&A]
Hey,

Not sure what i'm doing wrong but whenever i try to use the received access token (from `/oauth/v2/token`) i get the error response - so far i have tried `/oauth/v2/introspect`, `/oauth/v2/authorize` and `/v2/users/human`.
I'll include the requests and responses for all mentioned endpoints but if we can get the introspect working i can do the rest.

Every request contains at least one of these errors
```console
commit of read only transaction failed
sql: transaction has already been committed or rolled back
query failed
sql: no rows in result set
could not obtain lock on row in relation "current_states"
unauthorized_client
invalid token
Errors.App.NotFound
invalid audience
```

I'm almost certain the problem is somewhere at the jwt + token creation and the rest is just noise.
All ids match those on dashboard and yet some responses indicate it's not finding db records.
[v2.56.0](https://github.com/zitadel/zitadel/releases/tag/v2.56.0) contains [6222](https://github.com/zitadel/zitadel/issues/6222) which removes `@project` suffix - i have tried including it but it made no difference. Related? I don't know, might need to try `v2.55.0`.

`unauthorized_client` was suspicious so i gave service account explicit authorization to the project - made no difference.

#### zitadel versions
```
v2.57.0
v2.58.0
v2.58.0-debug - what's the difference?
```

#### postgres
```16-alpine```

#### macos
```14.5```

#### node
```v22.4.1```

### setup
```typescript
import { createPrivateKey } from "crypto";
import { SignJWT } from "jose";

const serviceAccount = {
  type: "serviceaccount",
  keyId: "278076548773314563",
  key: "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n", // pem encoded pkcs1 key
  expirationDate: "9999-12-31T23:59:59Z",
  userId: "278076535737417731",
};

const privateKey = createPrivateKey(serviceAccount.key);

// https://zitadel.com/docs/apis/openidoauth/authn-methods#jwt-with-private-key
// https://github.com/panva/jose/blob/main/docs/classes/jwt_sign.SignJWT.md
const jwt = await new SignJWT({
  iss: serviceAccount.userId,
  sub: serviceAccount.userId,
  aud: [
    "http://localhost:8080",
    "http://localhost:3000",
  ], // port is required!
  iat: Math.floor(+new Date() / 1000),
  exp: Math.floor(+new Date() / 1000) + 60 * 60, // expires in 1 hour
})
  .setProtectedHeader({ alg: "RS256", kid: serviceAccount.keyId })
  .sign(privateKey);

const getAccessToken = async () => {
  const body = new URLSearchParams({
    grant_type: "urn:ietf:params:oauth:grant-type:jwt-bearer",
    assertion: jwt,
    scope:
      "openid email profile urn:zitadel:iam:org:project:id:278076207994503171:aud",
  });
  const response = await fetch(`http://localhost:8080/oauth/v2/token`, {
    method: "post",
    body,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
  });

  const data = await response.json();

  console.log("getAccessToken response", response.ok, data);

  return data.access_token;
};
const introspect = async (accessToken: string) => {
  const body = new URLSearchParams({
    client_assertion_type:
      "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
    client_assertion: jwt,
    token: accessToken,
  });
  const response = await fetch(`http://localhost:8080/oauth/v2/introspect`, {
    method: "post",
    body,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
    },
  });

  const data = await response.json();

  console.log("introspect response", response.ok, data);

  return data;
};
const authorize = async (accessToken: string) => {
  const body = new URLSearchParams({
    client_id: "278076229368741891", // client id from project's api application
  });
  const response = await fetch(`http://localhost:8080/oauth/v2/authorize`, {
    method: "post",
    body,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Authorization: `Bearer ${accessToken}`,
    },
  });

  const data = await response.json();

  console.log("authorize response", response.ok, data);

  return data;
};
const human = async (accessToken: string) => {
  const body = new URLSearchParams({});
  const response = await fetch(`http://localhost:8080/v2/users/human`, {
    method: "post",
    body,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      Authorization: `Bearer ${accessToken}`,
    },
  });

  const data = await response.json();

  console.log("human response", response.ok, data);

  return data;
};
```

### responses
```
getAccessToken response true { access_token: '...', token_type: 'Bearer', expires_in: 43199, id_token: '...' }
introspect response false { error: 'unauthorized_client' }
authorize response false { error: 'invalid_request', error_description: 'Errors.App.NotFound' }
homan response false { code: 16, message: 'Errors.Token.Invalid (AUTH-7fs1e)', details: [ { '@type': 'type.googleapis.com/zitadel.v1.ErrorDetail', id: 'AUTH-7fs1e', message: 'Errors.Token.Invalid' } ] }
```

### zitadel v2.57.0 (token and introspect)
```console
zitadel-1  | time="2024-07-29T08:43:49Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="http://localhost:8080" grpcStatus= httpStatus= instance=278076025475170307 isSystemUser=false method= org=278076025475235843 path=/oauth/v2/token requestMethod=POST trigger=accessToken user=278076535737417731
zitadel-1  | time="2024-07-29T08:43:49Z" level=info msg="commit of read only transaction failed" caller="/home/runner/work/zitadel/zitadel/internal/database/database.go:48" error="failed to deallocate cached statement(s): conn closed"
zitadel-1  | time="2024-07-29T08:43:49Z" level=info msg="query failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/query.go:129" error="context canceled"
zitadel-1  | time=2024-07-29T08:43:49.310Z level=WARN msg="request error" oidc_error.parent="sql: no rows in result set" oidc_error.type=unauthorized_client status_code=400
```

### zitadel v2.58.0 (token and introspect)
```console
zitadel-1  | time="2024-07-30T09:24:40Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="http://localhost:8080" grpcStatus= httpStatus= instance=278076025475170307 isSystemUser=false method= org=278076025475235843 path=/oauth/v2/token requestMethod=POST trigger=accessToken user=278076535737417731
zitadel-1  | time="2024-07-30T09:24:40Z" level=info msg="lock and generate signing key pair" caller="/home/runner/work/zitadel/zitadel/internal/api/oidc/key.go:373"
zitadel-1  | time="2024-07-30T09:24:41Z" level=info msg="commit of read only transaction failed" caller="/home/runner/work/zitadel/zitadel/internal/database/database.go:48" error="sql: transaction has already been committed or rolled back"
zitadel-1  | time="2024-07-30T09:24:41Z" level=info msg="query failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/query.go:129" error="context canceled"
zitadel-1  | time=2024-07-30T09:24:41.369Z level=WARN msg="request error" oidc_error.parent="sql: no rows in result set" oidc_error.type=unauthorized_client status_code=400
```

### zitadel v2.58.0-debug (token and introspect)
```console
zitadel-1  | time="2024-07-30T09:28:45Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="http://localhost:8080" grpcStatus= httpStatus= instance=278076025475170307 isSystemUser=false method= org=278076025475235843 path=/oauth/v2/token requestMethod=POST trigger=accessToken user=278076535737417731
zitadel-1  | time="2024-07-30T09:28:45Z" level=info msg="query failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/query.go:129" error="context canceled"
zitadel-1  | time=2024-07-30T09:28:45.319Z level=WARN msg="request error" oidc_error.parent="sql: no rows in result set" oidc_error.type=unauthorized_client status_code=400
```

### zitadel v2.58.0-debug (token and authorize)
```console
zitadel-1  | time="2024-07-30T10:24:39Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="http://localhost:8080" grpcStatus= httpStatus= instance=278076025475170307 isSystemUser=false method= org=278076025475235843 path=/oauth/v2/token requestMethod=POST trigger=accessToken user=278076535737417731
zitadel-1  | time=2024-07-30T10:24:39.425Z level=WARN msg="request error" oidc_error.parent="ID=QUERY-wu6Ee Message=Errors.App.NotFound Parent=(sql: no rows in result set)" oidc_error.description=Errors.App.NotFound oidc_error.type=invalid_request status_code=400
```

### zitadel v2.58.0-debug (token and human)
```console
zitadel-1  | time="2024-07-30T10:32:12Z" level=info msg=activity caller="/home/runner/work/zitadel/zitadel/internal/activity/activity.go:105" domain="http://localhost:8080" grpcStatus= httpStatus= instance=278076025475170307 isSystemUser=false method= org=278076025475235843 path=/oauth/v2/token requestMethod=POST trigger=accessToken user=278076535737417731
zitadel-1  | time="2024-07-30T10:32:12Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:282" error="ID=APP-ASdgg Message=invalid token"
zitadel-1  | time="2024-07-30T10:32:12Z" level=warning msg="authz: verify access token" caller="/home/runner/work/zitadel/zitadel/internal/api/authz/context.go:112" error="ID=APP-Zxfako Message=invalid audience" org_domain= org_id=
db-1       | 2024-07-30 10:32:15.616 UTC [12446] ERROR:  could not obtain lock on row in relation "current_states"
db-1       | 2024-07-30 10:32:15.616 UTC [12446] STATEMENT:  SELECT
db-1       | 	    aggregate_id
db-1       | 	    , aggregate_type
db-1       | 	    , "sequence"
db-1       | 	    , event_date
db-1       | 	    , "position"
db-1       | 	    , filter_offset
db-1       | 	FROM 
db-1       | 	    projections.current_states
db-1       | 	WHERE
db-1       | 	    instance_id = $1
db-1       | 	    AND projection_name = $2
db-1       | 	FOR UPDATE NOWAIT;
```

### docker compose
```yaml
version: "3.8"

services:
  zitadel:
    restart: always
    networks:
      - zitadel
    image: ghcr.io/zitadel/zitadel:v2.58.0-debug
    command: start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled --init-projections=true
    environment:
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
      - ZITADEL_EXTERNALSECURE=false
      - PGUSER=postgres
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    restart: always
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zitadel
      - PGUSER=postgres
    networks:
      - zitadel
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready",
          "-d",
          "zitadel",
          "-U",
          "postgres"
        ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 5432:5432

networks:
  zitadel:
```

Any ideas?

Thank you!
Miran
