### DISCUSSION TITLE
Zitadel on self-hosted coolify

### DISCUSSION THREAD

**Discussion by danfarewell** [zitadel/zitadel#8370] [Q&A]
Hey everyone,

I'm currently exploring new technologies and thought to combine coolify.io with zitadel on a hobby project.
I installed coolify under coolify.domain.dev with pretty much the default setup (e.g. traefik as default proxy).

I've setup a postgres database with the coolify pg template (works!) and setup zitadel under the domain auth.domain.dev with a docker-compose.yml setup option that looks like this:

```yaml
version: '3.8'
services:
  zitadel:
    restart: always
    networks:
      - zitadel
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "5i1ptR3r7RU2nR5wIlpIP0NkjFrkgjAd" --tlsMode external'
    environment:
      - ZITADEL_DATABASE_POSTGRES_HOST=database_host_in_coolify
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=some_random_password
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=some_random_admin_password
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALDOMAIN=auth.domain.dev
      - ZITADEL_EXTERNALPORT=443
    ports:
      - '8081:8080'
```
This works so far that I can go to auth.domain.dev, login a user and setup stuff. There seems to be nothing in the beginning. I've setup a basic next.js app with next auth and loggin in works. However I'm having some issues that I would love to solve

1. Zitadel states that the domain for the organization is `zitadel.auth.domain.dev` which is not available on the server. What do I need to update in my setup either in docker-compose or coolify or wherever so this is supported?
2. If I keep Zitadel open too long it tells me that I need to login again however this always results in a oidc error (in json format) and I need to clear my cache before I can login again or I see Errors.OIDCSession.Token.Invalid (QUERY-IJL3H) error in the UI and can't do something else either.

Please help :-)
