### DISCUSSION TITLE
help~ about login first time

### DISCUSSION THREAD

**Discussion by jeromeleong** [zitadel/zitadel#8553] [Q&A]
<img width="721" alt="image" src="https://github.com/user-attachments/assets/0116b3b9-57ca-4cfe-b3ec-722684e64eba">

**zitadel-init-steps.yaml**
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  DefaultLanguage: 'zh'
  Org:
    Human:
      # use the loginname root@zitadel.localhost
      Username: 'root'
      Password: 'RootPassword1!'
```
I set this yaml and self-hosted zitadl, website like this - https://sso.xxxxxx.net
i try root@zitadel.localhost, it wrong
i try root@sso.xxxxxx.net, it wrong
i try root@xxxxxx.net, it wrong

who can help me😩😩😩
