### DISCUSSION TITLE
Stuck on "migration already started"

### DISCUSSION THREAD

**Discussion by djbe** [zitadel/zitadel#8583] [Q&A] [answered]
Trying to run a new Zitadel instance (stable), with a postgres DB. 

Have the following init containers:
- `zitadel init` without issues
- `zitadel setup cleanup` without issues, will mention if it cleans up a previous attempt at running setup
- `zitadel setup` always gets stuck on `03_default_instance`. Have tried letting it run, still stuck even after 12h.

Seems similar to https://github.com/zitadel/zitadel/discussions/6856, but the solution from there doesn't seem to help 😕 

<details>
<summary>Some extra info (config, env, …)</summary>

CMD parameters: `--config /zitadel-config.yaml`

Config:
```yaml
    Log:
      Level: info
    LogStore:
      Access:
        Stdout:
          Enabled: true
    ExternalPort: 443
    ExternalSecure: true
    Database:
      postgres:
        User:
          SSL:
            Mode: 'disable'
        Admin:
          SSL:
            Mode: 'disable'
    DefaultInstance:
      OIDCSettings:
        AccessTokenLifetime: 12h
        IdTokenLifetime: 12h
        RefreshTokenIdleExpiration: 720h  # 30 days
        RefreshTokenExpiration: 8640h  # 360 days
```

ENV variables:
```
ZITADEL_FIRSTINSTANCE_ORG_NAME
ZITADEL_EXTERNALDOMAIN
ZITADEL_MASTERKEY

ZITADEL_DATABASE_POSTGRES_HOST
ZITADEL_DATABASE_POSTGRES_PORT
ZITADEL_DATABASE_POSTGRES_DATABASE
ZITADEL_DATABASE_POSTGRES_USER_USERNAME
ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE
ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD

ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME
ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD
ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED
ZITADEL_FIRSTINSTANCE_ORG_HUMAN_FIRSTNAME
ZITADEL_FIRSTINSTANCE_ORG_HUMAN_LASTNAME
ZITADEL_FIRSTINSTANCE_ORG_HUMAN_EMAIL_ADDRESS
```
</details>
