### DISCUSSION TITLE
Support Yugabyte

### DISCUSSION THREAD

**Discussion by icelattefull** [zitadel/zitadel#8840] [Ideas]
For what I gather, zitadel supports both postgresql and cockroachdb. The latter recently changed their licensing and is not an open source project any more.

Bearing that in mind, I wonder if supporting YugabyteDB would be an option. I tried locally in docker-compose and it seems there's an incompatibility with the syntax somewhere

![image](https://github.com/user-attachments/assets/a5d39bde-e1a7-43d7-8512-ac48540f2724)

**Comment by hifabienne** [comment]
At the moment our recommendation is to use postresql, and we don't have plans to support some other databases at the moment, as each other db adds some more complexity and maintenance. 

@adlerhurst @muhlemmer might be able to give some more insights, opinions

**Reply by adlerhurst** [reply]
We were in contact some time ago with them and they are working on postgres compatibility: https://docs.yugabyte.com/preview/explore/ysql-language-features/postgresql-compatibility/

So it might get possible in the future without any code changes

**Comment by jbc-avk** [comment]
Same problem @icelattefull : SQL error during initialization when using Yugabyte DB as the backend

Versions : 
- Zitadel : patest stable
- YugabyteDB : 2.23.0.0

First installation steps are OK :
14_events_push 
01_tables 

But the installation stops at this step :
02_assets 

<img width="1300" alt="image" src="https://github.com/user-attachments/assets/eb0fa4f3-9905-4da8-87ca-21668094f3ee">

A quick review in YugabyteDB UI shows that the following user tables have been created successfully :

- unique_constraints
- encryption_keys
- events2
- locks
- current_sequences
- failed_events
- styling
- locks
- users
- user_sessions
- user_external_idsp
- tokens
- refresh_tokens
- org_project_mapping
- idp_providers
- idp_configs
- auth_requests
- locks

And several index tables are also available :
es_active_instances
es_wm
es_projection
user_user_agent_idx
unique_client_user_index
auth_code_idx


YugabyteDB provides interesting features in terms of HA, horizontal scalability, and PostgreSQL compatibility + it is open source : it could be a great replacement of CockroachDB with limited changes in SQL queries.

@adlerhurst looks like a SQL request called during the step 02_assets uses instructions not understood by YugabyteDB yet (see : https://docs.yugabyte.com/preview/explore/ysql-language-features/postgresql-compatibility/#unsupported-postgresql-features)

**Reply by fforootd** [reply]
Out of curiosity, is yugabyte not still pg version 11?

With Zitadel we require 15, if I remember correctly.

**Reply by jbc-avk** [reply]
This is my understanding too, and it is confirmed by the YugabyteDB Dev team in their blog -->  they have been working on pg15 compatibility for a few months already : 
https://www.yugabyte.com/blog/yugabytedb-moves-beyond-postgresql-11/
But not release date so far

Another interesting information for the Zitadel Dev team : Yugabyte seems more compatible with PG than cockroach (according to ... Yugabyte) : https://www.yugabyte.com/postgresql/compare-postgresql-compatibility/

<img width="587" alt="image" src="https://github.com/user-attachments/assets/dc6c176d-6019-48a2-abf7-f8b30482e944">

This may help make Zitadel compatible with YugebyteDB when their upgrade to pg15 is done ?

**Reply by jbc-avk** [reply]
In addition, the latest YugabyteDB builds seem to use pg15 as stated here : https://github.com/yugabyte/yugabyte-db/issues/9797
I'll try and share the result in a few days

**Reply by jbc-avk** [reply]
Tested with latest Yugabyte preview version (2.23.1.0-b220) : the problem is still there unfortunately
This is a clear show stopper for us, as we cannot run a Federated ID service in production without a highly available and scalable DB backend.

**Reply by adlerhurst** [reply]
thanks i need to dig into the problem, Zitadel sometimes uses different statements for crdb and psql which works around syntax and feature compatibility.

**Reply by muhlemmer** [reply]
@jbc-avk if the scalability and availability requirements cannot be met by a PostgreSQL HA, you might be interested in getting an enterprise contract. Under such contract we might[^1] be able to provide customized support for Yugabyte. For now it is not worth it for us to provide and maintain Yugabyte support purely for the community.

You can book a discovery call if you're interested: https://zitadel.com/discoverycall

[^1]: would need to be further investigated in the process.

**Reply by ddorian** [reply]
The new version using PG15 will fix this particular issue. 

For now, you can manually fix the migration and run the rest of them, to see if there's any other issue.

**Reply by jbc-avk** [reply]
Hey @ddorian 
That's great news ! are talking about the latest Yugabyte version or a fix in Zitadel code ?
Happy to help when the patch is available

**Reply by ddorian** [reply]
Talking about the next YugabyteDB version that will be based on PG15 and includes `Stored generated columns`.

It's already been tested in our slack channel with a build from master with this DDL from zitadel https://yugabyte-db.slack.com/archives/CJN8V5ZKJ/p1730744875527509?thread_ts=1730715072.153539&cid=CJN8V5ZKJ

![image](https://github.com/user-attachments/assets/5419216c-c7b9-4304-9bab-01cb383c21bd)

**Reply by jbc-avk** [reply]
@ddorian very clear, thanks for the details
will wait for the 2025 version of Yugabyte to launch our production ; meanwhile, we'll continue our Zitadel learning path using a PG15 DB as a backend

**Reply by adlerhurst** [reply]
these are great news thanks for sharing

**Reply by lknite** [reply]
@ddorian Could you tell me how you manually performed the migration steps.  That's where I'm getting stuck at the moment.

**Reply by ddorian** [reply]
It wasn't me in the screenshot. They ran it on a build from master which supports PostgreSQL 15. 

Where are you getting stuck exactly? (paste the command & output)

**Comment by lknite** [comment]
For those looking to implement yugabyte, I'm sure this will change ... this configures yugabyte w/ zitadel, though it might not work:
- copy the 'yugabyte-tls-client-cert' secret and create 'zitadel-yugabyte-tls-client-cert':
  - rename the keys so you have 'ca.crt' 'tls.crt' 'tls.key'
- configure the yugabyte helm chart using the latest image (because the stable does not support PG15, so ... unstable/test version it is):
  - ```yugabyte.Image.tag: 2.20.7.2-b1```
- configure the zitadel helm chart to use the secret we created above:
  - ```zitadel.dbSslAdminCrtSecret: zitadel-yugabyte-tls-client-cert```
- configure the zitadel helm chart configmapConfig section:
```
  zitadel:
    dbSslAdminCrtSecret: zitadel-yugabyte-tls-client-cert
    ...
    configmapConfig:
      ExternalSecure: false
      ExternalDomain: 127.0.0.1.sslip.io
      TLS:
        Enabled: true
      Database:
        postgres:
          Host: yb-tservers             # ZITADEL_DATABASE_POSTGRES_HOST
          Port: 5433                    # ZITADEL_DATABASE_POSTGRES_PORT
          Database: yugabyte            # ZITADEL_DATABASE_POSTGRES_DATABASE
          User:
            Username: yugabyte          # ZITADEL_DATABASE_POSTGRES_USER_USERNAME
            Password: yugabyte          # ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
            SSL:
              Mode: require             # ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE
          Admin:
            ExistingDatabase: yugabyte  # ZITADEL_DATABASE_POSTGRES_ADMIN_EXISTINGDATABASE
            Username: yugabyte          # ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
            Password: yugabyte          # ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
            SSL:
              Mode: require             # ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE
```
