### DISCUSSION TITLE
getting started with zitadel terraform provider

### DISCUSSION THREAD

**Discussion by chrisovergaauw** [zitadel/zitadel#8908] [Q&A] [answered]
Hi,

Both Terraform and Zitadel are new to me and using the examples from the docs leads to errors.
I would like to end up setting up OIDC with terraform.

docker-compose.yaml
```
version: "3.8"

services:
  zitadel:
    restart: "always"
    networks:
      - "zitadel"
    image: "ghcr.io/zitadel/zitadel:latest"
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - "ZITADEL_DATABASE_POSTGRES_HOST=db"
      - "ZITADEL_DATABASE_POSTGRES_PORT=5432"
      - "ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel"
      - "ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable"
      - "ZITADEL_EXTERNALSECURE=false"
      - "ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/machinekey/zitadel-admin-sa.json"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=zitadel-admin-sa"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Admin"
      - "ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1"
      #- "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=admin"
      #- "ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=Password1!"
    depends_on:
      db:
        condition: "service_healthy"
    ports:
      - "8080:8080"
    volumes:
      - ./machinekey:/machinekey

  db:
    restart: "always"
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - "zitadel"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    ports:
      - "3432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  zitadel:

volumes:
  pgdata:
  ```
  
  main.tf
  ```
  terraform {
  required_providers {
    zitadel = {
      source  = "zitadel/zitadel"
      version = "1.2.0"
    }
  }
}

provider "zitadel" {
  domain           = "localhost"
  insecure         = "true"
  port             = "8080"
  jwt_profile_file = "machinekey/zitadel-admin-sa.json"
}

resource "zitadel_org" "default" {
  name = "terraform-test"
}
```

commands used:
```
docker compose up -d
terraform init
terraform apply
zitadel_org.default: Refreshing state... [id=293488433140072451]
╷
│ Error: error while getting org by id 293488433140072451: rpc error: code = NotFound desc = Organisation not found (QUERY-iTTGJ)
│
│   with zitadel_org.default,
│   on main.tf line 17, in resource "zitadel_org" "default":
│   17: resource "zitadel_org" "default" {
│
╵
```

Can anyone help me get past this stage? I have googled a ton, looked at examples and checked all the relevant issues here.
