### DISCUSSION TITLE
Access Zitadel API with ztadel-go

### DISCUSSION THREAD

**Discussion by lesomnus** [zitadel/zitadel#9210] [Q&A]
Im trying to create a user in Zitadel using zitadel-go.
I issued a key under Management-API in the zitadel web UI and downloaded a JSON file.
Following is my go code to create a client:
```go
import (
	...
	"github.com/zitadel/zitadel-go/v3/pkg/client"
	"github.com/zitadel/zitadel-go/v3/pkg/zitadel"
	...
)

...
zitadel_conf := zitadel.New(c.Zitadel.Domain, zitadel_opts...)
zitadel_auth := client.DefaultServiceUserAuthentication(c.Zitadel.Key, client.ScopeZitadelAPI())
zitadel_client, _ := client.New(ctx, zitadel_conf, client.WithAuth(zitadel_auth))

_, err = zitadel_client.ManagementService().GetMyOrg(ctx, nil)
if err != nil {
	return err
}
```
Above code returns:
```
rpc error: code = Unauthenticated desc = transport: per-RPC creds failed due to error: ErrorType=server_error Description=Errors.Internal
```
and I can see the following log in the Zitadel server:
```
time=2025-01-20T09:46:54.439Z level=ERROR msg="request error" oidc_error.parent="ID=OIDC-AhX2u Message=Errors.Internal Parent=(invalid signature (error fetching keys: ID=QUERY-Tha6f Message=Errors.AuthNKey.NotFound Parent=(sql: no rows in result set)))" oidc_error.description=Errors.Internal oidc_error.type=server_error status_code=500
```

This is my Zitadel deploy:
```
  zitadel:
    image: ghcr.io/zitadel/zitadel:v2.67.4
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    restart: unless-stopped
    environment:
      # https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME: odin
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD: odin
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALDOMAIN: zitadel
      ZITADEL_EXTERNALSECURE: false
      ZITADEL_DEFAULTINSTANCE_PASSWORDCOMPLEXITYPOLICY_MINLENGTH: 1
      ZITADEL_DEFAULTINSTANCE_PASSWORDCOMPLEXITYPOLICY_HASLOWERCASE: false
      ZITADEL_DEFAULTINSTANCE_PASSWORDCOMPLEXITYPOLICY_HASUPPERCASE: false
      ZITADEL_DEFAULTINSTANCE_PASSWORDCOMPLEXITYPOLICY_HASNUMBER: false
      ZITADEL_DEFAULTINSTANCE_PASSWORDCOMPLEXITYPOLICY_HASSYMBOL: false
```

Is this mean that the request is unauthenticated? or is it internal error due to the bug of Zitadel?
Did I feed a wrong key?
