### DISCUSSION TITLE
New installation: [unknown] Failed to fetch

### DISCUSSION THREAD

**Discussion by ivancarlosti** [zitadel/zitadel#9521] [Q&A]
Hi team,

I am looking to use ZITADEL and I raised a docker compose, my server has a nginx as reverse proxy configured to http://127.0.0.1:8080.
When I start the docker compose, it runs fine, I can change the password, but when it redirects me to /ui/console/users/me, it shows an error :/ Please, what am I missing?

![image](https://github.com/user-attachments/assets/26ec6b9a-1de3-4413-b676-2e5800769ea6)

```
services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "<mymasterkey>" --tlsMode disabled'
    environment:
      ZITADEL_EXTERNALDOMAIN: <mysubdomain.example.com>
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: false
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  db:
    restart: 'always'
    image: postgres:16-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - 'zitadel'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

networks:
  zitadel:
```

Thanks a lot
