### DISCUSSION TITLE
only blank page with docker-compose version

### DISCUSSION THREAD

**Discussion by changchichung** [zitadel/zitadel#9662] [Q&A] [answered]
my docker-compose.yml
```
services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: false
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '3013:8080'

  db:
    restart: 'always'
    image: postgres:16-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - 'zitadel'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

networks:
  zitadel:
```

I basically change nothing , only the mapping port from 8080 to 3013
after the containers up , I only see a blank page at http://192.168.100.2:8013  , 192.168.100.2 is my docker host ip
and docker logs show
```
zitadel-1  |  Warning: you're using plain http without TLS. Be aware this is
zitadel-1  |  not a secure setup and should only be used for test systems.
zitadel-1  |  Visit: https://zitadel.com/docs/self-hosting/manage/tls_modes
zitadel-1  |
zitadel-1  |  ===============================================================
zitadel-1  |
zitadel-1  | time="2025-03-28T02:23:43Z" level=info msg="auth request cache disabled" caller="/home/runner/work/zitadel/zitadel/internal/auth_request/repository/cache/cache.go:31" error="must provide a positive size"
zitadel-1  | time="2025-03-28T02:23:43Z" level=info msg="auth request cache disabled" caller="/home/runner/work/zitadel/zitadel/internal/auth_request/repository/cache/cache.go:36" error="must provide a positive size"
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oauth/v2/authorize
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oauth/v2/device_authorization
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oauth/v2/token
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oauth/v2/introspect
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oidc/v1/userinfo
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oauth/v2/revoke
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oidc/v1/end_session
zitadel-1  | time=2025-03-28T02:23:43.717Z level=INFO msg="registered route" endpoint=/oauth/v2/keys
zitadel-1  | time="2025-03-28T02:23:43Z" level=info msg="server is listening on [::]:8080" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:605"
zitadel-1  | time="2025-03-28T02:23:50Z" level=error msg="unable to set instance" caller="/home/runner/work/zitadel/zitadel/internal/api/http/middleware/instance_interceptor.go:50" error="unable to get instance by host: instanceHost 192.168.100.2:3013, publicHost : ID=QUERY-1kIjX Message=Errors.IAM.NotFound" externalDomain=localhost origin="http://192.168.100.2:3013"
zitadel-1  | time="2025-03-28T02:28:19Z" level=error msg="unable to set instance" caller="/home/runner/work/zitadel/zitadel/internal/api/http/middleware/instance_interceptor.go:50" error="unable to get instance by host: instanceHost 192.168.100.2:3013, publicHost : ID=QUERY-1kIjX Message=Errors.IAM.NotFound" externalDomain=localhost origin="http://192.168.100.2:3013"
```

any suggestions ??
