### DISCUSSION TITLE
What does it means when I receive Errors.User.Code.Invalid ?

### DISCUSSION THREAD

**Discussion by soubinan** [zitadel/zitadel#9717] [General]
Hello,

I am trying to integrate another app to Zitadel (self-hosted) for SSO.
I created the app with everything needed, I already have 6 apps workings properly.

But for this application there is an issue I can't explain. It turns out the app is not able to integrate Zitadel correctly.
And when checking Zitadel logs, I see the error below:
```
level=WARN msg="request error" oidc_error.parent="ID=OIDC-ahLi2 Message=Errors.User.Code.Invalid Parent=(ID=CRYPT-23kH1 Message=cipher text block too short)" oidc_error.description=Errors.User.Code.Invalid oidc_error.type=invalid_request status_code=400
```

I have no clue what this error means.
I am pretty sure the issue is not about client ID/secret, since the error messages are different when they are the root cause.

By checking the [code source](https://github.com/zitadel/zitadel/blob/c815ff2a35cbd0f8c4303311e778e11999b53e07/internal/api/oidc/token_code.go#L32), it seems to be about a code Zitadel should use from an AccessTokenRequest (according to what I understood). But it is not something I configure, so it is just a confusing message for me.

Below the infos I use on the app side (a pretty basic config):
```yaml
AUTHENTICATION_TYPE: OIDC
ZITADEL_LOGIN_CONFIG:
  CLIENT_ID: "314045226417218573"
  CLIENT_SECRET: "**********"
  OIDC_SERVER: "https://********/"
  SERVICE_NAME: Zitadel
  LOGIN_SCOPES: ["openid", "email", "profile"]
```

If someone has an idea, I would be thankful for your help.
