### ISSUE TITLE
[Bug]: Not possible to create a new instance with "OIDC Token Exchange" feature enabled

### ISSUE THREAD

**Issue by Drowze** [zitadel/zitadel#10031]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

3.2.3

### Database

PostgreSQL

### Database Version

postgres:16-alpine

### Describe the problem caused by this bug

It doesn't seem to be possible to create a new Zitadel instance with "OIDC Token Exchange" feature enabled - so it seems that we must manually enable that feature (via API or manually in the UI).

Since we have this setting in the `defaults.yaml`, I assume that should be possible
```yaml
DefaultInstance:
  Features:
    # TokenExchange: false # ZITADEL_DEFAULTINSTANCE_FEATURES_TOKENEXCHANGE
```

What I've tried:
- via environment variable: `ZITADEL_DEFAULTINSTANCE_FEATURES_TOKENEXCHANGE=true`
- via --steps with:
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  Features:
    TokenExchange: true
```

### To reproduce

using this docker-compose:
```yaml
services:
  zitadel:
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:v3.2.3'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled --steps /zitadel-initial-config.yml'
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable

      ZITADEL_DEFAULTINSTANCE_FEATURES_TOKENEXCHANGE: 'true'
    depends_on:
      db:
        condition: 'service_healthy'
    ports:
      - '8080:8080'
    volumes:
      - "${PWD}/zitadel-initial-config.yml:/zitadel-initial-config.yml:ro"

  db:
    image: postgres:16-alpine
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - 'zitadel'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "zitadel", "-U", "postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

networks:
  zitadel:
```

And this `zitadel-initial-config.yml`:
```yaml
FirstInstance:
  Features:
    TokenExchange: true
```

And then verify that `OIDC Token Exchange` feature is not enabled.
