### ISSUE TITLE
otel logs exemplar labels have too many runes

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#10047]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v3.2.3

### Database

PostgreSQL

### Database Version

17

### Describe the problem caused by this bug

The following log line starts appearing:

`exemplar labels have 159 runes, exceeding the limit of 128`

It looks like this is caused by the [hard limit of otel metrics](https://github.com/prometheus/client_golang/blob/7c924b7c82b5a61e1e7e2be165bff781700b5365/prometheus/value.go#L240)

### To reproduce

i wasn't able to reproduce it locally

### Expected behavior

These logs should not occur. 

### Additional Context

Reported by a customer

**Comment by hifabienne** [comment]
@eliobischof as this issue is assigned to you, what does this mean?
Are you working on this and we can put it into in progress, or is this something to investigate?
Can you please update the state?

**Comment by eliobischof** [comment]
> @eliobischof as this issue is assigned to you, what does this mean?
> Are you working on this and we can put it into in progress, or is this something to investigate?
> Can you please update the state?

Yes, this needs investigation

**Comment by karlsabo** [comment]
@eliobischof , we're also seeing this issue and it's preventing us from being able to upgrade to Zitadel 2.71.X.

**Comment by zhirschtritt** [comment]
This might be a clue: https://github.com/open-telemetry/opentelemetry-go/pull/5778 - the go.opentelemetry.io/otel/exporters/prometheus exporter between v0.50.0 and v0.57.0 enabled exporting exemplars by default. I don't know what metrics in particular are too big, but it looks like we can still turn exemplars off with `OTEL_METRICS_EXEMPLAR_FILTER=always_off`

**Comment by adlerhurst** [comment]
A customer reported that the issue on v4.1.0 still exists

**Comment by mridang** [comment]
@adlerhurst I've managed to reproduce it too.

**Comment by Drowze** [comment]
We're also seeing this issue on v3.4.2 today, when we just started testing OTEL tracing.

E.g. an except from logs:
```
{"caller":"/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472","iteration":0,"level":"debug","msg":"trigger iteration","projection":"projections.login_names3","time":"2025-10-27T16:12:34Z"}
{"caller":"/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472","iteration":0,"level":"debug","msg":"trigger iteration","projection":"projections.personal_access_tokens3","time":"2025-10-27T16:12:35Z"}
{"caller":"/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472","iteration":0,"level":"debug","msg":"trigger iteration","projection":"projections.instance_members4","time":"2025-10-27T16:12:36Z"}
{"caller":"/home/runner/work/zitadel/zitadel/internal/eventstore/handler/v2/handler.go:472","iteration":0,"level":"debug","msg":"trigger iteration","projection":"projections.lockout_policies3","time":"2025-10-27T16:12:37Z"}
2025/10/27 16:12:39 exemplar labels have 163 runes, exceeding the limit of 128
2025/10/27 16:12:39 exemplar labels have 163 runes, exceeding the limit of 128
2025/10/27 16:12:39 exemplar labels have 163 runes, exceeding the limit of 128
```

**Comment by muhlemmer** [comment]
@mridang if you were able to reproduce, can you please add the steps to reproduce here? I'm wondering if it's something the library limits or perhaps something returned by the collector used? We don't see these logs in Google cloud, as far as I know, so it might be a collector specific limitation.

Please share your complete setup, I'm not a hero with otel collectors and /or grafana.

**Comment by rgdev** [comment]
Occurs on 4.11.0 as well. All I did was upgrade the instance from 4.9.1 (helm chart 9.16.0) to v4.11.0 (helm chart 9.23.0) with no changes in config or helm values.

**Comment by mridang** [comment]
@rgdev if you could share your values.yaml that you're using for the chart, that would help the others debug it.

**Comment by linwalth** [comment]
We have the same issue in v4.11.1

redacted valuesfile for you to debug with:

```
          replicaCount: 3
          image:
            tag: "v4.11.1"
          zitadel:
            configmapConfig:
              Log:
                Level: info
                Formatter:
                  Format: json
              LogStore:
                Access:
                  Stdout:
                    Enabled: true
                Execution:
                  Stdout:
                    Enabled: true
              ExternalSecure: true
              ExternalPort: 443
              ExternalDomain: REDACTED
              TLS:
                Enabled: false  # disabled because we terminate SSL at the Ingress Controller
              FirstInstance:
                Skip: false
                DefaultLanguage: en
                InstanceName: REDACTED
                Org:
                  Name: REDACTED
                  Human:
                    UserName: REDACTED
                    Email:
                      Address: REDACTED
                      Verified: true
                    PasswordChangeRequired: true
              DefaultInstance:
                OIDCSettings:
                  AccessTokenLifetime: 12h
                  IdTokenLifetime: 12h
                  RefreshTokenIdleExpiration: 720h # 30d
                  RefreshTokenExpiration: 2160h # 90d
                DomainPolicy:
                  UserLoginMustBeDomain: false
                  ValidateOrgDomains: true
                  SMTPSenderAddressMatchesInstanceDomain: true
                LoginPolicy:
                  AllowRegister: false
                  ForceMFA: false
                SMTPConfiguration:
                  SMTP:
                    Host: REDACTED
                    User: REDACTED
                  TLS: true
                  From: REDACTED
                  FromName: REDACTED
                Restrictions:
                  DisallowPublicOrgRegistration: true
              SystemDefaults:
                Multifactors:
                  OTP:
                    Issuer: REDACTED
            debug:
              enabled: false
```

**Comment by Crazy-Geeks** [comment]
+1 for 4.13:

```shell
time=2026-03-23T16:12:05.631Z level=INFO msg="registered route" endpoint=/oauth/v2/keys
time=2026-03-23T16:12:05.674Z level=INFO msg="server is listening" stream=runtime version=v4.13.0 address=[::]:8080
time=2026-03-23T16:23:14.786Z level=INFO msg="exemplar labels have 206 runes, exceeding the limit of 128"
time=2026-03-23T16:23:14.786Z level=INFO msg="exemplar labels have 206 runes, exceeding the limit of 128"
time=2026-03-23T16:23:14.786Z level=INFO msg="exemplar labels have 206 runes, exceeding the limit of 128"
....
time=2026-03-23T16:38:53.167Z level=INFO msg="exemplar labels have 203 runes, exceeding the limit of 128"
time=2026-03-23T16:38:53.167Z level=INFO msg="exemplar labels have 203 runes, exceeding the limit of 128"
....
time=2026-03-23T17:02:50.558Z level=INFO msg="traces export: exporter export timeout: rpc error: code = Unavailable desc = name resolver error: produced zero addresses"
```

I mentioned it when I added otel service. No error vlaues in otel's logs.
With otel service disabled - no such logs in main container. 

Compose file:
```yaml
x-zitadel-db-common: &zitadel-db-comm
    ZITADEL_DATABASE_POSTGRES_HOST: postgres
    ZITADEL_DATABASE_POSTGRES_DATABASE: ${DATABASE_NAME}
    ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${DATABASE_USERNAME}
    ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${DATABASE_PASSWORD}
x-zitadel-db-admin: &zitadel-db-admin
    ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${DATABASE_ADMIN_USERNAME}
    ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
x-zitadel-db-string: &zitadel-db-string
    ZITADEL_DATABASE_POSTGRES_DSN: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?sslmode=disable

networks:
    zitadel:
        external: true
    monitoring:
        external: true
services:
    zitadel-init:
        image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION}
        restart: "no"
        user: "0"
        command: init
        environment:
            <<: [*zitadel-db-comm, *zitadel-db-admin]
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - zitadel
    zitadel-setup:
        image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION}
        restart: "no"
        user: "0"
        command: >
            setup
            --config /config/config.yaml
            --masterkeyFile /secrets/masterkey
            --steps /config/init-steps.yaml
        environment:
            <<: *zitadel-db-string
            ZITADEL_EXTERNALDOMAIN: ${ZITADEL_DOMAIN}
        volumes:
            - zitadel-bootstrap:/zitadel/bootstrap:rw
            - ./config/config.yaml:/config/config.yaml:ro
            - ./config/init-steps.yaml:/config/init-steps.yaml:ro
            - ./secrets/masterkey:/secrets/masterkey:ro
        depends_on:
            postgres:
               condition: service_healthy
            zitadel-init:
               condition: service_completed_successfully
        networks:
            - zitadel
    zitadel-api:
        image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION}
        restart: unless-stopped
        user: "0"
        command: >
            start
            --config /config/config.yaml
            --masterkeyFile /secrets/masterkey
            --tlsMode external
        env_file:
            .env.common
        environment:
            ZITADEL_DATABASE_POSTGRES_DSN: postgresql://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@postgres:5432/${DATABASE_NAME}?sslmode=disable
            ZITADEL_CACHES_CONNECTORS_REDIS_URL: redis://redis:6379/0
            ZITADEL_EXTERNALDOMAIN: ${ZITADEL_DOMAIN}
            
            ZITADEL_INSTRUMENTATION_TRACE_EXPORTER_TYPE: ${INSTRUMENTATION_TRACE_EXPORTER_TYPE}
            ZITADEL_INSTRUMENTATION_TRACE_EXPORTER_ENDPOINT: otel-collector:4317
            ZITADEL_INSTRUMENTATION_TRACE_EXPORTER_INSECURE: true
            ZITADEL_INSTRUMENTATION_SERVICENAME: ${INSTRUMENTATION_SERVICENAME_API}
        healthcheck:
            test:
                - CMD
                - /app/zitadel
                - ready
            interval: 10s
            timeout: 30s
            retries: 12
            start_period: 20s
        volumes:
            - zitadel-bootstrap:/zitadel/bootstrap:rw
            - ./config/config.yaml:/config/config.yaml:ro
            - ./secrets/masterkey:/secrets/masterkey:ro
        networks:
            zitadel:
                ipv4_address: 172.20.0.10
        depends_on:
            postgres:
                condition: service_healthy
            zitadel-init:
                condition: service_completed_successfully
            zitadel-setup:
                condition: service_completed_successfully

    zitadel-login:
        image: ghcr.io/zitadel/zitadel-login:${ZITADEL_VERSION}
        restart: unless-stopped
        user: "0"
        environment:
            ZITADEL_API_URL: http://zitadel-api:8080
            NEXT_PUBLIC_BASE_PATH: /ui/v2/login
            ZITADEL_SERVICE_USER_TOKEN_FILE: /zitadel/bootstrap/login-client.pat
            CUSTOM_REQUEST_HEADERS: Host:${ZITADEL_DOMAIN},X-Forwarded-Proto:https

            OTEL_SERVICE_NAME: ${INSTRUMENTATION_SERVICENAME_LOGIN}
            OTEL_EXPORTER_OTLP_ENDPOINT: otel-collector:4317
            OTEL_EXPORTER_OTLP_PROTOCOL: ${INSTRUMENTATION_TRACE_EXPORTER_TYPE}
        healthcheck:
            test:
                - CMD
                - /bin/sh
                - -c
                - node /app/healthcheck.mjs http://localhost:3000/ui/v2/login/healthy
            interval: 10s
            timeout: 30s
            retries: 12
            start_period: 20s
        volumes:
            - zitadel-bootstrap:/zitadel/bootstrap:ro
        networks:
            zitadel:
                ipv4_address: 172.20.0.20
        depends_on:
            zitadel-api:
                condition: service_healthy
    postgres:
        image: ${POSTGRES_IMAGE}
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
            POSTGRES_USER: ${DATABASE_ADMIN_USERNAME}
        healthcheck:
            test:
                - CMD-SHELL
                - pg_isready -d ${DATABASE_NAME} -U ${DATABASE_ADMIN_USERNAME}
            interval: 10s
            timeout: 30s
            retries: 10
            start_period: 20s
        volumes:
            - postgres-data:/var/lib/postgresql/data:rw
        networks:
            - zitadel
    redis:
        image: ${REDIS_IMAGE}
        restart: unless-stopped
        command: redis-server --save "" --appendonly no
        networks:
            zitadel:
                ipv4_address: 172.20.0.30
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5
    zitadel-otel:
        image: ${OTEL_COLLECTOR_IMAGE}
        restart: unless-stopped
        command:
            - --config=/etc/otelcol/config.yaml
        volumes:
            - ./config/otel.yaml:/etc/otelcol/config.yaml:ro
        networks:
            zitadel:
                ipv4_address: 172.20.0.40
            monitoring: {}
volumes:
    postgres-data:
        name: zitadel_postgres-data
    zitadel-bootstrap:
        name: zitadel_zitadel-bootstrap
```

.env file:
```dotenv
ZITADEL_DOMAIN=<REDACTED>

ZITADEL_VERSION=v4.13.0
POSTGRES_IMAGE=postgres:17.2-alpine
REDIS_IMAGE=redis:7.4.2-alpine
OTEL_COLLECTOR_IMAGE=otel/opentelemetry-collector-contrib:0.114.0

DATABASE_NAME=zitadel
DATABASE_USERNAME=zitadel
DATABASE_PASSWORD=<REDACTED>
DATABASE_ADMIN_USERNAME=postgres_zitadel
DATABASE_ADMIN_PASSWORD=<REDACTED>

INSTRUMENTATION_SERVICENAME_API=zitadel-api
INSTRUMENTATION_SERVICENAME_LOGIN=zitadel-login
INSTRUMENTATION_TRACE_EXPORTER_TYPE=grpc
# and .env.common too:
ZITADEL_TLS_ENABLED=false
ZITADEL_EXTERNALSECURE=true
ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI=/ui/v2/login/
```

config.yaml:
```yaml
Port: 8080 # ZITADEL_PORT
ExternalPort: 443 # ZITADEL_EXTERNALPORT
ExternalSecure: true # ZITADEL_EXTERNALSECURE
TLS:
  Enabled: false # ZITADEL_TLS_ENABLED
# And some more, not related to monitoring
```

otel.yaml (otel cfg)
```yaml
receivers:
  otlp:
    protocols:
      grpc: {}
      http: {}
  prometheus:
    config:
      scrape_configs:
        - job_name: zitadel-api
          scrape_interval: 15s
          static_configs:
#            - targets: ['zitadel-api:8080']
            - targets: ['172.20.0.10:8080']
          metrics_path: /debug/metrics

processors:
  batch: {}

exporters:
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8088"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [prometheus]
```
