### ISSUE TITLE
[Bug]: HTTP is used to retrieve OpenID discovery document with `ExternalSecure` set to `true`

### ISSUE THREAD

**Issue by xadhatter** [zitadel/zitadel#12065]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.62.1

### Database

CockroachDB

### Database Version

v24.2.0

### Describe the problem caused by this bug

After installation I am unable to access the UI console. An error occurs because the webapp uses a plain http connection to retrieve the openid configuration, even with `ExternalSecure` set to `true`.

```
Wait!
Inserting something here could give attackers access to your zitadel account.
If you don't know exactly what you're doing, close the window and stay on the safe side
If you know exactly what you are doing, you should work for us

Refused to connect to 'http://my.domain/.well-known/openid-configuration' because it violates the following Content Security Policy directive: "connect-src 'self' my.domain".

error loading discovery document 
T {headers: k, status: 0, statusText: 'Unknown Error', url: 'http://my.domain/.well-known/openid-configuration', ok: false, …}
```

### To reproduce

1. Install Zitadel using Helm (see values.yaml, below)
2. Use Traefik as reverse proxy
3. Use `ExternalDomain` and `ExternalSecure`
4. Try to access console

### Screenshots

Connection is using HTTPS. All other calls used HTTPS, except for `http://my.domain/.well-known/openid-configuration`

Browser console:

![image](https://github.com/user-attachments/assets/ebd6692c-10af-4e45-b2e3-dcd1e8f237fd)

Browser network:

![image](https://github.com/user-attachments/assets/2cd56607-c0c9-45b1-ad8f-ba90dbfd4be0)

### Expected behavior

HTTPS is used to retrieve openid configuration and UI console loads.

### Operating System

AWS EKS

### Relevant Configuration

Helm chart values:

```yaml
zitadel:
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: my.domain
    ExternalPort: 443

    TLS:
      Enabled: false
```

Traefik IngressRoute:

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`my.domain`)
      services:
        - name: zitadel
          port: 8080
          scheme: h2c
          passHostHeader: true
```

**Comment by zetxx** [comment]
hey there, any decision on this ? same problem here

**Comment by ChristianJacobsen** [comment]
If you are - like I was - stuck getting this to work with Traefik, then enabling

```yaml
ports:
  web:
    forwardedHeaders:
      insecure: true
    proxyProtocol:
      insecure: true
```

in the Helm chart worked like a charm, in lieu of an actual solution(?).

I'm running Traefik behind a Cloudflare Tunnel.
