### ISSUE TITLE
Support for more databases

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#3598]
Based on a discussion on [hackernews] (https://news.ycombinator.com/item?id=31266460)it might make sense for us to support multiple storages.
Even though CockroachDB will be the primary one

**Acceptance criteria**
- [ ] Support Postgresql
- [ ] Discuss what more we can support

**Comment by fforootd** [comment]
I like to hear your thoughts on this @adlerhurst

**Comment by adlerhurst** [comment]
IMO before we begin we should discuss how we will test other databases. They might need different indexes. We can assume that we have to create the same indexes and index types as for crdb. 

To not break the configuration files structure for v2 we have to add a database type, this must be done before the release.

**Comment by adlerhurst** [comment]
Added task for database type: #3600

**Comment by fforootd** [comment]
I did some research around the offerings from the hyperscalers. It turns out that >80% of them has some form of pure Postgresql offering. Based on this I think we should allow and test for plain Postgresql as well besides cockroachDB.

What I currently would ignore are their proprietary offerings e.g CosmosDB, Amazon RDS, Google Spanner. Even though some of them provide Postgresql as dialect

**Comment by Sytten** [comment]
We are interested in using zitadel and being able to use postgres is the largest hurdle for adoption on our side.

**Comment by fforootd** [comment]
@Sytten 

We are currently valuating to support plain postgresql besides cockroachDB. This because multiple customers are interested in using the managed postgresql offerings.

I think we should be able to given an update to this in the next 2-4 weeks.

**Comment by Sytten** [comment]
Nice! Let me know if you need beta testers, willing to give you good feedback since I want to implement our integration with v2 as soon as possible 😀

**Comment by adlerhurst** [comment]
Support for mysql was requested here: https://github.com/zitadel/zitadel/issues/3600#issuecomment-1161246978

**Comment by KaKi87** [comment]
@hifabienne Considering you set priority to low, I'm guessing this [this statement](https://github.com/zitadel/zitadel/issues/3600#issuecomment-1168324557) from two months ago is no longer applicable ?
> Probably we will have a look at this in 1-2 months.

Thanks

**Comment by fforootd** [comment]
At the moment we are doing the finishing touches for Postgres which should be ready really soon to be released.

After this we will consider what additional databases might make sense.

**Comment by KaKi87** [comment]
Oh, very nice, thanks !

**Comment by fforootd** [comment]
What DB are you interested in?

**Comment by KaKi87** [comment]
Postgres is fine, I'll try it as soon as it's released.
Although MySQL is my primary database.

**Comment by adlerhurst** [comment]
hi @Sytten and @KaKi87 

We have just released postgresql support of ZITADEL. If you want to check it out you can find the release notes here: https://github.com/zitadel/zitadel/releases/tag/v2.3.0

If you have any feedback we are happy to answer :-)

**Comment by KaKi87** [comment]
Since PostgreSQL support of Zitadel is limited to the latest major version, I cannot use it, therefore I look forward to MySQL support. Thanks

**Comment by fforootd** [comment]
> Since PostgreSQL support of Zitadel is limited to the latest major version, I cannot use it, therefore I look forward to MySQL support. Thanks

I think it will be a while until we support mysql. Can you shine some light why it is a problem to use Postgresql 14?

**Comment by adlerhurst** [comment]
> > Since PostgreSQL support of Zitadel is limited to the latest major version, I cannot use it, therefore I look forward to MySQL support. Thanks
> 
> I think it will be a while until we support mysql. Can you shine some light why it is a problem to use Postgresql 14?

question was answered here: https://discord.com/channels/927474939156643850/1014503578439794688/1015302346449883176

**Comment by helmut72** [comment]
> If you have any feedback we are happy to answer :-)

I'm not the ones, but give feedback :-) Also wanted to switch to Postgres after seeing Cockroach RAM usage. In Keycloak the app is the memory hog, in Zitadel it's Cockroach.

This works:

```
ZITADEL_DATABASE_COCKROACH_HOST=cockroach
```

... and this doesn't work:

```
ZITADEL_DATABASE_POSTGRES_HOST=postgres
ZITADEL_DATABASE_POSTGRES_HOST=5432
ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=password
```

postgres is the container name of Postgres.

**Comment by adlerhurst** [comment]
hi @helmut72 

I think there is some configuration missing. If you use postgres you have to set all the fields for the connection. The defaults of zitadel are only configured for cockroachdb:

here is an example for disabled ssl on postgres:
```
ZITADEL_DATABASE_POSTGRES_HOST=postgres
ZITADEL_DATABASE_POSTGRES_PORT=5432
ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel

ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=password
ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
```

if you init the database also with zitadel you have to set the admin user additionaly:
```
ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=root
ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=root
ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
```

**Comment by helmut72** [comment]
@adlerhurst 
Thanks, have added SSL Mode and tried with disable, disabled, false and 0. But no luck. It still wants to connect to a Cockroach db. Which is unset:

```
level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:47" error="dial tcp 127.0.0.1:26257: connect: connection refused"
```

> We are currently working on ram usage of crdb.

I hope Postgres doesn't take this much RAM too... ;) Nevertheless I prefer Postgres for my home setup.

**Comment by helmut72** [comment]
Update. Now it works. First I've pulled latest `:stable` release. My image was from end of last week. Still got an error:

```
level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:65" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=postgres port=5432 user= application_name=zitadel sslmode= sslrootcert=`: failed to configure TLS (sslmode is invalid))"
```

Then I've also set the Postgres admin variables:

```
ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=zitadel
ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=zitadel
ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
```

But even then it doesn't worked:

```
level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:65" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(failed to connect to `host=postgres user=db_user database=`: server error (FATAL: database \"db_user\" does not exist (SQLSTATE 3D000)))"
```


Look at the database name. Same as Postgres user variable. But I have set a different db name. My examples here are other names for security reason.

Then I have tried with `zitadel` everywhere. Adminuser, Username, DB-Name and Password. Then it worked. It looks like the ENV parser need a fix with ZITADEL_DATABASE_POSTGRES_DATABASE option?

All at all it would be cool if the ENV parser use default values if any option is unset. I have this experience from other projects.

> I hope Postgres doesn't take this much RAM too... ;) 

Can answer my own question. Postgres use 38MB. For now. That's great. :)

**Comment by hifabienne** [comment]
@adlerhurst @fforootd Should we close this issue for now? We have added Postgres and I think for now we do not have the intention to add any other? Or  how do you see it?

**Comment by KaKi87** [comment]
MySQL ?

**Comment by adlerhurst** [comment]
I would leave it open that we can track the state and put it at the end of the backlog.

For now we focus to improve the currently implemented sql dialects (cockroach, postgresql). Additional dialects add an additional layer of complexity for each change and maintenance overhead. To add more dialects there must be made ground work to simplify the addition of dialects.

**Comment by musicformellons** [comment]
I could use [yugabytedb](https://www.yugabyte.com/) support. Based on postgresql, so should be 'relatively easy'.

**Comment by KaKi87** [comment]
Why not.

Although, I think MySQL is the most urgent one, as it's the most-used database.

**Comment by musicformellons** [comment]
That's right:
Black = mysql
Orange = postgres
Yellow = cockroachdb
Green = yugabytedb

<img width="498" alt="Screenshot 2023-02-01 at 15 20 17" src="https://user-images.githubusercontent.com/10334123/216069200-fe618990-367f-4730-aba1-d7cab08944ec.png">

**Comment by Wulfheart** [comment]
> I would leave it open for tracking the state and put it at the end of the backlog.
> 
>  For now we focus to improve the currently implemented sql dialects (cockroach, postgresql). Additional dialects add an additional layer of complexity for each change and maintenance overhead. To add more dialects there must be made ground work to simplify the addition of dialects.

So maybe use an ORM like sqlboiler? But that is only a shot as I am not familiar with the code. Just interested on your opinion on this.

**Comment by cr1xu5** [comment]
SQLite support would be great for compact setups on the edge, but also for testing locally.

Together with solutions like [LiteFS](https://fly.io/docs/litefs/) SQLite is a great alternative for the "regular" databases.

**Comment by gandaldf** [comment]
I don't know if anyone need this, but I was able to run Zitadel with Postgres using this docker-compose.yaml:
```
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:stable'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_EXTERNALSECURE=false'
      - 'ZITADEL_DATABASE_POSTGRES_HOST=pgdb'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=zitadeldb'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=zitadeladmin'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=zitadeladmin'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadeluser'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadeluser'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
    depends_on:
      pgdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  pgdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'postgres:16beta1'
    environment:
      - POSTGRES_USER=zitadeladmin
      - POSTGRES_PASSWORD=zitadeladmin
      - POSTGRES_DB=zitadeldb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '5432:5432'

networks:
  zitadel:
```
