### ISSUE TITLE
There is no SMTP configuration and one cannot be added

### ISSUE THREAD

**Issue by domdomegg** [zitadel/zitadel#3715]
**Describe the bug**

When running with Docker, Zitadel does not create a default instance SMTP configuration. Once running however, it cannot be edited because it tries to get the existing SMTP configuration and fails.

This results in errors such as:
- SMTP configuration not found
- Errors.NotificationProvider.NotFound
- Cannot read properties of undefined (reading 'translate')

**To Reproduce**

1. Start a new instance following the docker instructions: https://docs.zitadel.com/docs/guides/installation
2. Go to the SMTP settings
3. Try to add SMTP details (e.g. use mailtrap.io)

**Expected behavior**

User able to set SMTP configuration

**Additional context**

This blocks testing out creating new users as they need to verify their emails, which cannot be done without SMTP support as far as I can see.

**Comment by fforootd** [comment]
Hi @domdomegg 

Thanks for reporting this. I think you are trying to use the v2-alpha, right?

Could you proivde us with your zitadel config and version you are using?

**Comment by adlerhurst** [comment]
Hi @domdomegg 

We are investigating the problem in the console. A workaround is to reinitiate ZITADEL and overwrite the default config as described [here](https://docs.zitadel.com/docs/guides/installation#configure-by-configuration-files) by setting the `SMTPConfiguration` field, see the example below.

I've tested the following configuration and was able to send email using mailtrap:

```yaml
DefaultInstance:
  DomainPolicy:
    SMTPSenderAddressMatchesInstanceDomain: false #important: set to false because of host name matching
  SMTPConfiguration:
    SMTP:
      Host: smtp.mailtrap.io:2525
      User: <YOUR USER>
      Password: <PASSWORD OF THE USER>
    TLS: true
    From: noreply@your-host.tld
    FromName: ZITADEL
```

The missing fields in the `defaults.yaml` will be added in #3736 .

**Comment by domdomegg** [comment]
Thanks both for looking into this so quickly!

@fforootd I used version `v2.0.0-v2-alpha.3`, and the only config I had was just to point at a local cockroach database. I've now also tested it with `v2.0.0-v2-alpha.14` and `v2.0.0-v2-alpha.15` and get the same problem unfortunately.

@adlerhurst, after your change in #3736 (released in `v2.0.0-v2-alpha.14`), unfortunately I still seem to get a similar error. I have attached a sample docker compose file that running from scratch appears to still not let me set SMTP configuration:

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3.8'

services:
  zitadel:
    restart: always
    networks:
      - zitadel
    image: ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.15-amd64
    command: admin start-from-init --masterkey "MasterkeyNeedsToHave32Characters"
    environment:
      - ZITADEL_DATABASE_HOST=db
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN=localhost
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/debug"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    restart: always
    networks:
      - zitadel
    image: cockroachdb/cockroach:v21.2.5
    command: start-single-node --insecure --listen-addr=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 9090:8080
      - 26257:26257

networks:
  zitadel:
```

</details>

To reproduce:
1. Copy this file to your computer, and name it `docker-compose.yml`
2. `cd` into the directory containing it
3. Run `docker compose up`, or `docker-compose up` depending on your version of docker
4. Go to `http://localhost:8080/ui/console`, then enter username: `zitadel-admin@zitadel.localhost`, password: `Password1!`
5. Once into the main admin UI (you might need to change the default password), click the 'Instance' button at the top right
6. Go to the 'Settings' tab, and the 'Notification providers and SMTP' subpage
7. Try to set the mailtrap SMTP configuration (or any SMTP configuration here). Although the page displays a success toast message, looking at the network tab it shows the `UpdateSMTPConfig` request has a response indicating an error of `SMTP configuration not found (INST-Svq1a)`. When refreshing the page, it's clear this change has not been persisted.

I did find the proposed suggestion of overriding the SMTP configuration in config before starting Zitadel worked, so thank you for this workaround:

<details>
<summary>docker-compose.yml</summary>

```yaml
version: '3.8'

services:
  zitadel:
    restart: always
    networks:
      - zitadel
    image: ghcr.io/zitadel/zitadel:v2.0.0-v2-alpha.15-amd64
    command: admin start-from-init --masterkey "MasterkeyNeedsToHave32Characters"
    environment:
      - ZITADEL_DATABASE_HOST=db
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN=localhost
      - ZITADEL_DEFAULTINSTANCE_DOMAINPOLICY_SMTPSENDERADDRESSMATCHESINSTANCEDOMAIN=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=smtp.mailtrap.io:2525
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER=mailtrap_username_here
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD=mailtrap_password_here
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=true
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=sender@zitadel.localhost
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=Zitadel
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/debug"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 40s
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    restart: always
    networks:
      - zitadel
    image: cockroachdb/cockroach:v21.2.5
    command: start-single-node --insecure --listen-addr=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
    ports:
      - 9090:8080
      - 26257:26257

networks:
  zitadel:
```

</details>

(I think the bug of not being able to configure it, without overriding it in config still stands though)
