### ISSUE TITLE
Cannot access Zitadel over network (or any non-localhost host)

### ISSUE THREAD

**Issue by aliadnani** [zitadel/zitadel#3766]
**Describe the bug**

It seems I cannot access the Zitadel over the network - local network and internet both do not work

**To Reproduce**

I encountered this issue when trying to self host it on a VPS, but here is how you can recreate locally:

1. Start the Zitadel application by `cd`-ing into `deploy/compose` and running `docker compose up` - then wait for application to stabilize
2. Visiting `localhost:8080/ui/console` should work as normal
3. Fetch your machine's local IP address using ` hostname -I | awk '{print $1}'`
4. Visiting `<MACHINE_LOCAL_IP>/ui/console` results in a blank screen with errors printed to console
5. Seems that even `http://127.0.0.1:8080/ui/console/` results in the same behaviour

**Expected behavior**

Visiting `<MACHINE_LOCAL_IP>/ui/console` should work as normal

**Screenshots**
Blank screen with console output 

![image](https://user-images.githubusercontent.com/39276986/171679227-fd42b312-e29e-4410-86aa-93cac8ec4273.png)

Failed network request to `.../environment.json`
![image](https://user-images.githubusercontent.com/39276986/171679395-d5c9c405-a668-415e-838b-c2e2f4773a67.png)
![image](https://user-images.githubusercontent.com/39276986/171679437-3caf827d-6725-4455-8d7d-6587ce8c7a0e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 running on Windows 11 WSL2
 - Browser: Microsoft Edge 
 - Version: 100

**Additional context**

I saw a few `host` related config settings such as `ExternalDomain` but was not sure what they do 😅

**Comment by fforootd** [comment]
Hi @aliadnani 

If you are using the default compose file then you need to use `localhost` in the URL instead of the IP address.
This is because zitadel filters based on the hostname.

This value can be edited when overloading [this env](https://github.com/zitadel/zitadel/blob/v2-alpha/deploy/compose/docker-compose.yml#L13)

**Comment by RyanTT** [comment]
I am currently experiencing this issue too as a first time user of Zitadel.

I'm trying to reach my container under (not literally) `http://mydomain.de:8080/ui/console`.

First I attempted to set `ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN` to `ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN=mydomain.de`, however this still results in the errors shown in the original post. 

Looking at the default configuration file, I also tried `ZITADEL_EXTERNALDOMAIN=mydomain.de`, but with no success.

`ZITADEL_EXTERNALSECURE=false` is also set since I am accessing it with HTTP.

**Comment by fforootd** [comment]
Hi @RyanTT 

Hm I think I start to see the problem 😁 our homebrew and linux example work but in the docker-compose there seem to be one env missing. Can you please try again while setting the env like this:

```
    environment:
      - ZITADEL_DATABASE_HOST=db
      - ZITADEL_EXTERNALSECURE=false
      - ZITADEL_EXTERNALDOMAIN=localhost
      - ZITADEL_DEFAULTINSTANCE_CUSTOMDOMAIN=localhost
```

@eliobischof I think the compose needs to be updated.

@livio-a @hifabienne we defenitly need to document the config values 😁

**Comment by eliobischof** [comment]
@livio-a @adlerhurst should the instance domain values match with config values here?

![image](https://user-images.githubusercontent.com/12727842/171961378-6e7ebbc4-dd66-4a16-882b-68ea58213bd1.png)

**Comment by RyanTT** [comment]
@fforootd Thank you for the quick reply!

Unfortunately, I don't seem to be able to get it working that way either, though I suspect this is probably a mistake on my part now:

I changed my docker-compose.yml file's `command` line to reflect the passing of a custom config.yaml file for Zitadel like this:

```yml
    command: admin start-from-init --masterkey "redacted" --config /config.yaml
```

then mounted a config file via:

```yml
    volumes:
      - ./config.yaml:/config.yaml
```

As described in your answer, I put the following content inside the config.yaml:

```yml
# In both test scenarios, I put this here
ExternalDomain: mydomain.de
ExternalSecure: false

# Added this additionally in the second test as with just the above lines + the "S3DefaultInstance" block + the "Database"
# block it would not work
DefaultInstance:
  InstanceName: testing
  CustomDomain: mydomain.de

# This block was present in the first test to make my setup as accurate to your working example as possible
S3DefaultInstance:
  InstanceName: testing
  CustomDomain: mydomain.de

Database:
  Host: db
```

Unfortunately this still resulted in the same errors. I verified that this config.yaml actually gets loaded by setting the Database.Host value to a non-existing domain, which correctly resulted in Zitadel being unable to reach the DB, so it should definitely be reading the values from this config file.

I also noticed that the "CustomDomain" field on the DefaultInstance key is not present in the defaults.yaml file on the repo, I think adding it as a commented line would help new users be aware of this setting

**Comment by fforootd** [comment]
@RyanTT Sorry I forgot to mention this. The steps file needs to be declared explicitly:

`command: admin start-from-init --masterkey "redacted" --config /config.yaml - --steps /config.yaml`

I is fine to use the same yaml file here, we do the same with our test system.s

**Comment by RyanTT** [comment]
@fforootd Thanks again for the quick responses and help :)

I added the `--steps` parameter, making the final line `command: admin start-from-init --masterkey "redacted" --config /config.yaml --steps /config.yaml`.

This made the environment.json file load correctly when accessing the `http://zitadel.mydomain.de:8080/ui/console/`, aswell as get rid of both "Cannot read properties of undefined" errors, sadly the `ERROR Error: Uncaught (in promise): issuer  must use HTTPS (with TLS), or config value for property 'requireHttps' must be set to 'false' and allow HTTP (without TLS).` error remains.

My current entire config.yaml is

```yaml
ExternalDomain: zitadel.mydomain.de
ExternalSecure: false

S3DefaultInstance:
  InstanceName: test
  CustomDomain: zitadel.mydomain.de

Database:
  Host: db
```
