### ISSUE TITLE
Integration with Dex is not working

### ISSUE THREAD

**Issue by fforootd** [zitadel/zitadel#4090]
I started a local zitadel in linux with the guide located [here](https://docs.zitadel.com/docs/guides/deploy/linux).

After creating the Dex as Instance level IdP I get properly redirected to the Dex and callback of ZITADEL.

However as soon as is I want to "register" I receive the error "Invalid userdata"

![image](https://user-images.githubusercontent.com/9879976/182240718-2769290a-383e-4026-8618-e739b66af7bf.png)

## ZITADEL Config

![image](https://user-images.githubusercontent.com/9879976/182240800-84699dc1-034b-43cc-97e8-b113025835cc.png)

## Dex Tokens

 ID Token:

eyJhbGciOiJSUzI1NiIsImtpZCI6ImJkNmRjYTI3M2JiOGE0YmRhNDNmMzFlNzdkZmM0OGQ0YWVmNTMyNjYifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvZGV4Iiwic3ViIjoiQ2cwd0xUTTROUzB5T0RBNE9TMHdFZ1J0YjJOciIsImF1ZCI6ImV4YW1wbGUtYXBwIiwiZXhwIjoxNjU5NDcxNzgzLCJpYXQiOjE2NTkzODUzODMsImF0X2hhc2giOiJkSFBxZWFadFQwSU1Va3hEM2JQdG53IiwiY19oYXNoIjoiQ3lDbmstSms3X2l6Mi1WcG00eGR5USIsImVtYWlsIjoia2lsZ29yZUBraWxnb3JlLnRyb3V0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJLaWxnb3JlIFRyb3V0In0.koCtxTg0AYqVxZpbjwWxN0CS2xF8vUkdAnCmlZoXYtBfifWov696plIKkLgJahoeuNdbswDmXmKaqiWm_n3BZmwtmFpfDfpk99k1RhW1NtPamWgU0GZt4ZEhHY_TLFTzkc_Y0kCJsi0BU70k2yGsIviG-WOA0D4KV1-s5RTEPJhbb6eH2Z4MiP6hJCvrwHC-eO8wUOENFowB_3k7sBrWBdocDkPpNlci7VQb5ln0ghbvUuUnJrwSkBDxEVCqrhfyPlP6zKU83GgVh8zIB7znl6xmbJr9MtwS2gqdsI62xuqBb064CgYNXkYa5s7wo8QDgco1co5DHB6Exxa3M_Qokw

Access Token:

eyJhbGciOiJSUzI1NiIsImtpZCI6ImJkNmRjYTI3M2JiOGE0YmRhNDNmMzFlNzdkZmM0OGQ0YWVmNTMyNjYifQ.eyJpc3MiOiJodHRwOi8vMTI3LjAuMC4xOjU1NTYvZGV4Iiwic3ViIjoiQ2cwd0xUTTROUzB5T0RBNE9TMHdFZ1J0YjJOciIsImF1ZCI6ImV4YW1wbGUtYXBwIiwiZXhwIjoxNjU5NDcxNzgzLCJpYXQiOjE2NTkzODUzODMsImF0X2hhc2giOiJXc0phQ0Jyc1NyS2N4SlpMNFlMSHBRIiwiZW1haWwiOiJraWxnb3JlQGtpbGdvcmUudHJvdXQiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IktpbGdvcmUgVHJvdXQifQ.CvQhEwKVkePzMJzktSCiExA6d5QDDHsU-U3YB3XBEZgY3Ixr6S7rtZ60KrmwVZduVrskUhkS6iEPn8LjCE0YV5ghpHHIcJQhPAHtjbzXY9tf_1s4M-MBZuE3nhA7OagQW_oiSaJDqCwRzmgGYWd0MxcdR-ODXVBW1mFV0FWPK2cxrmbztWmUghyYJAhXJlGgvm9eK1kpoDmSDyPwxTKU-SX4WvRsbx5Vw--0xPwUSQ3orfl8ocek-NmoYUAvgxOlFtngezyo49dwVFMeFfXHI2-fCSjrEnLGiKc-ndCVF6fyGwI4_h4dP0MTGI6sDUcbB8ILw-ZoQ5knyvhQf9Sxng

## Dex config 

```
issuer: http://127.0.0.1:5556/dex
storage:
  type: sqlite3
  config:
    file: examples/dex.db
web:
  http: 127.0.0.1:5556

connectors:
- type: mockCallback
  id: mock
  name: Example
  
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  - 'http://localhost:8080/ui/login/login/externalidp/callback'  
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
```
