### ISSUE TITLE
WebAuthN not working while ZITADEL is behind an NGINX

### ISSUE THREAD

**Issue by lordwelch** [zitadel/zitadel#4307]
**Describe the bug**
Cannot register a U2F token.

**To Reproduce**
1. Follow instructions from docker guide https://docs.zitadel.com/docs/guides/deploy/compose
2. Attempt to register any U2F token (tested: macOS fingerprint, OnlyKey Duo, YubiKey 5C NFC FW: 5.2.7, Android fingerprint)

**Expected behavior**
Successfully register a U2F token

**Screenshots**
<img width="454" alt="Screen Shot 2022-09-04 at 12 39 54 PM" src="https://user-images.githubusercontent.com/7547075/188330771-b2dcd463-d70a-49d7-ac60-dc001874d2ea.png">

**Desktop (please complete the following information):**
 - OS: macOS 12.5.1
 - Browser: Chrome, Safari, FireFox, Arc (based on chrome)
 - Version: 105.0.5195.102 (Official Build) (arm64), 103.0.2 (64-bit), Version 0.65.3 (34418) Chromium Engine Version 104.0.5112.102

**Desktop (please complete the following information):**
 - OS: Fedora 36
 - Browser: Chrome, FireFox
 - Version: 103.0.5060.114 (Official Build) Fedora Project (64-bit), 104.0.1 (64-bit)

**Smartphone (please complete the following information):**
 - Device: OnePlus 6T
 - OS: Android 11, OxygenOS version 11.1.1.1
 - Browser: Chrome, FireFox
 - Version: 104.0.5112.97, 104.1.0

**Smartphone (please complete the following information):**
 - Device: Google Pixel 6 Pro
 - OS: Android 13
 - Browser: Chrome
 - Version: 105.0.5195.68

**Additional context**
Possibly related to #2910 #4082

**Comment by adlerhurst** [comment]
Hi @lordwelch we shipped a [fix](https://github.com/zitadel/zitadel/pull/4290) lately but it is not yet available in the `stable`-tag. The bug should be fixed using `zitadel:latest`-image instead of `zitadel:stable`.

```yaml
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.1.3'
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'

networks:
  zitadel:
```
