### ISSUE TITLE
HTTP proxy settings for outgoing connections

### ISSUE THREAD

**Issue by livio-a** [zitadel/zitadel#4316]
ZITADEL must be able to use an HTTP proxy for outgoing connections (e.g. calling token endpoint in current IdP Federation).

To start off, we should have a general http client and support the following settings:
- in the config file:
```yaml
HTTPProxy:
  HTTP: http://user:password@proxy:8080
  HTTPS:  https://user:password@proxy:8443
  NoProxy:
    - *.local
    - some-domain.com
```

- which leads to the following environment variables:
```env
ZITADEL_HTTPPROXY_HTTP=http://user:password@proxy:8080
ZITADEL_HTTPPROXY_HTTPS=https://user:password@proxy:8443
ZITADEL_HTTPPROXY_NOPROXY=*.local,some-domain.com
```
