### ISSUE TITLE
footerText not filled on new Instance

### ISSUE THREAD

**Issue by pcdummy** [zitadel/zitadel#4324]
**Describe the bug**
footerText is not filled in all Templates, this doesn't allow me to send E-Mails, as well that it took me ages to find that bug in the console, it made me pull my hair ;P

**Zitadel**
- ghcr.io/zitadel/zitadel:v2.2.0
- ghcr.io/zitadel/zitadel:v2.3.3 <-- Just tested as well.

**To Reproduce**

1.) Installed Zitadel with the helm chart, i used the follwing values.yaml
  ```yaml
    affinity: {}
  chownImage:
    pullPolicy: IfNotPresent
    repository: alpine
    tag: '3.11'
  cockroachdb:
    enabled: false
    single-node: true
    statefulset:
      replicas: 1
  fullnameOverride: ''
  image:
    pullPolicy: IfNotPresent
    repository: ghcr.io/zitadel/zitadel
    tag: 'v2.3.3'
  imagePullSecrets: []
  ingress:
    annotations: 
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: 'true'
      ingress.kubernetes.io/protocol: h2c
      traefik.ingress.kubernetes.io/router.tls: "true"
    enabled: true
    hosts:
      - host: auth.example.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - auth.example.com
        secretName: auth-jochum-dev-tls
  metrics:
    enabled: false
    serviceMonitor:
      enabled: false
      honorLabels: false
      honorTimestamps: true
  nameOverride: ''
  nodeSelector: {}
  podAnnotations: {}
  podSecurityContext:
    runAsNonRoot: true
    runAsUser: 1000
  replicaCount: 1
  resources: {}
  securityContext: {}
  service:
    port: 8080
    protocol: http2
    type: ClusterIP
    annotations:
      traefik.ingress.kubernetes.io/service.passhostheader: "true"
      traefik.ingress.kubernetes.io/service.serversscheme: h2c
  serviceAccount:
    annotations: {}
    create: true
    name: ''
  tolerations: []
  zitadel:
    configmapConfig:
      Log:
        Level: 'trace'
      ExternalSecure: true
      ExternalDomain: auth.example.com
      ExternalPort: 443
      Database:
        cockroach:
          Host: "crdb-public.crdb.svc.cluster.local"
          User:
            Username: root
            SSL:
              Mode: "verify-full"
              RootCert: '/.secrets/ca.crt'
              Cert: '/.secrets/tls.crt'
              Key: '/.secrets/tls.key'

          Admin:
            Username: root
            SSL:
              Mode: "verify-full"
              RootCert: '/.secrets/ca.crt'
              Cert: '/.secrets/tls.crt'
              Key: '/.secrets/tls.key'
      Machine:
        Identification:
          Hostname:
            Enabled: true
          Webhook:
            Enabled: false
      TLS:
        Enabled: false

      FirstInstance:
        Org:
          Name: 'Main'
          Human:
            # use the loginname root@main.auth.example.com
            Username: 'root'
            Password: 'RootPassword1!'

    dbSslClientCrtSecret: 'crdb-root'
    dbSslRootCrt: ''
    dbSslRootCrtSecret: 'crdb-root'
    configSecretName: 'zitadel-config-secret'
    masterkey: '32CharsHere'
  ```

**Expected behavior**
footerText be filled after the Installation and be able to send E-Mails without filling them first.

**Screenshots**

```bash
time="2022-09-03T23:50:19Z" level=warning msg="missing translation" args="map[ChangeDate:2022-09-03 23:50:19.809166 +0000 UTC Code:3KQEXI CreationDate:2022-09-03 23:50:19.809166 +0000 UTC DisplayName:René Jochum FirstName:René LastEmail:rene@example.com LastName:Jochum LastPhone: LoginNames:[rene@jochum.auth.example.com] NickName:jochum PreferredLoginName:rene@jochum.auth.example.com UserName:rene VerifiedEmail: VerifiedPhone:]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/i18n.go:206" error="message \"InitCode.Footer\" not found in language \"de\"" id=InitCode.Footer
```

**Desktop (please complete the following information):**
 - OS: Debian Testing
 - Browser: Firefox
 - Version: Latest from Flatpak 104.0.1

**Additional context**
After filling footerText in all Templates I was able to send E-Mails, but filling the E-Mail Server configuration wasn't straight forward (port in the mailserver name as well as having to set the password each time, no clear output that it didn't work).

In my yaml above I use the root user+cert instead the "zitadel" user, I haven't got it running otherwise for now.
