### ISSUE TITLE
Installation with Postgres, login works, but then Unknown Content-type received

### ISSUE THREAD

**Issue by SBejga** [zitadel/zitadel#4455]
Hello,

I am evaluating Zitadel as an IdP for our product. And we want also have a look at it, running in our own infrastructure to test and analyze a bit.

**Describe the bug**
We have a kubernetes Cluster and a Postgres Database. And I got a running stack of Zitadel. 

I am able to login with created user and password (zitadel-admin) of FirstInstance Org.
But after Login I get the following error in Frontend: `Unknown Content-type received.`.

In the network tab of Chrome, I see that the frontend, with login works, but then POST calls against resources like `/zitadel.auth.v1.AuthService/`are failing with 404.

(I redacted the real domain to id.example.org, where example.org is set via $.Values.dnsDomain)

using zitadel helm chart 3.2.0 with values: 
```
        zitadel:
          configmapConfig:
            Log:
              Level: debug

            ExternalSecure: true
            ExternalDomain: id.{{ $.Values.dnsDomain }}
            ExternalPort: 443

            TLS:
              Enabled: false

            FirstInstance:
              Org:
                Name: 'ORG'

          configSecretName: postgres-credentials

        replicaCount: 1

        ingress:
          enabled: true
          className: nginx
          annotations: 
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
          - host: id.{{ $.Values.dnsDomain }}
            paths:
              - path: /
                pathType: Prefix
          tls:
          - secretName: id.{{ $.Values.dnsDomain }}
            hosts:
            - id.{{ $.Values.dnsDomain }}

        image:
          repository: ghcr.io/zitadel/zitadel
          pullPolicy: IfNotPresent
          tag: "v2.6.0"

        cockroachdb:
          enabled: false
          fullnameOverride: crdb
          tls:
            enabled: false
```

and working postgres credentials and config in a secret.

Logs of the pod: 

```

time="2022-09-26T13:24:49Z" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:61"
time="2022-09-26T13:24:49Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
time="2022-09-26T13:24:49Z" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:61"
time="2022-09-26T13:24:49Z" level=info msg="verify migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-09-26T13:24:49Z" level=info msg="starting migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-09-26T13:24:49Z" level=info msg="verify migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-09-26T13:24:49Z" level=info msg="starting migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"

[...]

time="2022-09-26T13:24:52Z" level=debug msg="skipping next check" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/init.go:206" execute=0 projection=projections.keys3
time="2022-09-26T13:24:52Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:63" lockerID=180695134290084452 workers=1
time="2022-09-26T13:24:52Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:63" lockerID=180695134290149988 workers=1
time="2022-09-26T13:24:52Z" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go:44" locker=180695134290149988--0 logID=LOCKE-lOgbg view=adminapi.styling
time="2022-09-26T13:24:52Z" level=debug msg="load canceled" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:138" error="ID=MODEL-pF3DR Message=no filters set" logID=SPOOL-OT8di view=adminapi.styling worker=180695134290149988--0
time="2022-09-26T13:24:52Z" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go:44" locker=180695134290084452--0 logID=LOCKE-lOgbg view=auth.user_external_idps
time="2022-09-26T13:24:52Z" level=debug msg="load canceled" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:138" error="ID=MODEL-pF3DR Message=no filters set" logID=SPOOL-OT8di view=auth.user_external_idps worker=180695134290084452--0

[...]

time="2022-09-26T13:24:53Z" level=info msg="server is listening on [::]:8080" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:255"

time="2022-09-26T13:26:43Z" level=warning msg="asset in login could not be served" caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/resources_handler.go:35" error="download failed: ID=DATAB-pCP8P Message=Errors.Assets.Object.NotFound Parent=(sql: no rows in result set)" file="policy/label/css/variables.css?v=2022-09-26T13:24:50Z" org=180695128787157604
time="2022-09-26T13:26:45Z" level=debug msg="statement dropped" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/handler_stmt.go:219" currentSequence="&{180695128787157604 113}" statement="&{user 113 112 180695128787157604 <nil>}"
time="2022-09-26T13:26:45Z" level=warning msg="unable to process all events from subscription" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:171" error="<nil>" projection=projections.login_names
time="2022-09-26T13:26:45Z" level=debug msg="statement dropped" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/crdb/handler_stmt.go:219" currentSequence="&{180695128787157604 113}" statement="&{user 113 112 180695128787157604 <nil>}"
time="2022-09-26T13:26:45Z" level=warning msg="unable to process all events from subscription" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:171" error="<nil>" projection=projections.users3
```

**To Reproduce**
1. Fresh postgres database
2. restarted zitadel deployment/pods
3. accessing id.example.org
4. login with zitadel-admin@org.id.example.org works

5. failing requests with 404 and frontend notification "Unknown Content-type received."

**Expected behavior**

**Screenshots**
see a screenshot of chrome network tab
![CleanShot 2022-09-26 at 15 37 08](https://user-images.githubusercontent.com/67571/192291995-12179d7a-22d6-4257-b932-907090d85d08.png)
1f.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version: 105.0.5195.125

**Comment by fforootd** [comment]
I am somewhat sure that you need to configure you ingress to use ZITADEL as grpc backend.

A typical [nginx conf ](https://docs.zitadel.com/docs/guides/manage/self-hosted/proxy#tls-mode-external)looks somewhat like this

```
worker_processes  1;
events {
    worker_connections  1024;
}

http {
    server {
        listen 443;

        ssl_certificate     ssl/certificate.pem;
        ssl_certificate_key ssl/key.pem;
 
        location / {
            grpc_pass grpc://localhost:8080;
            grpc_set_header Host $host;
        }
    }
}
```

**Comment by fforootd** [comment]
I think the nginx ingress needs the following:

```
annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      grpc_set_header Host $host;
    ```

**Comment by SBejga** [comment]
@fforootd Yes! Those annotations was missing. Thanks a lot. 

You may should add this somewhere in the kubernetes guide. This may depend on the specific ingress controller. But I would guess the nginx controller is frequently used.

With those annotation, I can login and use the console as expected. We will continue testing in detail, tomorrow.

**Comment by surangar** [comment]
I was tried with below AWS load balancer ingress controller and it's giving me "HTTP ERROR 464".
`apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol-version: GRPC
    alb.ingress.kubernetes.io/success-codes: "0"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-xxx,subnet-yyy
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:xxx:certificate/yyy
    alb.ingress.kubernetes.io/group.name: xxx
  name: zitadel-ingress-grpc
  namespace: zitadel
spec:
  rules:
  - host: staging-zitadel.xxx.com
    http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /
        pathType: Prefix
      - backend:
          service:
            name: zitadel-grpc
            port:
              number: 8080
        path: /
        pathType: Prefix`

**Comment by fforootd** [comment]
@surangar 

I am not sure how to configure ALB correctly, but ZITADEL awaits h2c as connection.

The error you describe in this case be "The request protocol is an HTTP/1.1, while the target group protocol version is a gRPC or HTTP/2"

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-troubleshooting.html#http-464-issues

**Comment by chathuwick** [comment]
@surangar 

Update the backend-protocol-version to HTTP2 instead of GRPC. Your Ingress definition should be similar to the following:

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig":
      { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-xxx,subnet-yyy
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-southeast-2:xxx:certificate/yyy
    alb.ingress.kubernetes.io/group.name: xxx
  name: zitadel-ingress-grpc
  namespace: zitadel
spec:
  rules:
  - host: staging-zitadel.xxx.com
    http:
      paths:
      - backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation
        path: /
        pathType: Prefix
      - backend:
          service:
            name: zitadel-grpc
            port:
              number: 8080
        path: /
        pathType: Prefix
```
