### ISSUE TITLE
Prune SQL Statements

### ISSUE THREAD

**Issue by eliobischof** [zitadel/zitadel#4469]
**Describe the bug**

We should avoid SQL injection like situations. For example, if you use a tick in the database password config, ZITADEL fails to initialize the database. This is, because the SQL query created in *cmd/initialise/verify_user.go* for creating a database user contains a dynamic variable that is placed between ticks:

![image](https://user-images.githubusercontent.com/12727842/192800999-998d110c-3467-4b42-a35b-88c70fcc5d6b.png)

**To Reproduce**

Apply a helm chart v3.2.0 containing the following values 

```yaml
zitadel:
  # ...
  secretConfig:
    Database:
      cockroach:
        User:
          Password: "i-don't-care"
# ...
```

See above

**Expected behavior**
Hyphens in the password should be respected and ZITADEL shouldn't fail.

**Screenshots**

![image](https://user-images.githubusercontent.com/12727842/192799494-8dce4e23-0a51-47f9-ab94-e41df1259710.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
