### ISSUE TITLE
Unable to start zitadel using example

### ISSUE THREAD

**Issue by Dima-Kal** [zitadel/zitadel#4610]
**Describe the bug**
When container is started the following issue appears and the container is constantly restarting:

```
time="2022-10-25T15:10:45Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2022-10-25T15:10:45Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel_user
time="2022-10-25T15:10:45Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2022-10-25T15:10:45Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel_user
time="2022-10-25T15:10:45Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
time="2022-10-25T15:10:47Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
time="2022-10-25T15:10:47Z" level=info msg="verify migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:47Z" level=info msg="verify migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:47Z" level=info msg="verify migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:47Z" level=info msg="starting migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-25T15:10:47Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:45" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
time="2022-10-25T15:10:47Z" level=fatal msg="unable to migrate step 3" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:98" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
time="2022-10-25T15:10:54Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2022-10-25T15:10:54Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel_user
time="2022-10-25T15:10:54Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2022-10-25T15:10:54Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel_user
time="2022-10-25T15:10:54Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
time="2022-10-25T15:10:56Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:57"
time="2022-10-25T15:10:57Z" level=info msg="verify migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:57Z" level=info msg="verify migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:57Z" level=info msg="verify migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:33"
time="2022-10-25T15:10:57Z" level=info msg="starting migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43"
time="2022-10-25T15:10:57Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:45" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
time="2022-10-25T15:10:57Z" level=fatal msg="unable to migrate step 3" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:98" error="ID=COMMA-VoaRj Message=Errors.User.PasswordComplexityPolicy.HasUpper"
```

**To Reproduce**
Used the example here:
https://docs.zitadel.com/docs/guides/deploy/loadbalancing-example

**Comment by hifabienne** [comment]
Hi @Dima-Kal 
The error message tells that the PasswordComplexityPolicy defines that a password should contain an upper letter.
Do you have an upper letter in the password of your first admin user?

**Comment by Dima-Kal** [comment]
> Hi @Dima-Kal The error message tells that the PasswordComplexityPolicy defines that a password should contain an upper letter. Do you have an upper letter in the password of your first admin user?

yes, tried it with "Secret_DB_User_Password"
and then changed it to:
```
    User:
      # If the user doesn't exist already, it is created
      Username: 'zitadel_user'
      Password: 'f#AfFd7y783ho'
    Admin:
      Username: 'root'
      Password: '!ws#4dD3qss'
```

**Comment by hifabienne** [comment]
Hei @Dima-Kal 
This message is not about your DB-User.
It is about your first user in your ZITADEL instance that has admin rights.
It should be in the FirstInstance

**Comment by Dima-Kal** [comment]
> Hei @Dima-Kal This message is not about your DB-User. It is about your first user in your ZITADEL instance that has admin rights. It should be in the FirstInstance

Ok that indeed solved it, I had another issue:

```
time="2022-10-26T06:58:00Z" level=fatal msg="unable to initialize ZITADEL" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:68" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=zitadel-db port=26257 user=zitadel_user dbname=zitadel application_name=zitadel sslmode=verify-full dbname=zitadel password=xxxxx sslrootcert=/crdb-certs/ca.crt sslcert=/crdb-certs/client.zitadel_user.crt sslkey=/crdb-certs/client.zitadel_user.key`: failed to configure TLS (unable to read cert: open /crdb-certs/client.zitadel_user.crt: no such file or directory))"
```

"solved" it by removing 'Cert' and 'Key' from this configuration
Database:
  cockroach:
    Host: 'zitadel-db'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
       # Cert: "/crdb-certs/client.zitadel_user.crt"
       # Key: "/crdb-certs/client.zitadel_user.key"

**Comment by hifabienne** [comment]
I will close the issue since we have found the problem

**Comment by Dima-Kal** [comment]
> I will close the issue since we have found the problem

Should i open a new issue regarding this?

```
Ok that indeed solved it, I had another issue:

time="2022-10-26T06:58:00Z" level=fatal msg="unable to initialize ZITADEL" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:68" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=zitadel-db port=26257 user=zitadel_user dbname=zitadel application_name=zitadel sslmode=verify-full dbname=zitadel password=xxxxx sslrootcert=/crdb-certs/ca.crt sslcert=/crdb-certs/client.zitadel_user.crt sslkey=/crdb-certs/client.zitadel_user.key`: failed to configure TLS (unable to read cert: open /crdb-certs/client.zitadel_user.crt: no such file or directory))"
"solved" it by removing 'Cert' and 'Key' from this configuration

Database:
  cockroach:
    Host: 'zitadel-db'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/crdb-certs/ca.crt"
       # Cert: "/crdb-certs/client.zitadel_user.crt"
       # Key: "/crdb-certs/client.zitadel_user.key"
       
```

**Comment by hifabienne** [comment]
@Dima-Kal

**Comment by Dima-Kal** [comment]
> @Dima-Kal Did you use a cockroach Cloud? They do everything with the root cert and you do not need the cert and key

I've used the example here https://docs.zitadel.com/docs/guides/deploy/loadbalancing-example
here's my compose:

```
  zitadel:
    container_name: "zitadel"
    restart: "always"
    networks:
      - "docker_network"
    image: "ghcr.io/zitadel/zitadel:stable"
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "8A960501A73B30FC5F33E2160E25B91A" --tlsMode external'
    volumes:
      - "./configs/zitadel/zitadel-config.yaml:/zitadel-config.yaml:ro"
      - "./configs/zitadel/zitadel-secrets.yaml:/zitadel-secrets.yaml:ro"
      - "./configs/zitadel/zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro"
      - "${DOCKER_STORAGE_PATH}/network/zitadel/zitadel-certs:/crdb-certs:ro"
    depends_on:
      chown:
        condition: "service_completed_successfully"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.rule=Host(`zitadel.${SERVER_DOMAIN}`)"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"
    ports:
      - "47983:8080"

  chown:
    image: "cockroachdb/cockroach:v22.1.0"
    networks:
      - "docker_network"
    entrypoint: ["/bin/bash", "-c"]
    command:
      [
        "cp /certs/ca.crt /zitadel-certs/ && cp /certs/client.root.crt /zitadel-certs/ && cp /certs/client.root.key /zitadel-certs/ && chown 1000:1000 /zitadel-certs/* && chmod 0400 /zitadel-certs/*",
      ]
    volumes:
      - "${DOCKER_STORAGE_PATH}/network/zitadel/db/certs:/certs:ro"
      - "${DOCKER_STORAGE_PATH}/network/zitadel/zitadel-certs:/zitadel-certs:rw"
    depends_on:
      zitadel-db:
        condition: "service_healthy"

  zitadel-db:
    container_name: "zitadel-db"
    restart: "always"
    networks:
      - "docker_network"
    volumes:
      - "${DOCKER_STORAGE_PATH}/network/zitadel/db/certs:/cockroach/certs:rw"
      - "${DOCKER_STORAGE_PATH}/network/zitadel/db/data:/cockroach/cockroach-data:rw"
    image: "cockroachdb/cockroach:v22.1.3"
    command: "start-single-node --advertise-addr zitadel-db"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    #ports:
    #  - "9090:8080"
    #  - "26257:26257"
```
