### ISSUE TITLE
[Bug]: Unable to send emails : Could not set sender

### ISSUE THREAD

**Issue by MinDBreaK** [zitadel/zitadel#4742]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

I'm currently facing an issue with sending emails. Whenever I try to send one, I'm facing the following issue in the logs 

```
time="2022-11-22T16:48:50Z" level=error msg="trigger failed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/handler/handler_projection.go:254" error="ID=EMAIL-s3is3 Message=could not set sender: auth@corp.org Parent=(EOF)" instanceIDs="[188968113247617026]" projection=projections.notifications
```

### To reproduce

1. Create a account (But probably any action sending an email)
2. Send the activation email
3. The error appears in the logs

### Expected behavior

The email should be sent to the user. 

### Version

v1.12.0

### Operating System

Ubuntu 22.04 on Docker
Postgres 14.5

EC2 on AWS

### Relevant Configuration

```yaml
DomainPolicy:
    UserLoginMustBeDomain: false
    ValidateOrgDomains: false
    SMTPSenderAddressMatchesInstanceDomain: false
  SMTPConfiguration:
    # configuration of the host
    SMTP:
      #for example smtp.mailtrap.io:2525
      Host: "smtp-relay.gmail.com:465"
      User: ""
      Password: ""
    TLS: true
    # if the host of the sender is different from ExternalDomain set DefaultInstance.DomainPolicy.SMTPSenderAddressMatchesInstanceDomain to false
    From: "auth@corp.org"
    FromName: "Authentication Systems"
```

### Additional Context

The SMTP authentication is without user authentication. We use SMTP relay with IP authentication. This works well this the `smtp-cli` but sending the email fails with zitadel.

```shell
./smtp-cli --verbose  --server=smtp-relay.gmail.com:465 --from=auth@corp.org --to=user@corp.org --ssl --hello-host=auth.corp.org --body-plain="Hello From Auth"
```

I know 1.13 has been released, but the migration failed (I'll open a new issue for this)
