### ISSUE TITLE
Allow system api token on other apis

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#4764]
At the moment the system api has a different authentication mechanism than the other apis. For setup purpose it would be great to be able to make requests to other apis (admin and management) with the system token. So we can enable the customer portal to setup things.

**Acceptance criteria**
- [ ] Allow System API Token on the ManagementAPI
- [ ] Allow System API Token on the AdminAPI

**Comment by hifabienne** [comment]
Just allowing the tokens for the management and auth api is no big deal.
What we have to look at is how do we handle roles for that user? 
Is the system user allowed to do anything? Do we want to give specific roles?
It is important that we do not count calls with that user to the authenticated requests. Because mostly we will do this calls and we should not bill them to the customers.

@livio-a @fforootd @adlerhurst any opinions?

**Comment by fforootd** [comment]
I think we should allow users to create system api uses (keys) which can have a defined scope of instance access.

Something like this:

```yaml
SystemAPIUsers:
  - PortalUser:
      Path: /path/to/superuser/key.pem
      Scope: # Optional filter for the instances domains or ids
        - *
      Roles: # Optional list of ZITADEL Manager Roles
        - IAM_OWNER
```
