### ISSUE TITLE
[Bug]: When trying to run with postgres

### ISSUE THREAD

**Issue by overpod** [zitadel/zitadel#4898]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Error on first run
```
time="2022-12-17T07:35:34Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2022-12-17T07:35:34Z" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:62"
time="2022-12-17T07:35:34Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel
time="2022-12-17T07:35:34Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2022-12-17T07:35:34Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel
time="2022-12-17T07:35:34Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
time="2022-12-17T07:35:34Z" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:62"
time="2022-12-17T07:35:35Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:60"
time="2022-12-17T07:35:35Z" level=warning msg="postgres is currently in beta" caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:62"
time="2022-12-17T07:35:35Z" level=info msg="verify migration 01_tables" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39"
time="2022-12-17T07:35:35Z" level=info msg="verify migration 02_assets" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39"
time="2022-12-17T07:35:35Z" level=info msg="verify migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39"
time="2022-12-17T07:35:35Z" level=info msg="starting migration 03_default_instance" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49"
time="2022-12-17T07:35:35Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:51" error="cannot start key storage: ID= Message=masterkey must be 32 bytes, but is 9"
time="2022-12-17T07:35:35Z" level=fatal msg="unable to migrate step 3" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:109" error="cannot start key storage: ID= Message=masterkey must be 32 bytes, but is 9"

```

### To reproduce

Run version ghcr.io/zitadel/zitadel:v2.16.0 with postgres
I am using docker-swarm

```
version: "3.7"
services:
  app:
    image: ghcr.io/zitadel/zitadel:v2.16.0
    command: 'start-from-init --masterkey $ZITADEL_MASTER_KEY --tlsMode disabled'
    environment:
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable # is missing in your comment above
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=zitadel
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=zitadel
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable         
    networks:
      - default
      - zitadel
    ports:
      - 8080:8080      
    deploy:
      replicas: 1
      

  db:
    image: postgres:15-alpine
    ports:
      - 5433:5432
    volumes:
      - db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    networks:
      - zitadel
    deploy:
      replicas: 1
    environment:
      POSTGRES_DB: zitadel
      POSTGRES_USER: zitadel
      POSTGRES_PASSWORD: zitadel          

networks:
  default:
    external: true
    name: share
  zitadel:

volumes:
  db:

```
