### ISSUE TITLE
[Bug]: Unable to disable AllowRegister on FirstInstance with Helm deployment

### ISSUE THREAD

**Issue by meyfa** [zitadel/zitadel#4992]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

We are deploying via the Helm chart, and as part of the `configmapConfig` value, we try to disable registration. This doesn't work - registration is enabled on the instance and organization.

### To reproduce

1. Deploy Zitadel using Helm. Inside the values, specify the instance as described below.
2. Open up the console UI.
3. Observe that the Register button is available. Alternatively, log in with the admin user, and observe that inside the instance settings, "Allow register" is checked.

### Expected behavior

I would have expected `FirstInstance.LoginPolicy.AllowRegister` to affect the ability to register.

### Version

v2.15.0

### Operating System

Zitadel Helm chart: v4.1.3
Kubernetes: v1.25.4

### Relevant Configuration

```yaml
zitadel:
  configmapConfig:
    FirstInstance:
      InstanceName: Foo
      LoginPolicy:
        AllowRegister: false
      Org:
        Name: Foo Org
        Human:
          # ...
```

### Additional Context

The default value for `AllowRegister` is documented here:

https://github.com/zitadel/zitadel/blob/5651f98600ba17dfc8294f6ae1df34748167cb9a/cmd/defaults.yaml#L422
