### ISSUE TITLE
[Bug]: SMTP with Exchange gives Unrecognized Authentication Type Error

### ISSUE THREAD

**Issue by lusu007** [zitadel/zitadel#5424]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

If you configure an Exchange SMTP server for sending Zitadel email, Zitadel throws an error.

When TLS is disabled, sending mail fails with the following:

```
level=error msg="could not connect to smtp" caller="/home/runner/work/zitadel/zitadel/internal/notification/channels/smtp/channel.go:32" error="unencrypted connection"
```

When TLS is enabled, the log instead contains:

```
level=warning msg="could not connect using normal tls. trying starttls instead..." caller="/home/runner/work/zitadel/zitadel/internal/notification/channels/smtp/channel.go:121" error="tls: first record does not look like a TLS handshake"
level=error msg="could not connect to smtp" caller="/home/runner/work/zitadel/zitadel/internal/notification/channels/smtp/channel.go:32" error="504 5.7.4 Unrecognized authentication type"
```

The issue is further discussed in #4263.

### To reproduce

1. Configure Zitadel using an Exchange SMTP server
2. Start Zitadel
3. Try sending an email e.g. with registering or resetting your password

### Expected behavior

Zitadel should send an email.

### Version

v2.21.2

### Relevant Configuration

This is an extract from my configuration which contains the important part:

```yaml
SMTPConfiguration:
  SMTP:
    Host: pro2.mail.ovh.net:587
    User: admin@example.com
    Password: password
  TLS: false
  From: noreply@example.com
  FromName: Example Identity
```
