### ISSUE TITLE
Message=Instance not found

### ISSUE THREAD

**Issue by fcrbat** [zitadel/zitadel#5615]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

Hi,

thanks for this cool project. I'm running it on a Alpine Linux VM and have troubles accessing a new created instance. 
I tried to fix it with https://github.com/zitadel/zitadel/issues/4452 but I was not successful....
I tried to access the new instance with Firefox/Chrome and with curl (with Header direct on the ReverseProxy) but I get the always same error message: Instance not found.
Firefox/Chrome: https://test2.oidc.fullcron.tech/ui/login
curl --header "Host: test2.oidc.fullcron.tech" https://zitadel01.auth.fmf.local:8080/ui/login

The URL https://oidc.fullcron.tech/ui/console is working just fine.

### To reproduce

1) Log into https://oidc.fullcron.tech/ui/console
2) create a new Instance
3) configure DNS and add hostname to caddy
/etc/caddy/Caddyfile: 
test2.oidc.fullcron.tech {
        reverse_proxy {
            to https://zitadel01.auth.fmf.local:8080 https://zitadel02.auth.fmf.local:8080 https://zitadel03.auth.fmf.local:8080
            #lb_policy ip_hash
            health_uri "/debug/healthz"
            health_interval 3s
            health_timeout 1s
            health_body "ok"
        }
}

### Expected behavior

I should be able to register a new user, but I get the error: ID=QUERY-n0wng Message=Instanz nicht gefunden

### Version

2.17.3

### Operating System

Alpine Linux 3.17.1

### Relevant Configuration

/opt/zitadel/zitadel-config.yaml:

```
Log:
  Level: 'info'

ExternalSecure: true
ExternalDomain: 'oidc.fullcron.tech'
ExternalPort: 443

TLS:
  # if enabled, ZITADEL will serve all traffic over TLS (HTTPS and gRPC)
  # you must then also provide a private key and certificate to be used for the connection
  # either directly or by a path to the corresponding file
  Enabled: true
  # Path to the private key of the TLS certificate, it will be loaded into the Key
  # and overwrite any exising value
  KeyPath: /opt/zitadel/certs/zitadel01.fmf.local.key
  # Private key of the TLS certificate (KeyPath will this overwrite, if specified)
  # Key: #<bas64 encoded content of a pem file>
  # Path to the certificate for the TLS connection, it will be loaded into the Cert
  # and overwrite any exising value
  CertPath: /opt/zitadel/certs/zitadel01.fmf.local.crt
  # Certificate for the TLS connection (CertPath will this overwrite, if specified)
  # Cert: #<bas64 encoded content of a pem file>

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    Host: 'dbha.db.fmf.local'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: "/opt/zitadel/crdb-certs/ca.crt"
        Cert: "/opt/zitadel/crdb-certs/client.zitadel_user.crt"
        Key: "/opt/zitadel/crdb-certs/client.zitadel_user.key"
    Admin:
      SSL:
        Mode: 'verify-full'
        RootCert: "/opt/zitadel/crdb-certs/ca.crt"
        Cert: "/opt/zitadel/crdb-certs/client.root.crt"
        Key: "/opt/zitadel/crdb-certs/client.root.key"
```
