### ISSUE TITLE
[Load Balancing Example] error: ERR_CONNECTION_CLOSED

### ISSUE THREAD

**Issue by elkon028** [zitadel/zitadel#5786]
I configured according to [Load Balancing Example](https://zitadel.com/docs/self-hosting/deploy/loadbalancing-example)
open: `https://t470p.com` unable to access
error: ERR_CONNECTION_CLOSED

## `cat /etc/hosts`
```
# ...
127.0.0.1       t470p.com
# ...
```
## docker-compose.yaml
```yaml
# docs: https://zitadel.com/docs/self-hosting/deploy/compose
# Run the database and application containers.
# export ZITADEL_MASTERKEY="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
# docker-compose -f docker-compose.yaml up -d
version: '3.8'

services:
  traefik:
    networks:
      - 'zitadel'
    image: 'traefik:v2.7'
    ports:
      - '8800:80'
      - '8080:8080'
      - '443:443'
    volumes:
      - './traefik.yaml:/etc/traefik/traefik.yaml'
      - /var/run/docker.sock:/var/run/docker.sock

  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:stable'
    command: 'start-from-init --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml --masterkey "ee34sWIMERmmn1esg58hmEM0PPKMcztX" --tlsMode external'
    depends_on:
      certs:
        condition: 'service_completed_successfully'
    # ports:
    #   - '8080:8080'
    volumes:
      - './zitadel-config.yaml:/zitadel-config.yaml:ro'
      - './zitadel-secrets.yaml:/zitadel-secrets.yaml:ro'
      - './zitadel-init-steps.yaml:/zitadel-init-steps.yaml:ro'
      - 'zitadel-certs:/crdb-certs:ro'

  certs:
    image: 'cockroachdb/cockroach:v22.2.8'
    entrypoint: ['/bin/bash', '-c']
    command:
      [
        'cp /certs/* /zitadel-certs/ && cockroach cert create-client --overwrite --certs-dir /zitadel-certs/ --ca-key /zitadel-certs/ca.key shuxin && chown 1000:1000 /zitadel-certs/*',
      ]
    volumes:
      - 'certs:/certs:ro'
      - 'zitadel-certs:/zitadel-certs:rw'
    depends_on:
      cockroach-database:
        condition: 'service_healthy'

  cockroach-database:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:v22.2.8'
    command: 'start-single-node --advertise-addr cockroach-database'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health?ready=1']
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'
    volumes:
      - 'certs:/cockroach/certs:rw'
      - 'data:/cockroach/cockroach-data:rw'

networks:
  zitadel:

volumes:
  certs:
  zitadel-certs:
  data:
```

## traefik.yaml
```yaml
entrypoints:
  web:
    address: ':80'

  websecure:
    address: ':433'

api:
  # Enable the API in insecure mode
  insecure: true
  # Enabled Dashboard
  dashboard: true

tls:
  stores:
    default:
      # generates self-signed certificates
      defaultCertificate:

providers:
  file:
    filename: /etc/traefik/traefik.yaml

http:
  middlewares:
    zitadel:
      headers:
        isDevelopment: false
        allowedHosts:
          - 't470p.com'
        customRequestHeaders:
          :authority: 't470p.com'
    redirect-to-https:
      redirectScheme:
        scheme: https
        port: 433
        permanent: true

  routers:
    # Redirect HTTP to HTTPS
    router0:
      entryPoints:
        - web
      middlewares:
        - redirect-to-https
      rule: 'HostRegexp(`t470p.com`, `{subdomain:[a-z]+}.t470p.com`)'
      service: zitadel
    # The actual ZITADEL router
    router1:
      entryPoints:
        - websecure
      service: zitadel
      middlewares:
        - zitadel
      rule: 'HostRegexp(`t470p.com`, `{subdomain:[a-z]+}.t470p.com`)'
      tls:
        domains:
          - main: 't470p.com'
            sans:
              - '*.t470p.com'
              - 't470p.com'

  # Add the service
  services:
    zitadel:
      loadBalancer:
        servers:
          # h2c is the scheme for unencrypted HTTP/2
          - url: h2c://zitadel:8080
        passHostHeader: true
```

## zitadel-config.yaml
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
Log:
  Level: 'info'

# Make ZITADEL accessible over HTTP, not HTTPS
ExternalSecure: true
ExternalDomain: 't470p.com'
ExternalPort: 443

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    Host: 'cockroach-database'
    User:
      SSL:
        Mode: 'verify-full'
        RootCert: '/crdb-certs/ca.crt'
        Cert: '/crdb-certs/client.shuxin.crt'
        Key: '/crdb-certs/client.shuxin.key'
    Admin:
      SSL:
        Mode: 'verify-full'
        RootCert: '/crdb-certs/ca.crt'
        Cert: '/crdb-certs/client.root.crt'
        Key: '/crdb-certs/client.root.key'
```
## zitadel-init-steps.yaml
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/setup/steps.yaml
FirstInstance:
  DefaultLanguage: 'zh'
  Org:
    Human:
      # use the loginname root@zitadel.localhost
      Username: 'root'
      Password: 'RootPassword1!'
      PreferredLanguage: 'zh'
```
## zitadel-secrets.yaml
```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml

# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  cockroach:
    User:
      # If the user doesn't exist already, it is created
      Username: 'shuxin'
    Admin:
      Username: 'root'
```

_Originally posted by @elkon028 in https://github.com/zitadel/zitadel/discussions/5784_
