### ISSUE TITLE
[Bug]: Zitadel can't connect to external PostgreSQL database instance

### ISSUE THREAD

**Issue by nettworker** [zitadel/zitadel#5810]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Describe the bug

I tried to bring up Zitadel with external (related to the Zitadel host) PostgreSQL database instance. 

Before the start i've done all steps described here:
https://zitadel.com/docs/self-hosting/manage/database at the "Postgres" sheet.

The following config file `zitadel-conf.yml` was used:
```yml
Log:
  Level: info

Port: 8080
ExternalPort: 8080
ExternalDomain: localhost
ExternalSecure: false

Database:
  postgres:
    Host: pg1.mynet.net
    Port: 6432
    Database: zitadel
    MaxOpenConns: 25
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options: ""
    User:
      Username: zitadel
      Password: "supPer-3Pass"
      SSL:
        Mode: disable
        #RootCert:
        #Cert:
        #Key:
```

The following init steps file `zitadel-init.yml` was used:
```yml
FirstInstance:
  Org:
    Human:
      Username: 'admin'
      Password: 'Adm384-Du'
```

I tried with the following commands:
```bash
export ZITADEL_MASTERKEY="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
./zitadel start-from-init --masterkeyFromEnv --config zitadel-conf.yml --steps zitadel-init.yml  
```

and has got the following messages:
```
INFO[0000] initialization started                        caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
WARN[0000] postgres is currently in beta                 caller="/home/runner/work/zitadel/zitadel/internal/database/postgres/config.go:62"
FATA[0000] unable to initialize the database             caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:65" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(cannot parse `host=pg1.mynet.net port=6432 user= application_name=zitadel sslmode= dbname=postgres sslrootcert=`: failed to configure TLS (sslmode is invalid))"
```

I am really don't understand why Zitadel trying connect to the `postgress` database when config file has direct order to use `zitadel` database.

### To reproduce

The following config file `zitadel-conf.yml` was used:
```yml
Log:
  Level: info

Port: 8080
ExternalPort: 8080
ExternalDomain: localhost
ExternalSecure: false

Database:
  postgres:
    Host: pg1.mynet.net
    Port: 6432
    Database: zitadel
    MaxOpenConns: 25
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options: ""
    User:
      Username: zitadel
      Password: "supPer-3Pass"
      SSL:
        Mode: disable
        #RootCert:
        #Cert:
        #Key:
```

The following init steps file `zitadel-init.yml` was used:
```yml
FirstInstance:
  Org:
    Human:
      Username: 'admin'
      Password: 'Adm384-Du'
```

I tried with the following commands:
```bash
export ZITADEL_MASTERKEY="$(tr -dc A-Za-z0-9 </dev/urandom | head -c 32)"
./zitadel start-from-init --masterkeyFromEnv --config zitadel-conf.yml --steps zitadel-init.yml  
```

### Expected behavior

The configured database name - "zitadel" should be used instead of "postgres".

### Version

2.25.5

### Operating System

Linux tb1 5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Additional Context

I suspect that something wrong with your logic here:
https://github.com/zitadel/zitadel/blob/main/internal/database/postgres/config.go#L146-L150

By my mind - database type = "postgres" and database name it is completly different things.

P.S. I tried to configure database settings via environment variables such as `ZITADEL_DATABASE_POSTGRES_...` with the same negative results.
P.S.S. I was successfully tested my PG instance via `psql` CLI command from the host where Zitadel was executed.
