### ISSUE TITLE
add `zitadel ready` command

### ISSUE THREAD

**Issue by adlerhurst** [zitadel/zitadel#6055]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

As an operator of ZITADEL i wan't to verify if zitadel is healthy so that I can use add the command to the health checks of kubernetes or docker.

The cli command `zitadel ready` was added by the #5953 https://github.com/zitadel/zitadel/blob/35c464c88bcdac7f70449bd8e2c81c9b57fc2f9e/cmd/ready/ready.go#L16. but the command is very basic and simply executes a http call to localhost/debug/health which might not work in all scenarios.

### Describe your ideal solution

As an operator of ZITADEL i wan't to verify if zitadel is healthy so that I can use add the command to the health checks of kubernetes or docker.

### Version

main

### Environment

Self-hosted

**Comment by crazybolillo** [comment]
I could work on this but I wonder what else should the command check?

**Comment by adlerhurst** [comment]
Hi @crazybolillo 

Thanks for reaching out. I will create a detailed list asap

**Comment by adlerhurst** [comment]
Hi @crazybolillo 

I have update the issue. The only missing part is adding it to the dockerfile. Let me know if something is unclear.

**Comment by crazybolillo** [comment]
Thanks @adlerhurst , seems clear enough, hopefully I got it right in #8606.

**Comment by kasir-barati** [comment]
The `healthcheck` attribute for the `ghcr.io/zitadel/zitadel-login`:

```yaml
services:
  zitadel-login:
    image: ghcr.io/zitadel/zitadel-login:v4.12.2
    restart: unless-stopped
    environment:
      ZITADEL_API_URL: http://zitadel:8080
      NEXT_PUBLIC_BASE_PATH: /ui/v2/login
      ZITADEL_SERVICE_USER_TOKEN_FILE: /zitadel-pat/login-client.pat
      CUSTOM_REQUEST_HEADERS: "Host:localhost,X-Forwarded-Proto:http"
    volumes:
      - zitadel-pat:/zitadel-pat:ro
    depends_on:
      zitadel:
        condition: service_healthy
    healthcheck:
      test:
        - CMD
        - /bin/sh
        - -c
        - node /app/healthcheck.mjs http://localhost:3000/ui/v2/login/healthy
```

> [!TIP]
>
> The `/app/healthcheck.mjs` might be named `/app/healthcheck.js` in older versions.
