### ISSUE TITLE
[Bug]: Postgres only works via ENV but not via ConfigMap

### ISSUE THREAD

**Issue by unique-dominik** [zitadel/zitadel#6106]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.28.1

### Describe the problem caused by this bug

![image](https://github.com/zitadel/zitadel/assets/103249640/04d03f1f-20c6-403e-b98f-fa06687be16a)

Using this setup (yes, with commented code) Zitadel errors out with:

```
zitadel-1    | time="2023-06-27T09:41:23Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
zitadel-1    | time="2023-06-27T09:41:23Z" level=fatal msg="unable to initialize the database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:65" error="ID=DATAB-0pIWD Message=Errors.Database.Connection.Failed Parent=(failed to connect to `host=localhost user=root database=zitadel`: dial error (dial tcp [::1]:26257: connect: cannot assign requested address))"
zitadel-1 exited with code 1
```

It seems that the parser just does not work. Which is weird as when you comment the opposite code and use the `ENV` approach, it suddenly works.

The code on the left is a 1:1 copy of https://zitadel.com/docs/self-hosting/manage/database#postgres.

I somehow feel I came once a bit further but don't know how but then it failed with invalid SSL mode or so. All in all these configs appear to behave not the same as `ENV` always works.

### To reproduce

Use the docker-compose below ⬇️ 

### Expected behavior

The parser should work the same as the environment variables 😊

### Operating System

not so relevant but linux/amd64 docker

### Relevant Configuration

This docker-compose file is enough:

```yaml
version: '3.7'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '5432:5432'

  zitadel:
    build:
      context: .
      dockerfile: Dockerfile.zitadel
    # environment:
    #   - 'ZITADEL_DATABASE_POSTGRES_HOST=postgres'
    #   - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
    #   - 'ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel'
    #   - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel'
    #   - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel'
    #   - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
    #   - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
    #   - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres'
    #   - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
    command: 'start-from-init --config /zitadel-config.yaml --steps /zitadel-init-steps.yaml  --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    depends_on:
      postgres:
        condition: 'service_healthy'

```

```Dockerfile
FROM ghcr.io/zitadel/zitadel:v2.28.1

COPY zitadel/. .
```

whereas `zitadel/` is

zitadel-config.yaml:
```
Log:
  Level: 'info'

# Make ZITADEL accessible over HTTP, not HTTPS
ExternalSecure: false
ExternalPort: 9123

Database:
  postgres:
    Host: postgres
    Port: 5432
    Database: zitadel
    MaxOpenConns: 25
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options:
    User:
      Username: zitadel
      Password: zitadel
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:
    Admin:
      Username: postgres
      Password: postgres
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:

LogStore:
  Access:
    Stdout:
      Enabled: true

DefaultInstance:
  DomainPolicy:
    UserLoginMustBeDomain: true
    ValidateOrgDomain: false
  LoginPolicy:
    AllowDomainDiscovery: true
  SMTPConfiguration:
    SMTP:
      Host: smtp.sendgrid.net:465
      User: apikey
      Password: <put sendgrid password here>
    TLS: true
    From: 'no-reply@my.app'
    FromName: My
```

zitadel-init-steps.yaml

```
FirstInstance:
  InstanceName: MY
  DefaultLanguage: en
  Org:
    Name: My IAM
    Human:
      Username: root@my-iam.localhost
      Password: 'RootPassword1!'
```

### Additional Context

The same issue seems to have been _hinted_ at here:
https://github.com/zitadel/zitadel/issues/3598#issuecomment-1289463922

I can not see in the release notes any fix for that as well in 2.29 or 2.30
https://github.com/zitadel/zitadel/releases

I am also aware that PSQL is an enterprise feature and we self-host but an answer would brighten my day 🌥️

**Comment by fforootd** [comment]
Hm that is really odd, I just started a Zitadel locally with a Cloud SQL attached.

This really looks like zitadel does not parse the config at all. I.e it is not accessible.
Are you sure the config is available in the container?

These files below worked in my case. 

```yaml
version: '3.8'
services:

  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:v2.29.1'
    command: 'start-from-init --config /example-zitadel-config.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'

    volumes:
      - './example-zitadel-config.yaml:/example-zitadel-config.yaml:ro'
    ports:
      - '8080:8080'

networks:
  zitadel:

volumes:
  certs:
  zitadel-certs:
  data:
```

```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
Log:
  Level: 'info'


# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  postgres:
    Host: [REDACTED]
    Port: 5432
    Database: zitadel_2
    MaxOpenConns: 50
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options:
    User:
      Username: [REDACTED]
      Password: [REDACTED]
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:
    Admin:
      Username: [REDACTED]
      Password: [REDACTED]
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:

LogStore:
  Access:
    Stdout:
      Enabled: false
```

**Comment by fforootd** [comment]
I just started a Zitadel on a Google Cloud SQL Postgres and this config below worked.

To me it looks like in your case Zitadel can not access the config and falls back to default values.
Can you make sure the file is in that exact location?

```yaml
version: '3.8'
services:

  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:v2.29.1'
    command: 'start-from-init --config /example-zitadel-config.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'

    volumes:
      - './example-zitadel-config.yaml:/example-zitadel-config.yaml:ro'
    ports:
      - '8080:8080'

networks:
  zitadel:

volumes:
  certs:
  zitadel-certs:
  data:
```


```yaml
# All possible options and their defaults: https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml
Log:
  Level: 'info'


# If not using the docker compose example, adjust these values for connecting ZITADEL to your CockroachDB
Database:
  postgres:
    Host: [Redacted]
    Port: 5432
    Database: zitadel_2
    MaxOpenConns: 50
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options:
    User:
      Username:  [Redacted]
      Password:  [Redacted]
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:
    Admin:
      Username:  [Redacted]
      Password:  [Redacted]
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:

LogStore:
  Access:
    Stdout:
      Enabled: false
```
