### ISSUE TITLE
[Bug]: unable to read config: cannot parse 'Port' as uint: strconv.ParseUint: parsing "tcp://10.43.212.45:8080": invalid syntax

### ISSUE THREAD

**Issue by myyra** [zitadel/zitadel#6230]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.30.0

### Describe the problem caused by this bug

Zitadel fails to start because it's trying to parse a full URL as a Port.

Full log line:
```
time="2023-07-18T17:02:50Z" level=fatal msg="unable to read config" caller="/home/runner/work/zitadel/zitadel/cmd/start/config.go:88" error="1 error(s) decoding:\n\n* cannot parse 'Port' as uint: strconv.ParseUint: parsing \"tcp://10.43.212.45:8080\": invalid syntax"
```

### To reproduce

Launch Zitadel in Kubernetes with a `Service` deployed. The failed content will be the service IP and port (changing the port and deleting the failing pod will immediately show the new port)

Deleting the service allows Zitadel to start.

### Expected behavior

Zitadel doesn't fetch a random IP and port and try to parse it as a port.

### Operating System

Kubernetes v1.27.1

### Relevant Configuration

``` yaml
Database:
  cockroach:
    Admin:
      SSL:
        Mode: "verify-full"
      Username: "root"
    Host: "cockroachdb-public.zitadel.svc.cluster.local"
    User:
      SSL:
        Mode: "verify-full"
      Username: "zitadel"
ExternalDomain: "redacted"
ExternalPort: 443
ExternalSecure: true
FirstInstance:
  Org:
    Machine:
      Machine:
        Name: "Machine User"
        Username: "admin"
      MachineKey:
        Type: 1
Machine:
  Identification:
    Hostname:
      Enabled: true
    PrivateIp:
      Enabled: false
    Webhook:
      Enabled: false
TLS:
  Enabled: false
```

### Additional Context

It would be helpful to know where the content for the port is fetched from, that would allow me to debug further.
