### ISSUE TITLE
COPY zitadel /app/zitadel  Zitadel folder not available while building through build/dockerfile

### ISSUE THREAD

**Issue by Muthiah131998** [zitadel/zitadel#6277]
I have tried to build zitadel through build/dockerfile but got some error like Zitadel folder not available

Current Dockerfile

```
FROM --platform=$TARGETPLATFORM debian:latest as artifact
ENV ZITADEL_ARGS=
ARG TARGETPLATFORM

RUN apt-get update && apt-get install ca-certificates -y

COPY build/entrypoint.sh /app/entrypoint.sh
COPY zitadel /app/zitadel

RUN useradd -s "" --home / zitadel && \
    chown zitadel /app/zitadel && \
    chmod +x /app/zitadel && \
    chown zitadel /app/entrypoint.sh && \
    chmod +x /app/entrypoint.sh

WORKDIR /app
ENV PATH="/app:${PATH}"

USER zitadel
ENTRYPOINT ["/app/entrypoint.sh"]

FROM --platform=$TARGETPLATFORM scratch as final
ARG TARGETPLATFORM

COPY --from=artifact /etc/passwd /etc/passwd
COPY --from=artifact /etc/ssl/certs /etc/ssl/certs
COPY --from=artifact /app/zitadel /app/zitadel

HEALTHCHECK NONE

USER zitadel
ENTRYPOINT ["/app/zitadel"].
```

Please guide me how to build this image with exact steps need to follow.

**Comment by Muthiah131998** [comment]
Hi @hifabienne  Need your Help on this

**Comment by hifabienne** [comment]
Hi @Muthiah131998 
I am the wrong person to help you on this. 
@eliobischof Can you help out?

@Muthiah131998 I can also recommend that you join our community chat, where we have a lot of people helping each other with some troubles: zitadel.com/chat

**Comment by fforootd** [comment]
Hm I think you should look at the just recently created make file.

This command builds all you need https://github.com/zitadel/zitadel/blob/d3e403f645a3a9bfd3254b46bb7427b8716542d6/Makefile#L9

You need to have installed go and node

**Comment by Muthiah131998** [comment]
Hi @fforootd Thankyou for your Help, Can you give more details After Installed go and node I need to run Makefile after that I need to try docker build . Am I correct? 

If Possible can you provide commands for it ,would be really helpful

**Comment by fforootd** [comment]
You should find some guidance here https://github.com/zitadel/zitadel/blob/main/CONTRIBUTING.md#backendlogin

**Comment by fforootd** [comment]
hm weird, @adlerhurst @stebenz any ideas?

I just tried to recreate this and received a different error:

```
ffo@ffo-pc:~/git/zitadel/zitadel$ make compile
go mod download
go install internal/protoc/protoc-gen-authoption/main.go \
    && mv $(go env GOPATH)/bin/main ""$(go env GOPATH)/bin"/protoc-gen-authoption"
go install internal/protoc/protoc-gen-zitadel/main.go \
    && mv $(go env GOPATH)/bin/main ""$(go env GOPATH)/bin"/protoc-gen-zitadel"
go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.30
go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.15.2
go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.15.2
go install github.com/envoyproxy/protoc-gen-validate@v0.10.1
buf generate
Failure: plugin authoption: could not find
```

We also should document the need to install buf, because this was somehow missing.

**Comment by adlerhurst** [comment]
Which platforms are you using, it's only tested on linux (not wsl) and macos

**Comment by fforootd** [comment]
> Which platforms are you using, it's only tested on linux (not wsl) and macos

Ubuntu 22.04 (as VM and WSL2) both the same result. To me it looks like you have a file locally that is missing with us.

**Comment by Muthiah131998** [comment]
Yes I was Using Linux Ubuntu Machine 

Yeah For workaround I tried to install go and buff got some openapiv2 package was missing that also installed then make compile got succeeded and zitadel binary folder got generated

**Comment by Muthiah131998** [comment]
But Go Installed if i run just make compile looks like current setup was not working we need to install multiple packages and need to solve the issue one by one .

**Comment by adlerhurst** [comment]
Okay thanks for the infos i try to reproduce tomorrow

**Comment by Muthiah131998** [comment]
![image](https://github.com/zitadel/zitadel/assets/110098347/32c3a2f4-7a85-49be-a054-0d507b0ffcc9)
For I used My Image zitadel was around  33 MB and used in docker compose file got this message  

missing anything on this ? Also the size of zitadel image 33MB size of image was correct?

**Comment by Muthiah131998** [comment]
![image](https://github.com/zitadel/zitadel/assets/110098347/30d1c20a-ffe7-4315-a2d1-bb70f794d901)
Update on this Added ZITADEL_EXTERNALDOMAIN and after that got this page still loading 

Also checked in Network Tab seems like Openid Configuration was blocking
![image](https://github.com/zitadel/zitadel/assets/110098347/03c7c780-e9a0-43fd-8da6-fd31cc876d41)

```
version: "3.3"
services:
  zitadel:
    restart: always
    image: <reponame?zitadel:${SOFTWARE_VERSION_TAG}
    command: start-from-init --masterkey "MasterkeyNeedsToHave32Characters"
      --tlsMode disabled
    environment:
      - ZITADEL_DATABASE_COCKROACH_HOST=crdb
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALDOMAIN=${DOMAIN}
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS=false
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST=${SMTP_HOST}:${SMTP_PORT}
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME=Zitadel
      - ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM=${SMTP_FROM_EMAIL}
    depends_on:
      - crdb
    ports:
      - 172.17.0.1:8586:8080
  crdb:
    restart: always
    image: cockroachdb/cockroach:v22.2.2
    command: start-single-node --insecure
    ports:
      - 172.17.0.1:9090:8080
      - 172.17.0.1:26257:26257
```
