### ISSUE TITLE
[Bug]: Date Header missing in Mails

### ISSUE THREAD

**Issue by pulsar256** [zitadel/zitadel#6293]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.31.3

### Describe the problem caused by this bug

`Date` header not present when sending E-Mail verification and password reset E-Mails.

Example of a captured E-Mail:

```
From: <REDACTED>
To: <REDACTED>
Cc:
Subject: Verify email
MIME-version: 1.0;
Content-Type: text/html; charset="UTF-8";


<!doctype html>
(...)
```

Direct implications of this behaviour:
- E-Mail spam score increases due to missing mandatory header
- E-Mail clients cannot properly parse the mail, some of them will date the mail to 1970-01-01

### To reproduce

- configure SMTP server in Instance Settings -> Notification Settings
- TLS was disabled during testing 
- change / add an E-Mail address to the currently logged in user to trigger an E-Mail verification flow.

### Expected behavior

`Date` Header is included in sent E-Mails according to [RFC822](https://datatracker.ietf.org/doc/html/rfc822#appendix-A.3.1)

### Relevant Configuration

```yaml
zitadel:
    image: "ghcr.io/zitadel/zitadel:latest"
    container_name: "zitadel"
    restart: always
    command: 'start-from-init --masterkeyFromEnv --tlsMode external --steps /init-steps.yaml'
    volumes:
      - "./zitadel/init-steps.yaml:/init-steps.yaml:ro"
    environment:
      - "ZITADEL_EXTERNALSECURE=true"
      - "ZITADEL_EXTERNALDOMAIN=${HOSTNAME_AUTH}"
      - "ZITADEL_EXTERNALPORT=443"
      - "ZITADEL_MASTERKEY=${ZITADEL_MASTERKEY}"
      - "ZITADEL_DATABASE_POSTGRES_HOST=<REDACTED>"
      - "ZITADEL_DATABASE_POSTGRES_PORT=5432"
      - "ZITADEL_DATABASE_POSTGRES_DATABASE=<REDACTED>"
      - "ZITADEL_DATABASE_POSTGRES_USER_USERNAME=<REDACTED>"
      - "ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=<REDACTED>"
      - "ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=<REDACTED>"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=<REDACTED>"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=<REDACTED>"
      - "ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=<REDACTED>"
      - "ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED=<REDACTED>"
    depends_on:
      - db-zitadel
    ports:
      - "127.0.0.1:8081:8080"
    labels:
      - "traefik.enable=true"
      - ...
```
