### ISSUE TITLE
[Bug]: Primary Domain does not update for E-Mail

### ISSUE THREAD

**Issue by hofq** [zitadel/zitadel#6576]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Self-hosted

### Version

2.28.1

### Describe the problem caused by this bug

When i Updated the Domain (zitadel.configmapConfig.ExternalDomain) for Zitadel in the Helm Chart, the Domain in E-Mails send to new users does not get updated.

### To reproduce

1. Install Zitadel using this Guide (ExternalDomain unset): https://zitadel.com/docs/self-hosting/deploy/kubernetes
2. After ensuring it works as intended, add the domain to Helm Values (zitadel.configmapConfig.ExternalDomain: zitadel.my-domain.tld)
3. If new Users get invited, they will receive an E-Mail with the old domain (localhost) and manually have to tweak it.

### Screenshots

![grafik](https://github.com/zitadel/zitadel/assets/54744977/88bc2a1b-e6dc-4138-9df6-44bf9ee10bbd)
![grafik](https://github.com/zitadel/zitadel/assets/54744977/3f29ca0a-6b91-4aa4-8819-86385e71db89)

### Expected behavior

If i set a domain as my External Domain, i want the E-Mail to be updated also.

If this is not possible, i would want instructions on how to manually modifying it in the Database.

### Operating System

Kubernetes: v1.27.5+k0s.0 
Chart Version: 5.*
Database: Cockroach

### Relevant Configuration

helm values:
```yaml
zitadel:
  masterkeySecretName: zitadel-secret
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: zitadel.my-domain.tld
    ExternalPort: 443
    TLS:
      Enabled: false
  configSecretName: zitadel-config
replicaCount: 1
```

### Additional Context

What i've tried without success:
- Setting my-domain.tld, zitadel.my-domain.tld and zitadel.localhost as primary domain
- Re-Building Pods
- Re-Creating Users

**Comment by hifabienne** [comment]
Hei @hofq 
ZITADEL has two different types of domains.
Organization domains, which are used to domain discovery and suffixing users.
And custom domains, on which ZITADEL runs.
In your case you have to change the custom domains, you can do so with the system API.
In the emails we do take the primary domain.
https://zitadel.com/docs/apis/resources/system/system-service-add-domain

**Comment by hofq** [comment]
> Hei @hofq ZITADEL has two different types of domains. Organization domains, which are used to domain discovery and suffixing users. And custom domains, on which ZITADEL runs. In your case you have to change the custom domains, you can do so with the system API. In the emails we do take the primary domain. https://zitadel.com/docs/apis/resources/system/system-service-add-domain

I tried getting Access to the System API, sadly when i try to get a JWT Token from the Cert, ill just get the following Error: 
![grafik](https://github.com/zitadel/zitadel/assets/54744977/6822b560-71d9-4c28-97a4-26803afd7f3f)


I followed the Guide [Here](https://zitadel.com/docs/guides/integrate/access-zitadel-system-api)

**Comment by livio-a** [comment]
Hey @hofq 

Did you create the key pair using openssl? Respectively can you check which type the private key has:
`head -n 1 system-user-1.pem`
it should be:
```
-----BEGIN RSA PRIVATE KEY-----
```

**Comment by hofq** [comment]
with the command `openssl genrsa -out system-user-1.pem 2048` i got
-----BEGIN PRIVATE KEY-----

**Comment by livio-a** [comment]
> with the command `openssl genrsa -out system-user-1.pem 2048` i got -----BEGIN PRIVATE KEY----- @livio-a
> 
> edit: using `openssl/stable,now 3.0.9-1 amd64 [installed,automatic]`

from what i just found, it appears that openssl3 switched the default format to PKCS8 (from PKCS1) and you now need to use `openssl genrsa --traditional 2048`: https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key#comment132991589_20065522

the other option would be to convert the format:
`openssl rsa -in domain.key -out domain-rsa.key`

I just created an issue to be able to support both formats in the tool: https://github.com/zitadel/zitadel-tools/issues/97

**Comment by hofq** [comment]
Hi,
sorry for my late response.
With this i can get the Token, Thanks @livio-a.
but unfortunately I received another error. While running an example curl command to the API like this with the Token
```bash
curl --request POST \
  --url https://sso.hof.pub/system/v1/instances/_search \
  --header 'Authorization: Bearer <token here>' \
  --header 'Content-Type: application/json'
```
i just received the following issue:
`{"code":2,"message":"invalid signature (square/go-jose: error in cryptographic primitive)"}`
have i missed something?

**Comment by livio-a** [comment]
hmm strange... sounds like either the token has some wrong format or something there's an issue with the public key

i'll try to reproduce

**Comment by HungryHowies** [comment]
I'm also having the same issue. Zitadel v2.50.0, Ubuntu 22.0.4.

**Comment by hofq** [comment]
Tried again today with no issues with the API Key and Solved it.

I got the following response from my set domains:

```yaml
curl --request POST --url https://<wanted-domain>/system/v1/instances/121/domains --header 'Authorization: Bearer <token-here>' --header 'Content-Type: application/json' --data-raw '{ "domain": "<wanted-domain>"}' | yq -P


details:
  totalResult: "1"
result:
  - id: "230194407041663180"
    details:
      sequence: "115"
      creationDate: "2023-09-03T00:55:59.565760Z"
      changeDate: "2023-09-03T00:56:01.077266Z"
      resourceOwner: "230194407041663180"
    state: STATE_RUNNING
    name: ZITADEL
    version: 2.28.1
    domains:
      - details:
          sequence: "121"
          creationDate: "2023-09-03T00:56:01.163777Z"
          changeDate: "2023-09-03T00:56:01.131101Z"
          resourceOwner: "230194407041663180"
        domain: localhost
        primary: true
      - details:
          sequence: "125"
          creationDate: "2023-09-03T01:02:13.738421Z"
          changeDate: "2023-09-03T01:02:13.738421Z"
          resourceOwner: "230194407041663180"
        domain: wanted-domain
      - details:
          sequence: "121"
          creationDate: "2023-09-03T00:56:01.163777Z"
          changeDate: "2023-09-03T00:56:01.087568Z"
          resourceOwner: "230194407041663180"
        domain: zitadel-i4gteh.localhost
        generated: true
      - details:
          sequence: "123"
          creationDate: "2023-09-03T01:02:13.701237Z"
          changeDate: "2023-09-03T01:02:13.701237Z"
          resourceOwner: "230194407041663180"
        domain: zitadel-i56teh.wanted-domain
        generated: true
```

you can see both localhost and my here replaced wanted-domain are present.

To set the Primary to my wanted-domain i ran the following:
```yaml
url --request POST --url https://<wanted-domain>/system/v1/instances/230194407041663180/domains/_set_primary --header 'Authorization: Bearer <Token>' --header 'Content-Type: application/json' --data-raw '{ "domain": "<wanted-domain>"}' | yq -P

details:
  sequence: "1146"
  changeDate: "2024-06-23T17:56:13.443587Z"
  resourceOwner: "230194407041663180"
```
Source: https://zitadel.com/docs/apis/resources/system/system-service-set-primary-domain



Would love to get UI Support or Automation for this, since the Method of Changing the Domain is a step that shouldn't require interaction with the API.

For me the easiest option would be if the change of the domain in the Zitadel Helm Values would directly change the primary e-mail domain. Also a place in the Settings where i can find and change it would be a lot easier.
@livio-a
