### ISSUE TITLE
[Bug]: Unable to update some Login Interface Texts

### ISSUE THREAD

**Issue by brandan-schmitz** [zitadel/zitadel#6764]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.38.1

### Describe the problem caused by this bug

I am unable to update any of the Login Interface Texts for my instance or any organization. Whenever I attempt to update a text and save it, I get the following error message.
```
unable to create event (SQL-SBP37)
```

And in the Failed Events section of the instance I am seeing the following error listed as well:
![image](https://github.com/zitadel/zitadel/assets/6267549/30c23aef-900b-4919-acf3-6be6d58ec59a)

In the logs of the Zitadel pod in my kubernetes cluster I also see the following error anytime one is attempted to be saved:
```
time="2023-10-20T06:07:04Z" level=debug msg="query failed" aggregate=instance aggregateId=237021086347227843 aggregateType=instance caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="timeout: context deadline exceeded" eventType=instance.customtext.removed instanceID=237021086347227843
time="2023-10-20T06:07:05Z" level=warning msg="missing translation" args="map[]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/i18n.go:210" error="message \"unable to create event\" not found in language \"en\"" id="unable to create event"
```

### To reproduce

1. Login with an instance administrator account.
2. Navigate to the Instance settings and then the **Login Interface Texts** section.
3. Use the **Login Screen / Interface** drop down menu to select the `Login` options.
4. Attempt to customize some fields.
5. Press the **Save** button to try and save the customization.

### Expected behavior

I would expect to be able to change the login interface texts without any errors.

### Computer:
- Device: `2019 MacBook Pro 16"`
- Operating System: `macOS Sonoma`
- Browser: `Firefox 118.0.2`

### Cluster:
- Kubernetes: `v1.27.1`
- CockroachDB: `v23.1.10 (3-node)` 
- Ingress: `ingress-nginx`

### Relevant Configuration

Below is the configuration I used when installing through helm. I have redacted sensitive items but changed nothing else.

_**Note:** I did manually modify the deployment to add the ZITADEL_LOG_LEVEL to be `debug` to try and get more logs for creating this bug report._ 

Helm command:
```shell
helm upgrade --install zitadel zitadel/zitadel --namespace auth-services -f zitadel-values.yaml --version 7.0.0 --timeout 30m0s
```

zitadel-values.yaml:
```yaml
zitadel:
  configmapConfig:
    ExternalPort: 443
    ExternalDomain: REDACTED
    ExternalSecure: true
    TLS:
      Enabled: false
    WebAuthNName: REDACTED
    Database:
      cockroach:
        Host: cockroachdb-public.database-servers.svc.cluster.local
        Database: zitadel
        MaxOpenConns: 20
        MaxIdleConns: 10
        MaxConnLifetime: 30m
        MaxConnIdleTime: 5m
        User:
          Username: zitadel
          SSL:
            Mode: verify-full
        Admin:
          SSL:
            Mode: verify-full
  secretConfig:
    Database:
      cockroach:
        User:
          Password: "REDACTED"
  masterkey: "REDACTED"
  dbSslCaCrtSecret: cockroachdb-ca-secret
  dbSslAdminCrtSecret: cockroachdb-client-secret
  dbSslUserCrtSecret: cockroachdb-zitadel-secret

replicaCount: 3

image:
  tag: v2.38.1

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: REDACTED
  hosts:
    - host: REDACTED
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - REDACTED
        - '*.REDACTED'
      secretName: zitadel-ui-tls

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    honorLabels: false
    honorTimestamps: true
```

### Additional Context

Below is the log from my Zitadel pod in kubernetes. I scaled my deployment down to one pod, and then restarted it to get a clean set of logs. The only actions taken after it was logged in was attempting to change the Login Interface Texts.

```log
  _____  ___   _____      _      ____    _____   _
 |__  / |_ _| |_   _|    / \    |  _ \  | ____| | |
   / /   | |    | |     / _ \   | | | | |  _|   | |
  / /_   | |    | |    / ___ \  | |_| | | |___  | |___
 /____| |___|   |_|   /_/   \_\ |____/  |_____| |_____|

 ===============================================================

 Version          : v2.38.1
 TLS enabled      : false
 External Secure  : true
 Console URL      : https://REDACTED:443/ui/console
 Health Check URL : https://REDACTED:443/debug/healthz

 ===============================================================

time="2023-10-20T06:06:15Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=237038532521161428 workers=1
time="2023-10-20T06:06:15Z" level=info msg="spooler started" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/spooler/spooler.go:73" lockerID=237038532521226964 workers=1
time="2023-10-20T06:06:15Z" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go:44" locker=237038532521161428--0 logID=LOCKE-lOgbg view=auth.user_sessions
time="2023-10-20T06:06:15Z" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go:44" locker=237038532521226964--0 logID=LOCKE-lOgbg view=adminapi.styling2
time="2023-10-20T06:06:15Z" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go:44" locker=237038532521161428--0 logID=LOCKE-lOgbg view=auth.refresh_tokens
time="2023-10-20T06:06:15Z" level=info msg="server is listening on [::]:8080" caller="/home/runner/work/zitadel/zitadel/cmd/start/start.go:466"
time="2023-10-20T06:06:15Z" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go:44" locker=237038532521161428--0 logID=LOCKE-lOgbg view=auth.users2
time="2023-10-20T06:06:15Z" level=debug msg="locker changed" caller="/home/runner/work/zitadel/zitadel/internal/eventstore/v1/locker/lock.go:44" locker=237038532521161428--0 logID=LOCKE-lOgbg view=auth.tokens
time="2023-10-20T06:07:04Z" level=debug msg="query failed" aggregate=instance aggregateId=237021086347227843 aggregateType=instance caller="/home/runner/work/zitadel/zitadel/internal/eventstore/repository/sql/crdb.go:143" error="timeout: context deadline exceeded" eventType=instance.customtext.removed instanceID=237021086347227843
time="2023-10-20T06:07:05Z" level=warning msg="missing translation" args="map[]" caller="/home/runner/work/zitadel/zitadel/internal/i18n/i18n.go:210" error="message \"unable to create event\" not found in language \"en\"" id="unable to create event"
```

I also did perform an upgrade from v2.35.0 to v2.38.1, and my init and setup pod logs from the upgrade are below. However I will note that this error occurs on a blank install with no upgrade on v2.35.0 and it still occurs on v2.38.1 even with a fresh install at that newer version.
```
time="2023-10-20T05:41:03Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:72"
time="2023-10-20T05:41:03Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:38" username=zitadel
time="2023-10-20T05:41:03Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:38" database=zitadel
time="2023-10-20T05:41:03Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:33" database=zitadel user=zitadel
time="2023-10-20T05:41:03Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69" database=zitadel
```

```
time="2023-10-20T05:41:28Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:63"
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=01_tables
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=02_assets
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=03_default_instance
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=04_eventstore_indexes
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=05_last_failed
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=06_resource_owner_columns
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=07_logstore
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=08_auth_token_indexes
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=09_optimise_indexes
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=10_correct_creation_date
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=11_event_created_at
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=12_auth_users_otp_columns
time="2023-10-20T05:41:28Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=13_fix_quota_constraints
time="2023-10-20T05:41:28Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=13_fix_quota_constraints
time="2023-10-20T05:41:29Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=config_change
time="2023-10-20T05:41:29Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:39" name=projection_tables
time="2023-10-20T05:41:29Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:49" name=projection_tables
```
