### ISSUE TITLE
[Bug]: Can't use PasswordHasher configuration with environment variables

### ISSUE THREAD

**Issue by pbintcha** [zitadel/zitadel#6913]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.40.1

### Describe the problem caused by this bug

When I try to start zitadel with the environment variable `ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_COST` to configure the bcrypt password salt cost, i get the following error
```
Error: cannot start commands: ID=CRYPT-Que4r Message=password hash config invalid Parent=(decode bcrypt params: 1 error(s) decoding:
* 'Cost' expected type 'int', got unconvertible type 'string', value: '11')
```

I'm also having the same kind of error with the other password algorithms

### To reproduce

do a `docker-compose up -d` of the following
```
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:v2.40.1'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ALGORITHM=bcrypt'
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_COST=11'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:latest'
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'

networks:
  zitadel:
```
