### ISSUE TITLE
[Bug]: LDAP internal error after login

### ISSUE THREAD

**Issue by Alvise88** [zitadel/zitadel#7000]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.41.1, latest

### Database

CockroachDB

### Database Version

23.1.12

### Describe the problem caused by this bug

With ldap idp added when i login (using ldap) zitadel throws the following error:

level=error auth_req_id=242850077901589092 caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/renderer.go:342" error="ID=QUERY-C1E4D Message=Errors.Internal Parent=(ERROR: error in argument for $2: invalid UTF-8 sequence (SQLSTATE 22021))"

### To reproduce

Go to http://localhost:8080/, login using ldap, 

### Screenshots

<img width="956" alt="image" src="https://github.com/zitadel/zitadel/assets/6458371/ffe56835-2e6c-47ff-b518-d4a0d31b59a4">

### Operating System

Linux, windows

**Comment by Alvise88** [comment]
Using OpenLDAP the result is:

<img width="582" alt="image" src="https://github.com/zitadel/zitadel/assets/6458371/82042f74-0441-48bd-8e11-640cc4e845c2">


```
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_COCKROACH_HOST=crdb'
      - 'ZITADEL_EXTERNALSECURE=false'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    restart: 'always'
    networks:
      - 'zitadel'
    image: 'cockroachdb/cockroach:latest'
    # image: cockroachdb/cockroach:v22.2.16
    # image: cockroachdb/cockroach:v21.2.17
    command: 'start-single-node --insecure'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health?ready=1"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - '9090:8080'
      - '26257:26257'


  ldap_server:
    # image: wshihadeh/openldap:withdata
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - 'zitadel'
    environment:
      LDAP_ADMIN_PASSWORD: test1234
      LDAP_BASE_DN: dc=shihadeh,dc=intern
    ports:
      - "389:389"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - ldap_data:/var/lib/ldap
      - ldap_config:/etc/ldap/slapd.d

  ldap_server_admin:
    image: osixia/phpldapadmin:0.7.2
    networks:
      - 'zitadel'
    ports:
      - 8090:80
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap_server
      PHPLDAPADMIN_HTTPS: 'false'

networks:
  zitadel:

volumes:
  ldap_data:
  ldap_config:
```

```
dn: cn=developer,dc=shihadeh,dc=intern
changetype: add
objectclass: inetOrgPerson
cn: developer
givenname: developer
sn: Developer
displayname: Developer User
mail: developer@gmail.com
userpassword: developer_pass

dn: cn=maintainer,dc=shihadeh,dc=intern
changetype: add
objectclass: inetOrgPerson
cn: maintainer
givenname: maintainer
sn: Maintainer
displayname: Maintainer User
mail: maintainer@gmail.com
userpassword: maintainer_pass

dn: cn=admin_gh,dc=shihadeh,dc=intern
changetype: add
objectclass: inetOrgPerson
cn: admin_gh
givenname: admin_gh
sn: AdminGithub
displayname: Admin Github User
mail: admin_gh@gmail.com
userpassword: admin_gh_pass

dn: ou=Groups,dc=shihadeh,dc=intern
changetype: add
objectclass: organizationalUnit
ou: Groups

dn: ou=Users,dc=shihadeh,dc=intern
changetype: add
objectclass: organizationalUnit
ou: Users

dn: cn=Admins,ou=Groups,dc=shihadeh,dc=intern
changetype: add
cn: Admins
objectclass: groupOfUniqueNames
uniqueMember: cn=admin_gh,dc=shihadeh,dc=intern

dn: cn=Maintaners,ou=Groups,dc=shihadeh,dc=intern
changetype: add
cn: Maintaners
objectclass: groupOfUniqueNames
uniqueMember: cn=maintainer,dc=shihadeh,dc=intern
uniqueMember: cn=developer,dc=shihadeh,dc=intern
```

<img width="206" alt="image" src="https://github.com/zitadel/zitadel/assets/6458371/335ffbe7-93bb-4edc-bb06-2c3d49e339bb">
