### ISSUE TITLE
[Bug]: Setting SMTP Host via env prevents Zitadel from starting

### ISSUE THREAD

**Issue by maximilianmaihoefner** [zitadel/zitadel#7009]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.42.0

### Database

CockroachDB

### Database Version

v23.1.12

### Describe the problem caused by this bug

When setting `ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST` to any value on a fresh install, Zitadel fails to start with the following error:
```
2023-12-01T09:34:18.154813959Z time="2023-12-01T09:34:18Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:129" error="ID=INST-mruNY Message=Errors.Invalid.Argument" name=03_default_instance
```

### To reproduce

Take the docker-compose and the init sql file and run it.
```docker-compose
version: '3.5'

services:
  zitadel:
    container_name: zitadel
    image: ghcr.io/zitadel/zitadel:v2.42.0-debug
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    restart: no
    environment:
      ZITADEL_DATABASE_COCKROACH_HOST: crdb
      ZITADEL_DATABASE_COCKROACH_DATABASE: zitadel
      ZITADEL_EXTERNALSECURE: false
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST: "mailpit:1025"
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER: ''
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD: ''
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_SSL: false
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_FROM: zitadel@localhost
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_FROMNAME: Zitadel

      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: 'false'
    depends_on:
      crdb:
        condition: 'service_healthy'
    ports:
      - '8080:8080'

  crdb:
    image: cockroachdb/cockroach:v23.1.12
    container_name: crdb
    volumes:
      - crdb_data:/cockroach/cockroach-data
      - ./sql:/docker-entrypoint-initdb.d:ro
    command: start-single-node --insecure
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health?ready=1" ]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'
    ports:
      - "26257:26257"
      - "8082:8080"
      - "8083:8081"

  mailpit:
    image: axllent/mailpit:v1.9.5
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit_data:/data
    environment:
      MP_DATA_FILE: /data/mailpit.db
      TZ: Europe/Berlin
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # Smtp

volumes:
  crdb_data:
  mailpit_data:
```

Place this sql in a directory called `sql` next to the docker-compose.yml. (The name of the sql file it self is irrelevant.)
```sql
CREATE DATABASE IF NOT EXISTS zitadel;
CREATE USER IF NOT EXISTS zitadel with createdb;
GRANT ALL ON DATABASE zitadel to zitadel;
```

Zitadel will fail to start with the error described above, once the `ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST` env is removed it starts, although none of the other SMTP settings are applied.

### Expected behavior

I would expect Zitadel to start and apply the specified SMTP settings.

### Operating System

Device: Mac
OS: macOS 14.1

### Additional Context

Setting the SMTP Settings via the Web Interface works and emails get delivered correctly. (Although it complains that User is required, but lets me save anyway)

**Comment by hifabienne** [comment]
@eliobischof @adlerhurst can you give some inputs here?

**Comment by adlerhurst** [comment]
huhu 

The documentation was wrong.

Please replace the following env vars:

```
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST: "mailpit:1025"
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER: ''
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD: ''
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS: false
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM: zitadel@localhost
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME: Zitadel
```

**Comment by hifabienne** [comment]
I will close this issue, as the problem was wrong docs and they have been fixed now.
Feel free to reopen if you still have problems

**Comment by cloudymax** [comment]
Ran into this as well using the helm chart:
error:
```console
┌─────────────────────────────────────────────────────────────────────────────────────────────────── Logs(zitadel/zitadel-setup-btw54:zitadel-setup)[tail] ────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                              Autoscroll:On      FullScreen:Off     Timestamps:Off     Wrap:Off                                                                                               │
│ time="2024-10-20T15:57:53Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:99"                                                                                                                                  │
│ time="2024-10-20T15:57:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push                                                                                              │
│ time="2024-10-20T15:57:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=01_tables                                                                                                   │
│ time="2024-10-20T15:57:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=02_assets                                                                                                   │
│ time="2024-10-20T15:57:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=28_add_search_table                                                                                         │
│ time="2024-10-20T15:57:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=31_add_aggregate_index_to_fields                                                                            │
│ time="2024-10-20T15:57:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=03_default_instance                                                                                         │
│ time="2024-10-20T15:57:53Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=03_default_instance                                                                                       │
│ time="2024-10-20T15:57:53Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:68" error="ID=INST-9JdRe Message=Errors.Invalid.Argument" name=03_default_instance                                  │
│ time="2024-10-20T15:57:53Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:241" error="ID=INST-9JdRe Message=Errors.Invalid.Argument" name=03_default_instance                                              │
│ Stream closed EOF for zitadel/zitadel-setup-btw54 (zitadel-setup)                                                                                                                                                                                            

```
produced from Values:
```yaml
      source:
        repoURL: https://zitadel.github.io/zitadel-charts
        chart: zitadel
        targetRevision: 8.5.0
        helm:
          releaseName: zitadel
          # https://github.com/zitadel/zitadel-charts/blob/main/charts/zitadel/values.yaml
          valuesObject:
            replicaCount: 1

            env:
              - name: TZ
                value: '{{ .global_time_zone }}'

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: host

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: user

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: password

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS
                value: 'true'

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: from_address

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: from_name

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_REPLYTOADDRESS
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: reply_to_address

              - name: ZITADEL_LOG_LEVEL
                value: info
```

**Comment by jessebot** [comment]
@hifabienne could we please reopen this?

**Comment by cloudymax** [comment]
@hifabienne Hoi 👋 

This issue is still present in 8.12.0.

When trying to install zitadel via Helm and pass in the ENV vars required for setting up SMTP as described in the docs, The DB migration job will fail with the following message:


```console
error="ID=INST-9JdRe Message=Errors.Invalid.Argument" name=03_default_instance
```

Here's what the docs say to use as env vars:

: https://github.com/zitadel/zitadel/blob/4df3b6492ca5b0824ebd8c536e8ad403a1272b58/cmd/defaults.yaml#L991

```yaml
  SMTPConfiguration:
    # Configuration of the host
    SMTP:
      # must include the port, like smtp.mailtrap.io:2525. IPv6 is also supported, like [2001:db8::1]:2525
      Host: # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST
      User: # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER
      Password: # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD
    TLS: # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS
    # If the host of the sender is different from ExternalDomain set DefaultInstance.DomainPolicy.SMTPSenderAddressMatchesInstanceDomain to false
    From: # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM
    FromName: # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME
    ReplyToAddress: # ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_REPLYTOADDRESS
```

Heres what we pass to the helm chart:

```yaml
              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: host

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: user

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: password

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS
                value: 'true'

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: from_address

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: from_name

              - name: ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_REPLYTOADDRESS
                valueFrom:
                  secretKeyRef:
                    name: zitadel-smtp-credentials
                    key: reply_to_address
```

removing the env vars from the helm values allows the setup to proceed as normal, but I'd like to be able to provision the SMTP settings
