### ISSUE TITLE
Support for application_name  in Postgres and CockroachDB Connection

### ISSUE THREAD

**Issue by patrickalima98** [zitadel/zitadel#7051]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

Some cache services and other services that create a proxy/bridge with the database require sending the application_name parameter.

For example, Polyscale a service where add a global cache layer for postgres and cockroachDB databases need a application_name parameter for a database connection:

```sql
postgres://[USERNAME]:[PASSWORD]@psedge.global:5432/[DATABASE]?application_name=xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

### Describe your ideal solution

My suggestion if possible is allow and expose the application_name for config, so we can pass our application_name, something like the others postgres_envs:

```
Database:
  postgres:
    Host: localhost
    Port: 5432
    Database: zitadel
    ApplicationName: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx <--- application_name here
    MaxOpenConns: 25
    MaxIdleConns: 10
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options:
    User:
      Username: zitadel
      Password: zitadel
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:
    Admin:
      Username: postgres
      Password: postgres
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:
  cockroach:
    Host: localhost
    Port: 26257
    Database: zitadel
    ApplicationName: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx <--- application_name here
    MaxOpenConns: 20
    MaxConnLifetime: 30m
    MaxConnIdleTime: 30m
    Options: ""
    User:
      Username: zitadel
      Password: ""
      SSL:
        Mode: disable
        RootCert: ""
        Cert: ""
        Key: ""
    Admin:
      Username: root
      Password: ""
      SSL:
        Mode: disable
        RootCert: ""
        Cert: ""
        Key: ""
```

### Version

2.42.1

### Environment

Self-hosted
