### ISSUE TITLE
[Bug]: No error checking if keys are empty

### ISSUE THREAD

**Issue by ghstahl** [zitadel/zitadel#7206]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.43.4

### Database

PostgreSQL

### Database Version

14

### Describe the problem caused by this bug

This is the handler for the keys endpoint 
```https://zitadel.miab.mapped.dev/oauth/v2/keys```  

```go
func (s *LegacyServer) Keys(ctx context.Context, r *Request[struct{}]) (*Response, error) {
        // HERB: No Keys here
	keys, err := s.provider.Storage().KeySet(ctx)
	if err != nil {
		return nil, NewStatusError(err, http.StatusInternalServerError)
	}
	return NewResponse(jsonWebKeySet(keys)), nil
}

func (o *OPStorage) KeySet(ctx context.Context) (keys []op.Key, err error) {
	ctx, span := tracing.NewSpan(ctx)
	defer func() { span.EndWithError(err) }()
	err = retry(func() error {
               // HERB: No publicKeys here
		publicKeys, err := o.query.ActivePublicKeys(ctx, time.Now())
		if err != nil {
			return err
		}
		keys = make([]op.Key, len(publicKeys.Keys))
		for i, key := range publicKeys.Keys {
			keys[i] = &PublicKey{key}
		}
		return nil
	})
	return keys, err
}
func (q *Queries) ActivePublicKeys(ctx context.Context, t time.Time) (keys *PublicKeys, err error) {
	ctx, span := tracing.NewSpan(ctx)
	defer func() { span.EndWithError(err) }()

	query, scan := preparePublicKeysQuery(ctx, q.client)
	if t.IsZero() {
		t = time.Now()
	}
	stmt, args, err := query.Where(
		sq.And{
			sq.Eq{KeyColInstanceID.identifier(): authz.GetInstance(ctx).InstanceID()},
			sq.Gt{KeyPublicColExpiry.identifier(): t},
		}).ToSql()
	if err != nil {
		return nil, zerrors.ThrowInternal(err, "QUERY-SDFfg", "Errors.Query.SQLStatement")
	}

	err = q.client.QueryContext(ctx, func(rows *sql.Rows) error {
		keys, err = scan(rows)
		return err
	}, stmt, args...)
	if err != nil {
		return nil, zerrors.ThrowInternal(err, "QUERY-Sghn4", "Errors.Internal")
	}

	keys.State, err = q.latestState(ctx, keyTable)
	if !zerrors.IsNotFound(err) {
	       // HERB: No keys here.
		return keys, err
	}
	return keys, nil
}
```

I am getting no keys back and there is no error.
This is an error.    

Will try to hunt down the root cause.

 

### To reproduce

We setup a zitadel instance in docker several months back and saved the db.  When we come up from scratch its already setup.  

My theory is that this will be the base config and zitadel must cleanly migrate from it to the latest.  I also use this as a proof that if I had to restore a dated image of the database it should still work.  

The problem isn't with the latest version, it is there with the original one and things just stopped producing keys.  My hope was that upgrading would generate them again.

zitadel.yaml
```yaml
Port: 9999
ExternalPort: 443
ExternalSecure: true
ExternalDomain: zitadel.miab.mapped.dev

SystemDefaults:
  KeyConfig:
    PrivateKeyLifetime: 8760h
    PublicKeyLifetime: 1080h

Database:
  postgres:
    Host: postgresql
    Port: override_with_env_var
    Database: zitadel
    MaxOpenConns: 25
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options:
    User:
      Username: override_with_env_var
      Password: override_with_env_var
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:
    Admin:
      Username: override_with_env_var
      Password: override_with_env_var
      SSL:
        Mode: disable
        RootCert:
        Cert:
        Key:

TLS:
  # Proxy deals with certificates
  # Cannot use them here because localhost heathcheck is not working with TLS.
  Enabled: false

```

init.yaml
```yaml
# This is used only for initialization.
# Right now zitadel is recovered from backup.
# This config here is for the case if something bad happens
# and we need to start from scratch
FirstInstance:
  MachineKeyPath: /machinekey/zitadel-admin-sa.json
  InstanceName: ZITADEL
  DefaultLanguage: en
  Org:
    Name: ZITADEL
    Machine:
      Machine:
        Username: zitadel-admin-sa
        Name: Admin
      MachineKey:
        Type: 1
```

### Expected behavior

better, I got no keys mitigation.

### Operating System

Docker
