### ISSUE TITLE
WebAuthN doesn't work with example nginx config

### ISSUE THREAD

**Issue by vaminakov** [zitadel/zitadel#7251]
**Edit by @muhlemmer** 

TL;DR: The example [Nginx config](https://zitadel.com/docs/self-hosting/manage/reverseproxy/nginx) rewrites the request `Host` by appending a port. This breaks WebAuthN registration, as the signed origin does not match the actual request origin. This problem seems to present itself using the standard 443 port, instead of the custom 8080 port that the guide assumes.

- If there is a custom port deployment, the port _should_ be set in the `Host` header
- If there is a standard port deployment, the port _should not_ be set in the `Host` header.

Question: why rewrite the host header at all? Why not forward the original Host?

------

**Original issue**

### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Version

2.43.5

### Database

PostgreSQL

### Database Version

16.1

### Describe the problem caused by this bug

There are no possibility to register any webauthn/passkey device in fresh install.

### To reproduce

1.     Create a new instance
2.     Login to the instance with username + password
3.     Go to User setting > Password and security
4.     Click "add method" on passwordless or "add factor" on multifactor
5.     Enter any device name
6.     Get popup error "Error on create credentials" while in zitadel admin or "Errors.User.WebAuthN.CreateCredentialFailed" while in 2fa registration by link.

**Comment by hifabienne** [comment]
Hei @vaminakov 
I quickly checked this myself and didn't have any problems.
Can you please add some more information about your environment?
Which os do you have? What browser do you use?

And I just saw that you say you are on our cloud but you also added db version, so it looks like you are running your own system? So just want to make sure I understand right were you are at

**Comment by vaminakov** [comment]
@hifabienne hello! Sorry for delay in response.
I have own installation (cloud in description is mistake).
I'm tried to debug this problem in OS ArchLinux, Ubuntu 23.10. Browser - latest Chrome and Firefox.
Anywhere problem is reproducing.

As reverse-proxy i'm using nginx with config:
```
location / { 
modsecurity off; 
grpc_pass grpc://localhost:8098; 
grpc_set_header Host $host:$server_port; 
}
```

**Comment by livio-a** [comment]
Hey @vaminakov 

Does your reverse proxy handle TLS? Resp. can you share your configuration of zitadel (ExternalDomain, ExternalPort, ExternalSecure, Port)?

**Comment by vaminakov** [comment]
@livio-a hello! Yes, there're full config:
nginx:

```
server {
server_name zitadel.mydomain;
listen *:443 ssl;
listen [::]:443 ssl;
listen *:443 quic;
listen [::]:443 quic;
ssl_certificate fullchain.pem;
ssl_certificate_key privkey.pem;
ssl_stapling on;
ssl_stapling_verify on;
ssl_stapling_file ocsp.der;
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
add_header Public-Key-Pins 'pin-sha256="mykey"; max-age=63072000';
add_header Alt-Svc 'h3=":443"; ma=86400';
add_header X-protocol $server_protocol always;
location / { 
    grpc_pass grpc://localhost:8098; 
    grpc_set_header Host $host:$server_port; 
               }
}
```
Zitadel:

```
ExternalSecure: true
ExternalDomain: zitadel.mydomain
ExternalPort: 443
Port: 8098
WebAuthNName: zitadel.mydomain
Database:
    postgres:
        Host: localhost
        Port: 5432
        Database: zitadel
        MaxOpenConns: 25
        MaxConnLifetime: 1h
        MaxConnIdleTime: 5m
        Options:
        User:
            Username: zitadel
            Password: secretpass
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key:
        Admin:
            Username: postgres
            Password: secretpass
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key:
LogStore:
  Access:
    Stdout:
      Enabled: true
  Execution:
    Stdout:
      Enabled: true
Log:
  Level: info
  Formatter:
    Format: text
Metrics:
  Type: none
```

Systemd unit:

```
# /etc/systemd/system/zitadel.service
[Unit]
Description=Zitadel IAM
After=postgresql.service

[Service]
RestartSec=2s
Type=simple
User=zitadel
WorkingDirectory=/var/lib/zitadel
Environment=USER=zitadel HOME=/var/lib/zitadel
ExecStart=/usr/bin/zitadel start --config /etc/zitadel/config.yaml --masterkeyFile /etc/zitadel/master.key --tlsMode external
ExecReload=/bin/kill -HUP $MAINPID
KillMode=process
Restart=on-failure

[Install]
WantedBy=multi-user.target
```
