### ISSUE TITLE
Add explicit logs in misconfigured configuration 

### ISSUE THREAD

**Issue by titouan-joseph** [zitadel/zitadel#7582]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I was using the SMTP configuration with docker environment variable, my fisrt attempt is to configure with those vars according to the [documentation](https://zitadel.com/docs/self-hosting/manage/configure) : 

```
ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST: smtp.google.com:587
ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER: username
ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD: verryStrongPassword
ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS:t true
```

And in the log I can see

```
zitadel-1  | time="2024-03-12T21:12:52Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:68" error="ID=INST-mruNY Message=Errors.Invalid.Argument" name=03_default_instance
zitadel-1  | time="2024-03-12T21:12:52Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:206" error="ID=INST-mruNY Message=Errors.Invalid.Argument" name=03_default_instance
```

We can see this log are saying the configuration is not compliant but we don't know which part is wrong  
I removed my SMTP configuration and I was realised the instance is well launched, so I was sure it's the SMTP configuration but I was not undertsdand why.  
I has checked in the Zitadel GUI which parameters are mendatory to setup a SMTP conenction, I found the rights parameters and now I have a working configuration.

### Describe your ideal solution

Add some futher informations on the logs to explain there is missing one parameters

### Version

2.47.4

### Environment

Self-hosted

### Additional Context

[Discord thread](https://discord.com/channels/927474939156643850/1217222627672719423)  

<details>
 <summary>Working docker-compose.yml</summary>

```yaml
version: "3.8"

services:
  zitadel:
    image: ghcr.io/zitadel/zitadel:v2.47.4
    restart: always
    networks:
      - zitadel
      - traefik-public
    command: "start-from-init --masterkeyFromEnv --tlsMode external"
    environment:
      ZITADEL_LOG_LEVEL:
      ZITADEL_MASTERKEY:
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: ${ZITADEL_DATABASE_NAME}
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: ${ZITADEL_DATABASE_USER_USER}
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: ${ZITADEL_DATABASE_USER_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: ${ZITADEL_DATABASE_ADMIN_USER}
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: ${ZITADEL_DATABASE_ADMIN_PASSWORD}
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALPORT: 443
      ZITADEL_EXTERNALSECURE: true
      ZITADEL_TLS_ENABLED: false
      ZITADEL_EXTERNALDOMAIN: zitadel.${DOMAIN}
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME:
      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD:
      ZITADEL_FIRSTINSTANCE_ORG_NAME: 24 heures de l'INSA
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_HOST: ${ZITADEL_SMTP_HOST}
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_USER: ${ZITADEL_SMTP_USER}
#      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROM: ${ZITADEL_SMTP_USER}
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_SMTP_PASSWORD: ${ZITADEL_SMTP_PASSWORD}
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_TLS:
      ZITADEL_DEFAULTINSTANCE_SMTPCONFIGURATION_FROMNAME: zitadel test
    depends_on:
      db:
        condition: "service_healthy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.tls=true"
      - "traefik.http.routers.zitadel.tls.certresolver=le"
      - "traefik.http.routers.zitadel.entrypoints=websecure"
      - "traefik.http.routers.zitadel.rule=Host(`zitadel.${DOMAIN}`)"
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.zitadel.loadbalancer.passHostHeader=true"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name={{.Name}},env=prod,app=zitadel"

  db:
    image: postgres:16.2-alpine
    restart: always
    environment:
      POSTGRES_USER: ${ZITADEL_DATABASE_ADMIN_USER}
      POSTGRES_PASSWORD: ${ZITADEL_DATABASE_ADMIN_PASSWORD}
      POSTGRES_DB: ${ZITADEL_DATABASE_NAME}
    networks:
      - zitadel
    volumes:
      - ./data/zitadel/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: "10s"
      timeout: "30s"
      retries: 5
      start_period: "20s"
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "container_name={{.Name}},env=prod,app=zitadel"

networks:
  traefik-public:
    external: true
  zitadel:
```

</details>

<details>
 <summary>All logs </summary>

```
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:73"
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:39" username=zitadel
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:39" database=zitadel
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:34" database=zitadel user=zitadel
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:78" database=zitadel
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify system" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:39"
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify encryption keys" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:44"
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify projections" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:49"
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify eventstore" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:54"
zitadel-1  | time="2024-03-13T07:29:48Z" level=info msg="verify events tables" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:59"
zitadel-1  | time="2024-03-13T07:29:49Z" level=info msg="verify system sequence" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:64"
zitadel-1  | time="2024-03-13T07:29:49Z" level=info msg="verify unique constraints" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:69"
zitadel-1  | time="2024-03-13T07:29:49Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:90"
zitadel-1  | time="2024-03-13T07:29:49Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
zitadel-1  | time="2024-03-13T07:29:49Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=14_events_pushzitadel-1  | time="2024-03-13T07:29:49Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=01_tables
zitadel-1  | time="2024-03-13T07:29:49Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=01_tables
zitadel-1  | time="2024-03-13T07:29:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=02_assets
zitadel-1  | time="2024-03-13T07:29:53Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=02_assets
zitadel-1  | time="2024-03-13T07:29:53Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=03_default_instance
zitadel-1  | time="2024-03-13T07:29:53Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=03_default_instance
zitadel-1  | time="2024-03-13T07:29:53Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:68" error="ID=INST-mruNY Message=Errors.Invalid.Argument" name=03_default_instance
zitadel-1  | time="2024-03-13T07:29:53Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:206" error="ID=INST-mruNY Message=Errors.Invalid.Argument" name=03_default_instance
```

<details>
