### ISSUE TITLE
[Bug]: `/oauth/v2/keys` returns `{"keys": []}` causing id token verification failures

### ISSUE THREAD

**Issue by jeffmccune** [zitadel/zitadel#7714]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.49.1

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

When I configure a long expiration time for public and private signing keys by setting `PrivateKeyLifetime: 999999h` and `PublicKeyLifetime: 999999h` in the [zitadel config file](https://github.com/zitadel/zitadel/blob/v2.49.1/cmd/defaults.yaml#L502-L503), the keys endpoint returns no keys which breaks verification for all clients.

My goal is to configure the proposed solution described in [Improve OIDC key management](https://github.com/zitadel/zitadel/discussions/7464)

```
curl https://login.example.com/oauth/v2/keys
```

No signing keys are returned.  This breaks login on all services integrated with ZITADEL.

```json
{"keys": []}
```

NOTE: Login via the ZITADEL web UI works at least, so I can access https://login.example.com/ui/console/users/me

### To reproduce

Configure zitadel using the following ConfigMap (Note the KeyConfig) per this discord discussion: [Jwks doesn't have key to match kid or alg from Jwt](https://discord.com/channels/927474939156643850/1225864407779901501)

> `ffo`
> I think you need to change these values https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml#L508 and then restart zitadel to pick them up

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-config-yaml
data:
  zitadel-config-yaml: |2-
    Database:
      postgres:
        Admin:
          SSL:
            Mode: verify-full
        MaxConnIdleTime: 5m
        MaxConnLifetime: 1h
        MaxIdleConns: 10
        MaxOpenConns: 25
        User:
          SSL:
            Mode: verify-full
    ExternalDomain: login.example.com
    ExternalPort: 443
    ExternalSecure: true
    Machine:
      Identification:
        Hostname:
          Enabled: true
        Webhook:
          Enabled: false
    SystemDefaults:
      KeyConfig:
        PrivateKeyLifetime: 999999h
        PublicKeyLifetime: 999999h
    TLS:
      Enabled: false
```

### Expected behavior

When `PrivateKeyLifetime: 999999h` and `PublicKeyLifetime: 999999h` I expect `/oauth/v2/keys` to always return at least one active signing key.

### Relevant Configuration

https://github.com/zitadel/zitadel/blob/main/cmd/defaults.yaml#L508-L509
