### ISSUE TITLE
[Bug]: Error when passing ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ALGORITHM=pbkdf2 as environment variable

### ISSUE THREAD

**Issue by buzzie-bee** [zitadel/zitadel#7789]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.50.1

### Database

PostgreSQL

### Database Version

v16.1

### Describe the problem caused by this bug

Zitadel fails to start when pbkdf2 hasher options are set via environment variables.

### To reproduce

Create a docker compose zitadel definition with db connections etc.

Add the following environment variables:

```
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ALGORITHM=pbkdf2' 
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ROUNDS=290000' 
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_HASH=sha256' 
```

Try to run docker compose up.

See the following error logged to the console:

```
nn-zitadel  | time="2024-04-17T14:20:50Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:68" error="password hasher: ID=CRYPT-Que4r Message=password hash config invalid Parent=(decode pbkdf2 params: 1 error(s) decoding:\n\n* '' has unset fields: Hash, Rounds)" name=03_default_instance
nn-zitadel  | time="2024-04-17T14:20:51Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:210" error="password hasher: ID=CRYPT-Que4r Message=password hash config invalid Parent=(decode pbkdf2 params: 1 error(s) decoding:\n\n* '' has unset fields: Hash, Rounds)" name=03_default_instance
nn-zitadel exited with code 0
```

### Expected behavior

I would expect that passing in valid rounds and hash arguments would not throw an error stating that rounds and hash arguments are required.

### Operating System

OS: Ubuntu 20.04.6 LTS x86_64 
Host: 20ST001CGE ThinkPad P15 Gen 1 
Kernel: 5.15.0-102-generic 

### Relevant Configuration

A stripped down version of my docker-compose file. You'll likely need to replace the db config with your own.

```yaml
version: '3.8'

volumes:
  nn-db:
    name: nn-db

services:
  nn-db:
    container_name: nn-db
    image: postgres:16
    shm_size: 1gb
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${NN_POSTGRES_DB}
      - POSTGRES_HOST=${NN_POSTGRES_HOST}
      - POSTGRES_USER=${NN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NN_POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${NN_POSTGRES_SCHEMA}
    ports:
      - ${NN_POSTGRES_PORT}:${NN_POSTGRES_PORT}
    volumes:
      - nn-db:/var/lib/postgresql/data
    networks:
      - nn-backend-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '$NN_POSTGRES_USER']
      interval: 5s
      timeout: 5s
      retries: 5

  nn-zitadel:
    container_name: nn-zitadel
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=nn-db'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_EXTERNALSECURE=false'
      - 'ZITADEL_PORT=8080'
      - 'ZITADEL_EXTERNALPORT=8081'

      - 'ZITADEL_DEFAULTINSTANCE_ORG_NAME=MatterHive'

      - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_USERNAME=zitadel-admin' #UserName: zitadel-admin # ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_USERNAME
      - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED=true' #  Verified: false # ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED
      - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_PREFERREDLANGUAGE=en' #PreferredLanguage: en # ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_PREFERREDLANGUAGE

      # attempt to get pbkdf2 imports working on the v2beta endpoint
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ALGORITHM=pbkdf2' 
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_ROUNDS=290000' 
      - 'ZITADEL_SYSTEMDEFAULTS_PASSWORDHASHER_HASHER_HASH=sha256' 
    restart: unless-stopped
    ports:
      - '8081:8080'
    networks:
      - nn-backend-network
    depends_on:
      nn-db:
        condition: 'service_healthy'

  nn-openfga-migrate:
    depends_on:
      nn-db:
        condition: service_healthy
    image: openfga/openfga:latest
    container_name: nn-openfga-migrate
    command: migrate
    env_file:
      - ./.env
    environment:
      - OPENFGA_DATASTORE_ENGINE=postgres
      - OPENFGA_DATASTORE_URI=${NN_OPENFGA_DATASTORE_URI}
    networks:
      - nn-backend-network

networks:
  nn-backend-network:
    name: nn-backend-network

```
