### ISSUE TITLE
USER-JDk4t error when calling v2beta human user import

### ISSUE THREAD

**Issue by buzzie-bee** [zitadel/zitadel#7793]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.50.1

### Database

PostgreSQL

### Database Version

v16.1

### Describe the problem caused by this bug

I am attempting migrate our data from keycloak into Zitadel and wanted to use the v2beta human user import endpoint as it has more functionality such as adding metadata when importing the user.

Unfortunately this error is thrown when I attempt to do a post to v2beta/users/human:
```
{
  code: 3,
  message: 'Password hash encoding not supported (USER-JDk4t)',
  details: [
    {
      '@type': 'type.googleapis.com/zitadel.v1.ErrorDetail',
      id: 'USER-JDk4t',
      message: 'Password hash encoding not supported'
    }
  ]
}
```
I am following the steps to do the keycloak migration found in the [documentation](https://zitadel.com/docs/guides/migrate/sources/keycloak), but as the v2beta human import route takes in a differently shaped object I also do some mapping to convert the zitadel-tools output into a v2beta import format.

Here is the user I'm attempting to import:
```js
const res = await fetch(`${ZITADEL_DOMAIN}/v2beta/users/human`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${ZITADEL_SERVICE_USER_ACCESS_TOKEN}`,
    },
    body: JSON.stringify({
      userId: '13c45e05-83c0-4732-8047-940bcf9da4ef',
      profile: {
        givenName: 'Bonnie',
        familyName: 'Em',
      },
      email: {
        email: 'testone@test.com',
        isEmailVerified: true,
      },
      hashedPassword: {
        hash: '$pbkdf2-sha256$27500$i0VOYMZPRzCZoJHtQqssEQ==$1BnCbQ7q6OYC/qI8xSOAYEBSUmh8ZqwcOo1ABqI2PiA=',
        changeRequired: false,
      },
    }),
  });
  ```
  
  The same hash value works on the v1 human user import, and looking at the docs for passwap it also looks correct, so I don't think the error being thrown is actually the problem. I even attempted to use the hash from the passwap examples/tests but that threw an error also. 

### To reproduce

1. Spin up a zitadel instance
2. Create a machine service account with the 'Org User Manager' role
3. Create a secret key for that machine service account
4. Make the following POST request, changing the ZITADEL_DOMAIN and ZITADEL_SERVICE_USER_ACCESS_TOKEN to your own values. This example is sent via node, but any other method will be fine too.

```
const res = await fetch(`${ZITADEL_DOMAIN}/v2beta/users/human`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${ZITADEL_SERVICE_USER_ACCESS_TOKEN}`,
    },
    body: JSON.stringify({
      userId: '13c45e05-83c0-4732-8047-940bcf9da4ef',
      profile: {
        givenName: 'Bonnie',
        familyName: 'Em',
      },
      email: {
        email: 'testone@test.com',
        isEmailVerified: true,
      },
      hashedPassword: {
        hash: '$pbkdf2-sha256$27500$i0VOYMZPRzCZoJHtQqssEQ==$1BnCbQ7q6OYC/qI8xSOAYEBSUmh8ZqwcOo1ABqI2PiA=',
        changeRequired: false,
      },
    }),
  });
```

5. Observe the following error in the response:
```
{
  code: 3,
  message: 'Password hash encoding not supported (USER-JDk4t)',
  details: [
    {
      '@type': 'type.googleapis.com/zitadel.v1.ErrorDetail',
      id: 'USER-JDk4t',
      message: 'Password hash encoding not supported'
    }
  ]
}
```

### Expected behavior

I expect the pbkdf2 hash format to work with human user import on the v2beta endpoints like the docs say it will and like the v1 endpoints.

### Operating System

OS: Ubuntu 20.04.6 LTS x86_64
Host: 20ST001CGE ThinkPad P15 Gen 1
Kernel: 5.15.0-102-generic

### Relevant Configuration

I think I have a fairly normal zitadel set up, but here's my docker compose with the other services stripped out:

```yaml
version: '3.8'

volumes:
  nn-db:
    name: nn-db

services:
  nn-db:
    container_name: nn-db
    image: postgres:16
    shm_size: 1gb
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${NN_POSTGRES_DB}
      - POSTGRES_HOST=${NN_POSTGRES_HOST}
      - POSTGRES_USER=${NN_POSTGRES_USER}
      - POSTGRES_PASSWORD=${NN_POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${NN_POSTGRES_SCHEMA}
    ports:
      - ${NN_POSTGRES_PORT}:${NN_POSTGRES_PORT}
    volumes:
      - nn-db:/var/lib/postgresql/data
    networks:
      - nn-backend-network
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '$NN_POSTGRES_USER']
      interval: 5s
      timeout: 5s
      retries: 5

  nn-zitadel:
    container_name: nn-zitadel
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=nn-db'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_EXTERNALSECURE=false'
      - 'ZITADEL_PORT=8080'
      - 'ZITADEL_EXTERNALPORT=8081'

      - 'ZITADEL_DEFAULTINSTANCE_ORG_NAME=MatterHive'

      - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_USERNAME=zitadel-admin' #UserName: zitadel-admin # ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_USERNAME
      - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED=true' #  Verified: false # ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_EMAIL_VERIFIED
      - 'ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_PREFERREDLANGUAGE=en' #PreferredLanguage: en # ZITADEL_DEFAULTINSTANCE_ORG_HUMAN_PREFERREDLANGUAGE

    restart: unless-stopped
    ports:
      - '8081:8080'
    networks:
      - nn-backend-network
    depends_on:
      nn-db:
        condition: 'service_healthy'

networks:
  nn-backend-network:
    name: nn-backend-network

```
