### ISSUE TITLE
[Bug]: Can't login as machine user

### ISSUE THREAD

**Issue by montycb** [zitadel/zitadel#7804]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.50.2

### Database

PostgreSQL

### Database Version

16

### Describe the problem caused by this bug

I've configured a self-hosted ZITADEL Instance, running behind a Caddy Proxy. I'm attempting to login from a Node.js application into ZITADEL, utilizing the library provided on the official ZITADEL website. Despite my efforts, ZITADEL consistently denies authentication requests. Notably, the user in question is designated as "Iam Owner."

### To reproduce

This is the code I'm using in my Node.JS application:

```ts
zitadelServiceAccount = ServiceAccount.fromJson({
  userId: ***,
  key: ***,
  keyId: ***
})

const interceptor = createServiceAccountInterceptor(SERVER, zitadelServiceAccount, { apiAccess: true })
managementClient = createManagementClient('https://***.cloud', interceptor)
```

If I set SERVER to "https://***.cloud" the authentication fails with the following error:
`issuer does not match: Expected: https://***.cloud:443, got: https://***.cloud`

If I set SERVER to "https://***.cloud:443" i receive a different error:
`Audience must contain client_id \"https://***.cloud\""`

### Operating System

Linux / Node.JS v20

### Relevant Configuration

ZITADEL
```
ExternalSecure: true
ExternalDomain: '***.cloud'
ExternalPort: 443

TLS:
  Enabled: false

Database:
    postgres:
        Host: localhost
        Port: 5432
        Database: zitadel
        MaxOpenConns: 25
        MaxConnLifetime: 1h
        MaxConnIdleTime: 5m
        Options:
        User:
            Username: zitadel
            Password: ***
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key:
        Admin:
            Username: postgres
            Password: ***
            SSL:
                Mode: disable
                RootCert:
                Cert:
                Key:
```

Caddy
```
https://***.cloud {
        reverse_proxy h2c://localhost:8080
}
```
