### ISSUE TITLE
Invalid comment on self-hosting loadbalancing-example

### ISSUE THREAD

**Issue by Yberion** [zitadel/zitadel#7842]
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe the docs your are missing or that are wrong

- https://zitadel.com/docs/self-hosting/deploy/loadbalancing-example

In the file `example-zitadel-config.yaml`, there's a wrong comment:

```yml
# Make ZITADEL accessible over HTTP, not HTTPS
ExternalSecure: true
ExternalDomain: my.domain
ExternalPort: 443
```

Shouldn't it be the following ?

```yml
# Make ZITADEL accessible over HTTPS, not HTTP
ExternalSecure: true
ExternalDomain: my.domain
ExternalPort: 443
```
