### ISSUE TITLE
[Bug]:  @zitadel/node does not work when zitadel is behind caddy or traefik.

### ISSUE THREAD

**Issue by philkunz** [zitadel/zitadel#7889]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

latest

### Database

None

### Describe the problem caused by this bug

ClientError: /zitadel.auth.v1.AuthService/GetMyUser INTERNAL: Received RST_STREAM with code 0

When reverse proxy like traefik or caddy is used with https enabled. (UI works fine, valid letsencrypt cert)

### To reproduce

Use zitadel behind a traefik or caddy reverse proxy, use @zitadel/node

**Comment by philkunz** [comment]
Here is the docker-compose.yml

```
version: '3.8'

services:
  zitadel:
    restart: 'always'
    networks:
      - zitadel
    image: 'ghcr.io/zitadel/zitadel:v2.50.5'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode external'
    environment:
      - 'ZITADEL_DATABASE_POSTGRES_HOST=db'
      - 'ZITADEL_DATABASE_POSTGRES_PORT=5432'
      - 'ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel'
      - 'ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres'
      - 'ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable'
      - 'ZITADEL_EXTERNALPORT=443'
      - 'ZITADEL_EXTERNALSECURE=true'
      - 'ZITADEL_TLS_ENABLED=false'
      - 'ZITADEL_EXTERNALDOMAIN=my.domain.here'
    depends_on:
      db:
        condition: 'service_healthy'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zitadel.rule=Host(`my.domain.here`)"
      - "traefik.http.routers.zitadel.entrypoints=websecure"
      - "traefik.http.routers.zitadel.tls.certresolver=myresolver"
      - "traefik.http.services.zitadel.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.zitadel.loadbalancer.server.port=8080"

  db:
    restart: 'always'
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - zitadel
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: '10s'
      timeout: '30s'
      retries: 5
      start_period: '20s'

  traefik:
    image: "traefik:v2.5"
    restart: 'always'
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.myresolver.acme.email=myname@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
    environment:
      CLOUDFLARE_DNS_API_TOKEN: "[CF_KEY_HERE]"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/traefik/acme.json:/acme.json"
    networks:
      - zitadel

networks:
  zitadel:

volumes:
  traefik_data:
```
