### ISSUE TITLE
[Bug]: Can't login via ZITADEL using oauth2-proxy when enabling proxy-protocol. Runs in kubernetes with ingress-nginx 

### ISSUE THREAD

**Issue by samtoxie** [zitadel/zitadel#8024]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.51.4

### Database

PostgreSQL

### Describe the problem caused by this bug

We have a setup where we run a flux managed kubernetes cluster on an OpenStack cloud. We use OpenStack Octavia loadbalancer to expose our ingress (`ingress-nginx`). Behind this we run various services such as zitadel and oauth2-proxy. Currently we do not use proxy-protocol, which means we dont have access to the client IP. When we do enable proxy-protocol, everything runs perfectly except for oauth2-proxy with ZITADEL. When we try to use oauth2-proxy with ZITADEL login we get the following error in our ZITADEL logs:

```
time="2024-05-28T11:12:01Z" level=error caller="/home/runner/work/zitadel/zitadel/internal/api/ui/login/renderer.go:345" error="ID=EVENT-adk13 Message=Errors.AuthRequest.UserAgentNotCorresponding"
```

and this in the oauth2-proxy logs:

```
[2024/05/28 11:12:00] [oauthproxy.go:1017] No valid authentication in request. Initiating login.
MY_IP - 8103a4fb76372ba297dd2ed464b67015 - - [2024/05/28 11:12:00] sso.redacted.tld GET - "/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0" 302 420 0.001
[2024/05/28 11:12:00] [oauthproxy.go:881] Error redeeming code during OAuth2 callback: token exchange failed: Post "https://identity.redacted.tld/oauth/v2/token": read tcp 100.96.3.68:34844->LOAD_BALANCER_IP:443: read: connection reset by peer
```

Weirdly, this only happens when logging into an app via oauth/oidc. Logging into zitadel itself works perfectly fine. When we disable proxy-protocol, we can login again like before and the issue is gone.

The following config is used for deploying ZITADEL:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: zitadel
  namespace: identity
spec:
  interval: 2h
  chart:
    spec:
      chart: zitadel
      sourceRef: 
        kind: HelmRepository
        name: zitadel
        namespace: identity
      interval: 2h
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  - name: ingress-nginx
    namespace: ingress-nginx
  - name: cloudnative-pg
    namespace: cloudnative-pg
  values:
    ingress:
      enabled: true
      className: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod-http"
      hosts:
        - host: identity.redacted.tld
          paths:
            - path: /
              pathType: Prefix
      tls: 
        - secretName: zitadel-tls
          hosts:
          - identity.redacted.tld
    replicaCount: 3
    image:
      repository: ghcr.io/zitadel/zitadel
      tag: "v2.51.4"
    zitadel:
      masterkeySecretName: zitadel-secrets
      configmapConfig:
        ExternalSecure: true
        ExternalPort: 443
        ExternalDomain: identity.redacted.tld
        TLS:
          Enabled: false
        Log:
          Level: 'info'
        Database:
          Postgres:
            Host: zitadel-rw.cloudnative-pg
            Port: 5432
            Database: zitadel
            MaxOpenConns: 20
            MaxIdleConns: 10
            MaxConnLifetime: 30m
            MaxConnIdleTime: 5m
            User:
              SSL:
                Mode: disable
            Admin:
              SSL:
                Mode: disable
    env:
    - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
      valueFrom:
        secretKeyRef:
          name: pg-zitadel-user
          key: username
    - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pg-zitadel-user
          key: password
    - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
      valueFrom:
        secretKeyRef:
          name: pg-superuser
          key: username
    - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pg-superuser
          key: password
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        honorLabels: false
        honorTimestamps: true
```

And our ingress config:

```yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
      version: 4.10.1
  dependsOn:
  - name: cert-manager
    namespace: cert-manager
  interval: 60m
  values:
    controller:
      allowSnippetAnnotations: true
      replicaCount: 2
      service:
        type: LoadBalancer
        loadBalancerIP: LOADBALANCER_IP
        externalTrafficPolicy: "Local"
        annotations:
          loadbalancer.openstack.org/proxy-protocol: "true"
          loadbalancer.openstack.org/keep-floatingip: "true"
      metrics:
        enabled: true
        serviceMonitor:
          additionalLabels:
            release: prometheus
          enabled: true
      config:
        use-proxy-protocol: true
        use-forwarded-headers: true
```

Currently I'm not sure how to proceed. I also changed log level to debug, however this did not give me any extra information. If anyone here has some suggestions, its highly appreciated!

### To reproduce

1. Enable proxy-protocol on the ingress and loadbalancer of a kubernetes cluster
