### ISSUE TITLE
[Bug]: zitadel ready command does not override default config parameters, causing the health check to fail.

### ISSUE THREAD

**Issue by everesio** [zitadel/zitadel#8106]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.54.1

### Database

PostgreSQL

### Database Version

16-alpine

### Describe the problem caused by this bug

zitadel config sets following parameters

```
ExternalPort: 9080
ExternalSecure: false
```
docker compose healthcheck is used as

```
healthcheck:
  test: ["CMD", "/app/zitadel", "ready", "--config", "/zitadel.yaml" ]
  interval: '10s'
  timeout: '5s'
  retries: 5
  start_period: '10s'
``` 

this healthcheck fails as default port 8080 and proto http is used (value are not overwritten)

```
Get \"https://localhost:8080/debug/ready\": http: server gave HTTP response to HTTPS client
``` 

### To reproduce

config zitadel.yaml

```
Log:
  Level: 'info'

ExternalPort: 9080
ExternalSecure: false
```

docker compose

``` 
services:
  zitadel:
    restart: always
    container_name: zitadel
    image: "ghcr.io/zitadel/zitadel:v2.54.1"
    command: 'start-from-init --config /zitadel.yaml --steps /zitadel.yaml --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    ports:
      - "9080:8080"
    volumes:
      - ./zitadel.yaml:/zitadel.yaml:ro
    healthcheck:
      test: ["CMD", "/app/zitadel", "ready", "--config", "/zitadel.yaml" ]
      interval: '10s'
      timeout: '5s'
      retries: 5
      start_period: '10s'
    depends_on:
      db:
        condition: 'service_healthy'
  db:
    image: postgres:16-alpine
    restart: always
    container_name: zitadel-postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
```
after started

``` 
docker inspect --format "{{json .State.Health }}" zitadel | jq '.Log[].Output'
docker exec -it zitadel /app/zitadel ready --config /zitadel.yaml
```
