### ISSUE TITLE
[Bug]: /ui/console/ requests /.well-known/openid-configuration from http, ignoring https

### ISSUE THREAD

**Issue by terion-name** [zitadel/zitadel#8440]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.58.3

### Database

PostgreSQL

### Describe the problem caused by this bug

Installed on my domain via docker compose (see below), set up custom domain with https. Added settings:
```
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALDOMAIN=zitadel-test.my.domain
      - ZITADEL_EXTERNALPORT=443
```

Console UI opens but breaks because host is on https, but it tries to load `/.well-known/openid-configuration`, which is obviously not allowed with CPP (the file itself is present and can be opened separately). I didn't find any other settings on this regard to enforce https

### To reproduce

```yaml
version: '3.8'
services:
  zitadel:
    restart: always
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled'
    environment:
      - ZITADEL_DATABASE_POSTGRES_HOST=db
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALDOMAIN=zitadel-test.my.domain
      - ZITADEL_EXTERNALPORT=443
    depends_on:
      db:
        condition: service_healthy
  db:
    restart: always
    image: 'postgres:16-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=zitadel
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready
        - '-d'
        - zitadel
        - '-U'
        - postgres
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s

```

### Screenshots

<img width="798" alt="Снимок экрана 2024-08-15 в 19 38 53" src="https://github.com/user-attachments/assets/45d31731-97b5-47e4-b3a1-5c43d8e2141b">

### Expected behavior

all assets are requested via https

**Comment by terion-name** [comment]
ah, sorry, overlooked this:
```
command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode external'
```

Really this should be mentioned in docs https://zitadel.com/docs/self-hosting/manage/custom-domain

**Comment by AdamJSoftware** [comment]
I am experiencing this issue with helm. I have set externalSecure to true but it still seems to want to use http.

My config:
```yaml
configSecretKey: config.yaml
  configSecretName: zitadel-secrets
  configmapConfig:
    ExternalSecure: true
    Machine:
      Identification:
        Hostname:
          Enabled: true
        Webhook:
          Enabled: false
    Database:
      Postgres:
        Admin:
          SSL:
            Mode: verify-full
          Username: postgres
        Database: zitadel
        Host: db-postgresql
        MaxConnIdleTime: 5m
        MaxConnLifetime: 30m
        MaxIdleConns: 10
        MaxOpenConns: 20
        Port: 5432
        User:
          SSL:
            Mode: verify-full
          Username: zitadel
    ExternalDomain: zitadel.redacted.tld
    ExternalPort: 443
    TLS:
      Enabled: false
  dbSslAdminCrtSecret: postgres-cert
  dbSslCaCrt: ''
  dbSslCaCrtSecret: postgres-cert
  dbSslUserCrtSecret: zitadel-cert
```

Any ideas why?
