### ISSUE TITLE
[Bug]: multiple reports of broken pbkdf2 imports

### ISSUE THREAD

**Issue by muhlemmer** [zitadel/zitadel#8491]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

ZITADEL Cloud

### Database

None

### Describe the problem caused by this bug

There are multiple reports on Discord about pbkdf2-sha256 imports that seem to be broken.

- ~~https://discord.com/channels/927474939156643850/1274106780493942876~~ -> was solved by config update
- https://discord.com/channels/927474939156643850/1272475641815760968

### To reproduce

1. Create an encoded hash with either external system:
  a. https://www.dcode.fr/pbkdf2-hash
  b. Export a user from Keycloack and format the password data into MCF.
2. Import human user (v1) into zitadel
3. Login the user -> password does not match

Note: This is taken from Discord, I didn't have time to verify this yet.

### Expected behavior

Password verification to work after import.

**Comment by schettn** [comment]
# Passlib pbkdf2 on ZITADEL CLOUD

This is how I reproduced this on ZITADEL cloud:

1. Generate a pbkdf2 hash (passlib)
![image](https://github.com/user-attachments/assets/ccb70187-b197-45a9-99da-26d3739e9d6f)

2. Create a new user
```python
import requests
import json

url = "https://test-aaaaaaaa.zitadel.cloud/management/v1/users/human/_import"

payload = json.dumps({
    "userName": "minnie-mouse",
    "profile": {
        "firstName": "Minnie",
        "lastName": "Mouse",
        "nickName": "Mini",
        "displayName": "Minnie Mouse",
        "preferredLanguage": "en",
        "gender": "GENDER_FEMALE"
    },
    "email": {
        "email": "minnie@mouse.com",
        "isEmailVerified": True
    },
    "hashedPassword": {
        "value": "$pbkdf2-sha256$100000$HpJaQbdgPJRVPbF9$kgm3QtMNYC9o0.O161N5PDszcMGcHfC2HdVXvokJkTs="
    },

})
headers = {
    'Content-Type': 'application/json',
    'Accept': 'application/json',
    'Authorization': 'Bearer xxxxx'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

3. Try to login
![image-3](https://github.com/user-attachments/assets/f493d93c-cb74-48a6-975f-cd6df10994c4)

**Comment by schettn** [comment]
# Django pbkdf2 on self hosted (verifier is enabled)

I tried the same on a self hosted instance but instead I use a Django pbkdf2 hash.

Example: `pbkdf2_sha256$100000$eWZncb8EO0lM$HddIrL/Yuvg91JrroQWqLk4kIJRzD25olN2+0UM8MoQ=` 

1. Issue: [zitadel/passwap](https://github.com/zitadel/passwap) does not support the Django format. Ref: https://github.com/zitadel/passwap/blob/f5db27927d9f56e11b3161cf12a8ad08db81fedd/pbkdf2/pbkdf2.go#L27. This leads to a "internal server error" when logging in.
2. Issue: Just updating the format from `pbkdf2_sha256$100000$eWZncb8EO0lM$HddIrL/Yuvg91JrroQWqLk4kIJRzD25olN2+0UM8MoQ=` to `pbkdf2-sha256$100000$eWZncb8EO0lM$HddIrL/Yuvg91JrroQWqLk4kIJRzD25olN2+0UM8MoQ=` results in a `password incorrect` when logging in.

**Comment by muhlemmer** [comment]
>Maybe the pbkdf2 verifier is not enabled on cloud?

It is: 

```yaml
  PasswordHasher:
    # Set hasher configuration for user passwords.
    # Passwords previously hashed with a different algorithm
    # or cost are automatically re-hashed using this config,
    # upon password validation or update.
    Hasher:
      Algorithm: "bcrypt"
      Cost: 12
    Verifiers:
      - "bcrypt"
      - "md5"
      - "scrypt"
      - "pbkdf2"
  ```
