### ISSUE TITLE
Translation and Custom Texts

### ISSUE THREAD

**Issue by hifabienne** [zitadel/zitadel#8608]

**Comment by adlerhurst** [comment]
# Proposal translation / error handling

Currently zitadel has an unstructured error and translation handling. The goal of this comment is to 

- first clarify the difference between error handling and translations
- describe the use cases
- describe which actor is responsible for which step in the process of showing messages to the customer

## Definition

### Translation

Used to represent an end user facing text in their preferred language.

### Error

Representation of what went wrong in which step of a process. The error is always returned to a client and never directly to the end user.

Validations are a special case which could be shown to the user directly if the app is a frontend.

An error can have a cause.

Details about the occurred error must be found in the documentation.

### Difference between translation and error

Translations are always returned to the end user, errors on the other hand are returned to some piece of logic, either business logic or and api client.

The keyset of translations is defined by the client, e.g. console or login ui. The keyset of errors is defined by the creator of the error.

Translations are for end users, errors are for IT personnel. Translations rewrite some cause to make it understandable for the end user whereas an error is a details description of the cause.

### Key

Is a unique identifier for either a translation or an error.

### Keyset

The schema used to load and store keys

### Summary

Translations and errors are different citizens in the software development lifecycle. Both are important but for different actors like described in the difference paragraph.

ZITADEL must fulfill the needs for end users (which use a UI) as well IT personnel (which use the APIs or low level clients like zitadel-go).

## Known actors

### Frontend apps provided by ZITADEL

Frontend apps present texts to an end user.

A list of applications (or parts) which are visible to the end user. 

- Login UI
- Console
- Notifications
  - SMS
  - Email

### Backend apps provided by ZITADEL

Backend apps never return texts to end user. They either return a successful message or an error which might include the cause.

A list of applications (or parts) which provide an API.

- Management API
- OIDC
- SAML
- OAuth
- Notifications
  - HTTP endpoint
- Actions

### Multi tenancy

#### System admins

Want to provide basic translations

#### Instance admins

Want to provide translations for the employees and customers

#### Org admin

Wants to add or overwrite transitions or add missing ones for their users.

## What does that mean om the future?

### Frontend

- Manges a keyset for multiple languages and instances / organizations
- Minimal translations are compiled so that we can always provide a backup
- An operator must be able to configure where and how to load translations
  - mount a folder/file
  - i18n endpoint?
  - s3 endpoint?
- Must be able to interpret errors returned for the backend and translate correspondingly

### Backend

- The functionality is reduced to return errors and at most a default description of the error. Personally I would prefer to return a link to the docs to lookup the error instead of a default description.
- The backend must make sure to return an error identifier exactly once
- TODO: should we always return the cause?
  - If yes we need to hide some information like sql errors
- Provides an API to load and store translations
- If we start working of the error handling we might also include a logging strategy

**Comment by eliobischof** [comment]
Here is my proposal for managing custom i18n.

# Dynamic Language Support

A self hoster configures text sources for supported languages in the defaults.yaml, which looks similar to this:
```yaml
I18n:
  CustomFilesBucketURI: "file://" # To implement this and support other schemes, we use the gocloud library  https://gocloud.dev/howto/blob/
  DefaultLanguage: "en"
  DefaultTranslations:
  - IsoCode: "en"
    URI: https://raw.githubusercontent.com/zitadel/zitadel-i18n-defaults/v1.0.0/en.yaml
  - IsoCode: "it"
    URI: https://raw.githubusercontent.com/zitadel/zitadel-i18n-defaults/v1.0.0/it.yaml
  - IsoCode: "fr" # ...and all other language files we currently have in the core
  - IsoCode: "en"
    URI: https://raw.githubusercontent.com/zitadel/typescript/main/i18n-defaults/en.yaml
```

ZITADEL queries the default sources on startup, merges the same languages together and holds them in-memory as supported languages or "system" languages as we know them. The DefaultLanguages yaml is unmarshalled into an internal struct holding all i18n key paths that the core needs. This fails if the default language misses translations. Wherever an i18n key is needed in the core, it is read from that struct.

# Multitenancy

ZITADEL exposes [a settings API](https://zitadel.com/docs/apis/v3#settings-services) for custom instance and org translations.

*SetLanguages* accepts a request context (instance, org), a language iso code and a plain yaml string. The yaml is used to create an object at {{ .I18n.CustomFilesBucketURI }}/{{ .InstanceID }}/{{ .OrgId }}/{{ .LanguageIsoCode }}.yaml. If the object already exists, the yamls are merged together and the object is replaced. No events are produced.

*GetLanguages* accepts a language and field mask. It returns the yaml at the field mask path twice: once the custom values at {{ .I18n.CustomFilesBucketURI }}/{{ .InstanceID }}/{{ .OrgId }}/{{ .LanguageIsoCode }}.yaml, once the yaml with resolved values from the hierarchy.

Open questions:
How do we retrieve the values in a performant way?
Should we hold resolved translations per "active org" in-memory and invalidate this in-memory cache when new languages are set and/or by last used time?

# Templating

If a yaml value has template variables, ZITADEL tries to resolve them using request context data.
