### ISSUE TITLE
[Bug]: HTTP is used to retrieve OpenID discovery document with `ExternalSecure` to to `true`

### ISSUE THREAD

**Issue by xadhatter** [zitadel/zitadel#8675]
### Preflight Checklist

- [X] I could not find a solution in the documentation, the existing issues or discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.62.1

### Database

CockroachDB

### Database Version

v24.2.0

### Describe the problem caused by this bug

After installation I am unable to access the UI console. An error occurs because the webapp uses a plain http connection to retrieve the openid configuration, even with `ExternalSecure` to to `true`.

```
Wait!
Inserting something here could give attackers access to your zitadel account.
If you don't know exactly what you're doing, close the window and stay on the safe side
If you know exactly what you are doing, you should work for us

Refused to connect to 'http://my.domain/.well-known/openid-configuration' because it violates the following Content Security Policy directive: "connect-src 'self' my.domain".

error loading discovery document 
T {headers: k, status: 0, statusText: 'Unknown Error', url: 'http://my.domain/.well-known/openid-configuration', ok: false, …}
```

### To reproduce

1. Install Zitadel using Helm (see values.yaml, below)
2. Use Traefik as reverse proxy
3. Use `ExternalDomain` and `ExternalSecure`
4. Try to access console

### Screenshots

Connection is using HTTPS. All other calls used HTTPS, except for `http://my.domain/.well-known/openid-configuration`

Browser console:

![image](https://github.com/user-attachments/assets/ebd6692c-10af-4e45-b2e3-dcd1e8f237fd)

Browser network:

![image](https://github.com/user-attachments/assets/2cd56607-c0c9-45b1-ad8f-ba90dbfd4be0)

### Expected behavior

HTTPS is used to retrieve openid configuration and UI console loads.

### Operating System

AWS EKS

### Relevant Configuration

Helm chart values:

```yaml
zitadel:
  configmapConfig:
    ExternalSecure: true
    ExternalDomain: my.domain
    ExternalPort: 443

    TLS:
      Enabled: false
```

Traefik IngressRoute:

```yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`my.domain`)
      services:
        - name: zitadel
          port: 8080
          scheme: h2c
          passHostHeader: true
```

**Comment by xadhatter** [comment]
It appears the url with plain http scheme is being returned when console GETs `https://my.domain/ui/console/assets/environment.json`

```json
{"api":"https://my.domain","issuer":"http://my.domain","clientid":"xxxxxxx"}
```

**Comment by xadhatter** [comment]
Added `x-forwared-proto` header seems to correct the issue:

```yaml
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: add-forwarded-proto-header
spec:
  headers:
    customRequestHeaders:
      x-forwarded-proto: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: zitadel
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`my.domain`)
      middlewares:
        - name: add-forwarded-proto-header
      services:
        - name: zitadel
          port: 8080
          scheme: h2c
          passHostHeader: true

```

I'll leave this ticket open as I am not sure this expected behavior when `ExternalSecure` is set to `true`.

**Comment by taills** [comment]
thanks for your idea.

Caddy:

```
example.com {
    reverse_proxy zitadel:8080 {
        header_up X-Forwarded-Proto "https"
    }
}
```

**Comment by eliobischof** [comment]
@livio-a I think we should use the ExternalSecure property for all environment.json properties instead of reading the proto from the request. Do you agree? 
https://github.com/zitadel/zitadel/blob/3d071fc505b506691f14d33ce971226b6f07384d/internal/api/ui/console/console.go#L120

**Comment by zuffik** [comment]
Happens also when setting `--tlsMode external`. Is there any known workaround?

**Comment by sabin-petru** [comment]
I use nginx proxy manager and fails also, even with x-forwarded-proto

**Comment by m-primo** [comment]
> I use nginx proxy manager and fails also, even with x-forwarded-proto

Same! I really don't understand the concept behind adding an `http` in `environment.json` while the request to `environment.json` made with `https`, like why not use the same scheme? or just put the hostname (without scheme) in the json file and prepend the scheme based on `ZITADEL_EXTERNALSECURE`!

**Comment by blackshady** [comment]
I’m encountering the same issue while using an NGINX Ingress Controller in my Kubernetes setup. Has anyone found a workaround or solution for this problem?

**Comment by k2589** [comment]
Solution/Workaround

We also faced this issue, we have LB in front of nginx ingress, this set of annotations and headers helped:

```
                annotations:
                    nginx.ingress.kubernetes.io/backend-protocol: GRPC
                    nginx.ingress.kubernetes.io/configuration-snippet: |
                      grpc_set_header X-Zitadel-Forwarded "for=$remote_addr;proto=https;";
                    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
```


Reference in code: https://github.com/zitadel/zitadel/blob/HEAD/internal/api/http/middleware/origin_interceptor.go#L50-L73


Sadly, pr from @xadhatter not solving the issue fully, it fixes an issue with environment.json generation, but not a few next checks which leads to errors like `invalid issuer in discovery document expected: https://domain.com current: http://domain.com`

**Comment by chtourou-youssef** [comment]
same problem

**Comment by phurinpat-ka** [comment]
Same issue here.

My current setup is:

Cloudflare (DNS Only)
        ↓
AWS NLB (TLS termination via ACM)
        ↓
Kong
        ↓
ZITADEL

**Comment by nvcnvn** [comment]
In my case, 2 things need to be done:
- set tlsMode flag to external `--tlsMode external`
- add `X-Forwarded-Proto: "https"` headers from above advise

In case if someone using istio, here is how I do it:
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zitadel-vs
  namespace: istio-system
spec:
  hosts:
  - sso.example.com
  http:
  - route:
    - destination:
        host: zitadel.zitadel-prod.svc.cluster.local
        port:
          number: 8080
      headers:
        request:
          set:
            X-Forwarded-Proto: "https"
```
