### ISSUE TITLE
Set branding logo urls via config

### ISSUE THREAD

**Issue by nason** [zitadel/zitadel#8759]
### Preflight Checklist

- [x] I could not find a solution in the existing issues, docs, nor discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I ran into the same issue described in https://github.com/zitadel/zitadel/discussions/8216, and am following the recommendation there to open an improvement issue.

I am automating the deployment of a self-hosted Zidatel and am able to configure almost everything needed via config, except logo URLs.

### Describe your ideal solution

Support for setting these values in config like:

```
DefaultInstance:
    LabelPolicy:
        LogoURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
        IconURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
        LogoDarkURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
        IconDarkURL: https://github.com/mygithubaccount/assets/blob/main/testlogo.png?raw=true
```

### Environment

Self-hosted
