### ISSUE TITLE
[Bug]: zitadel mirror command does not work correctly towards PSQL destination with sslMode verify-all and selfsigned RootCert

### ISSUE THREAD

**Issue by linwalth** [zitadel/zitadel#9120]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.64.1

### Database

PostgreSQL

### Database Version

17.0

### Describe the problem caused by this bug

When mirroring a CRDB backed instance we found that configuring RootCert as a path to the RootCert (CA) file and setting sslMode "verify-all" works fine for the CRDB Source Connection.

When trying to run the mirror command we did find, however, that the same configuration (Self signed Cert, Self-Sign CA) does NOT work with the Postgres Connection. The mirror command could not initiate the mirror process ("x509, certificate signed by unknown authority").

Both CAs (CRDB/PSQL) are self-signed CAs with self-signed Certificates.

The Helm chart mounting this specific PG CA as a ENV var for the PostgreSQL Connection and then running the Zitadel binary via Helm (Init, Setup, Serve) DOES work with the Zitadel binary to serve an instance and get data from the DB backend.

It is surprising that the Mirror command would have trouble doing what the binary generally does not have an issue with.

### To reproduce

1. Create a deployment of Cloud Native PG to mirror into
2. Create a Pod by using the Debian Image to use for mirroring
3. Create the connection Certs in a directory of that pod (or mount them as files)
4. Create a mirroring config using the CRDB as source and the CNPG as destination. 
5. Use rootCert/clientCert/clientKey params and set their paths to the respective files. Define sslMode param as "verify-all"
6. Mirroring Command then will be able to connect to CRDB, but throw error like "x509:certificate signed by unknown authority"

### Expected behavior

Mirroring Command works with ssl connection certs and self signed CA cert between CRDB and Postgresql

### Operating System

Debian

### Relevant Configuration

sslMode: verify-all

**Comment by muhlemmer** [comment]
Reported in #9129:

> ### Preflight Checklist
> * [x]  I could not find a solution in the documentation, the existing issues or discussions[ ]  I have joined the [ZITADEL chat](https://zitadel.com/chat)
> 
> ### Environment
> Self-hosted
> 
> ### Version
> v2.66.1
> 
> ### Database
> PostgreSQL
> 
> ### Database Version
> 16.6
> 
> ### Describe the problem caused by this bug
> Trying to migrate from CockroachDB to Postgres, running the `mirror` command results in an error:
> 
> ```
> zitadel-db-1      | 2025-01-06 10:09:45.802 UTC [2829] ERROR:  unrecognized configuration parameter "enable_multiple_modifications_of_table"
> zitadel-db-1      | 2025-01-06 10:09:45.802 UTC [2829] STATEMENT:  SET enable_multiple_modifications_of_table = on
> zitadel-mirror-1  | time="2025-01-06T10:09:45Z" level=fatal msg="unable to connect to destination database" caller="/home/runner/work/zitadel/zitadel/cmd/mirror/system.go:42" error="ERROR: unrecognized configuration parameter \"enable_multiple_modifications_of_table\" (SQLSTATE 42704)"
> ```
> 
> It is trying to set `enable_multiple_modifications_of_table` on the Postgres connection which fails since this is a CockroachDB parameter.
> 
> The relevant `docker-compose.yml` part:
> 
> ```
>   zitadel-mirror:
>     image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION?ZITADEL_VERSION_MISSING}
>     networks:
>       zitadel:
>     environment:
>     - ZITADEL_MASTERKEY=<openssl rand -hex 16>
>     - ZITADEL_SOURCE_COCKROACH_HOST=zitadel-db-old
>     - ZITADEL_DESTINATION_POSTGRES_HOST=zitadel-db
>     - ZITADEL_DESTINATION_POSTGRES_PORT=5432
>     - ZITADEL_DESTINATION_POSTGRES_DATABASE=zitadel
>     - ZITADEL_DESTINATION_POSTGRES_USER_USERNAME=zitadel
>     - ZITADEL_DESTINATION_POSTGRES_USER_PASSWORD=zitadel
>     - ZITADEL_DESTINATION_POSTGRES_USER_SSL_MODE=disable
>     command:
>     - mirror
>     - --replace
>     - --system
>     - --masterkeyFromEnv
>     - --tlsMode
>     - external
>     depends_on:
>       zitadel-db:
>         condition: service_healthy
>       zitadel-db-old:
>         condition: service_healthy
>       zitadel-setup:
>         condition: service_completed_successfully
> ```
> 
> ### To reproduce
> 1. Have an existing CockroachDB setup
> 2. Define a new Postgres database
> 3. Issue the `init` and `setup` commands for the new database
> 4. Try to `mirror`
> 
> ### Screenshots
> _No response_
> 
> ### Expected behavior
> The `ZITADEL_DESTINATION_POSTGRES_HOST` environment variable should instruct ZITADEL to use Postgres and not use the CockroachDB connection code which sets `enable_multiple_modifications_of_table`.
> 
> ### Operating System
> _No response_
> 
> ### Relevant Configuration
> _No response_
> 
> ### Additional Context
> _No response_

**Comment by Trickfilm400** [comment]
I've came across this issue (`FATA[0000] unable to connect to destination database     caller="/home/runner/work/zitadel/zitadel/cmd/mirror/system.go:42" error="ERROR: unrecognized configuration parameter \"enable_multiple_modifications_of_table\" (SQLSTATE 42704)"`) using no SSL

but I found this could be fixed in #9509 maybe?

**Comment by liranco** [comment]
I had the same issue, which was caused from cockroachdb's version being too low (v22.2). After upgrading to v25.1 the mirror works

**Comment by verymilan** [comment]
That would be fun as Cockroach support was removed with v3 and this seems to be part of a v3 release

**Comment by Trickfilm400** [comment]
I managed to upgrade to v3 be using the following workaround: 

You can use the v3 binary to copy the data of your instance
I did it like this:
0. Upgrade your zitadel instance to the newest version below v3
1. Stop the existing instance
2. Use the v3 binary to stup the destination database
3. The the same v3 binary to mirror the database data
4. Start the zitatel instance using the v3 version (like the v3 docker image)

In this way, the v3 binary used to setup the database handles some migrations I believe

**Comment by kkrime** [comment]
@linwalth I'm unable to reproduce your issue.

I set up a CRDB as the source and a PRDB as the destination, both used self-signing CA and I managed to mirror successfully.

Are there any other details about your setup you're able to provide me with? Maybe like the exact config files

Also, I noticed in your description you said 


> When trying to run the mirror command we did find, however, that the same configuration (Self signed Cert, Self-Sign CA) does NOT work with the Postgres Connection. The mirror command could not initiate the mirror process ("x509, certificate signed by unknown authority").


When you said `(Self signed Cert, Self-Sign CA) ` specifically what certificate are you referring to when you said `Self signed Cert` are you referring to any other certificates that are self-signed other than that of the CA?

**Comment by linwalth** [comment]
We already mirrored the DB with v2.65.10 and we switched over to CNPG, so in regards to us, this issue can be closed.

This was our mirroring Config:

```
Source:
  cockroach:
    Host: crdb-public.zitadel
    Port: 26257
    Database: zitadel
    MaxOpenConns: 15
    MaxIdleConns: 10
    MaxConnLifetime: 30m
    MaxConnIdleTime: 5m
    Options: ""
    User:
      Username: root
      SSL:
        Mode: verify-full
        RootCert: "/mnt/crdb-certs/ca.crt"
        Cert:  "/mnt/crdb-certs/tls.crt"
        Key: "/mnt/crdb-certs/tls.key"

Destination:
  postgres:
    Host: cnpg-cluster-zitadel-rw.zitadel
    Port: 5432
    Database: zitadel
    MaxOpenConns: 15
    MaxIdleConns: 10
    MaxConnLifetime: 1h
    MaxConnIdleTime: 5m
    Options: ""
    User:
      Username: zitadel
      Password: "REDACTED"
      SSL:
        Mode: verify-full
        RootCert: "/mnt/cnpg-cluster-zitadel-ca/ca.crt"
        Cert: ""
        Key: ""

EventBulkSize: 100000
MaxAuthRequestAge: 720h

Projections:
  ConcurrentInstances: 10
  EventBulkLimit: 5000

Auth:
  Spooler:
    BulkLimit: 5000

Admin:
  Spooler:
    BulkLimit: 1000

Log:
  Level: debug
```
