### ISSUE TITLE
[Bug]: mirror command setting enable_multiple_modifications_of_table on Postgres destination

### ISSUE THREAD

**Issue by michelkaeser** [zitadel/zitadel#9129]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.66.1

### Database

PostgreSQL

### Database Version

16.6

### Describe the problem caused by this bug

Trying to migrate from CockroachDB to Postgres, running the `mirror` command results in an error:

```
zitadel-db-1      | 2025-01-06 10:09:45.802 UTC [2829] ERROR:  unrecognized configuration parameter "enable_multiple_modifications_of_table"
zitadel-db-1      | 2025-01-06 10:09:45.802 UTC [2829] STATEMENT:  SET enable_multiple_modifications_of_table = on
zitadel-mirror-1  | time="2025-01-06T10:09:45Z" level=fatal msg="unable to connect to destination database" caller="/home/runner/work/zitadel/zitadel/cmd/mirror/system.go:42" error="ERROR: unrecognized configuration parameter \"enable_multiple_modifications_of_table\" (SQLSTATE 42704)"
```

It is trying to set `enable_multiple_modifications_of_table` on the Postgres connection which fails since this is a CockroachDB parameter.

The relevant `docker-compose.yml` part:

```
  zitadel-mirror:
    image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION?ZITADEL_VERSION_MISSING}
    networks:
      zitadel:
    environment:
    - ZITADEL_MASTERKEY=<openssl rand -hex 16>
    - ZITADEL_SOURCE_COCKROACH_HOST=zitadel-db-old
    - ZITADEL_DESTINATION_POSTGRES_HOST=zitadel-db
    - ZITADEL_DESTINATION_POSTGRES_PORT=5432
    - ZITADEL_DESTINATION_POSTGRES_DATABASE=zitadel
    - ZITADEL_DESTINATION_POSTGRES_USER_USERNAME=zitadel
    - ZITADEL_DESTINATION_POSTGRES_USER_PASSWORD=zitadel
    - ZITADEL_DESTINATION_POSTGRES_USER_SSL_MODE=disable
    command:
    - mirror
    - --replace
    - --system
    - --masterkeyFromEnv
    - --tlsMode
    - external
    depends_on:
      zitadel-db:
        condition: service_healthy
      zitadel-db-old:
        condition: service_healthy
      zitadel-setup:
        condition: service_completed_successfully
```

### To reproduce

1. Have an existing CockroachDB setup
2. Define a new Postgres database
3. Issue the `init` and `setup` commands for the new database
4. Try to `mirror`

### Expected behavior

The `ZITADEL_DESTINATION_POSTGRES_HOST` environment variable should instruct ZITADEL to use Postgres and not use the CockroachDB connection code which sets `enable_multiple_modifications_of_table`.
