### ISSUE TITLE
[Bug]: Token verification failure when accessing system API

### ISSUE THREAD

**Issue by sereneshikari** [zitadel/zitadel#9494]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.71.1

### Database

PostgreSQL

### Database Version

15.4.0

### Describe the problem caused by this bug

When I access the Zitadel system API, I see the following error message in the logs:
```
time="2025-03-07T18:00:58Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:283" error="ID=APP-ASdgg Message=invalid token"
time="2025-03-07T18:00:58Z" level=warning msg="token verifier repo: verify JWT access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:287" error="issuer does not match: Expected: http://127.0.0.1.sslip.io:8080, got: system-user-1"
time="2025-03-07T18:00:58Z" level=warning msg="authz: verify access token" caller="/home/runner/work/zitadel/zitadel/internal/api/authz/context.go:112" error="ID=APP-Reb32 Message=invalid token" org_domain= org_id=
```
Note that the response itself is successful

### To reproduce

1. Follow the steps in [this guide](https://zitadel.com/docs/guides/integrate/zitadel-apis/access-zitadel-system-api) to create a user that can access the system API
2. Follow the steps in [this guide](https://github.com/zitadel/zitadel-charts/tree/main/examples/1-postgres-insecure) to deploy Postgres (insecure) and Zitadel. You need to pass additional values as mentioned in the guide from step 1, and to use the latest version of Zitadel. Your additional values file should look like this:
```yaml
zitadel:
  configmapConfig:
    SystemAPIUsers:
    - system-user-1:
        KeyData: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEwek5zUHB4aEkxc1Y3anpjMDZPSgplMUZmc0xoMGtOOWNaMi81NDFSQlpXTTd2VkFTM0JNOUV5TjEwOFZ5OGttaFJNYXI2cXhtUW9jeXRNQVRqTU93CmdYNy90MDZIMzJScm0rLzlyZjhEZ1R2YWhXRTBpMkdOWWc2Y3h4bk81dVcvR1JuS1FLTHpsdlAxcFFqcUV6QW0Kak9CSGVBak5WMzN1TkxDYWFJYTNNZFZNZUY3ZnVRbGNCQjBoRzNJZUVWYktCRTd1RFB3RWVVYVZkRTdlZEgraAozUHNjUTBPY21iMUZqUlhmSzdqdHZOMzJ2RlhDbGk4UXhONXJMeW5sSlhGQ2hKUG55aXVyYWZQMktPVEo5WjFECkdsZnUwN09ubDZYQVo3b2tWTlVsU1BXM1FzajNZYURheGh5dzNMYkFSYmpJQVpEcU80VlA0akgxS0FIMTZGdzcKUFFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

image:
  tag: "v2.71.1"
```
3. Port forward the Zitadel service as mentioned in the guide from step 2. Make a request to the system API as mentioned in the guide from step 1. You should get a successful response like below:
```json
{
  "details": {
    "totalResult": "2"
  },
  "result": [
    {
      "id": "310166042087260169",
      "details": {
        "sequence": "28",
        "creationDate": "2025-03-07T17:42:49.439801Z",
        "changeDate": "2025-03-07T17:42:49.439801Z",
        "resourceOwner": "310166042087260169"
      },
      "state": "STATE_RUNNING",
      "name": "ZITADEL",
      "version": "v2.71.1",
      "domains": [
        {
          "details": {
            "sequence": "32",
            "creationDate": "2025-03-07T17:42:49.439801Z",
            "changeDate": "2025-03-07T17:42:49.439801Z",
            "resourceOwner": "310166042087260169"
          },
          "domain": "zitadel-eufhrd.127.0.0.1.sslip.io",
          "generated": true
        },
        {
          "details": {
            "sequence": "32",
            "creationDate": "2025-03-07T17:42:49.439801Z",
            "changeDate": "2025-03-07T17:42:49.439801Z",
            "resourceOwner": "310166042087260169"
          },
          "domain": "127.0.0.1.sslip.io",
          "primary": true
        }
      ]
    }
  ]
}
```
4. However, if you check the Zitadel pod logs, you should see the following error:
```
time="2025-03-07T18:00:58Z" level=warning msg="token verifier repo: decrypt access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:283" error="ID=APP-ASdgg Message=invalid token"
time="2025-03-07T18:00:58Z" level=warning msg="token verifier repo: verify JWT access token" caller="/home/runner/work/zitadel/zitadel/internal/authz/repository/eventsourcing/eventstore/token_verifier.go:287" error="issuer does not match: Expected: http://127.0.0.1.sslip.io:8080, got: system-user-1"
time="2025-03-07T18:00:58Z" level=warning msg="authz: verify access token" caller="/home/runner/work/zitadel/zitadel/internal/api/authz/context.go:112" error="ID=APP-Reb32 Message=invalid token" org_domain= org_id=
```

### Expected behavior

There should be no verification failures, and no errors should be logged in Zitadel

### Operating System

Device: Windows
OS: Windows 10
Browser: Microsoft Edge
Version: 133.0.3065.92 (Official build) (64-bit) 

### Additional Context

This may be a related issue but it's unclear what the original poster wanted: https://github.com/zitadel/zitadel/issues/7937
