### ISSUE TITLE
[Bug]: /app/zitadel ready command performs HTTPs client connection with TLS disabled

### ISSUE THREAD

**Issue by ArnauAregall** [zitadel/zitadel#9495]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.71.1, v3.0.0-rc.1

### Database

PostgreSQL

### Database Version

postgres:16-alpine

### Describe the problem caused by this bug

`/app/zitadel ready` command performs HTTPs client connection with TLS disabled`.

As far as I understood with `start-from-init --tlsMode disabled` and `TLS.Enabled: false` in the configuration should fully disable HTTPs connections.

However seems the following line is not honoring it https://github.com/zitadel/zitadel/blob/bae45ee159e5d4c8100aa40e6ef99eb31354dadd/cmd/ready/ready.go#L31 

````
2025-03-07 20:19:35   _____  ___   _____      _      ____    _____   _
2025-03-07 20:19:35  |__  / |_ _| |_   _|    / \    |  _ \  | ____| | |
2025-03-07 20:19:35    / /   | |    | |     / _ \   | | | | |  _|   | |
2025-03-07 20:19:35   / /_   | |    | |    / ___ \  | |_| | | |___  | |___
2025-03-07 20:19:35  /____| |___|   |_|   /_/   \_\ |____/  |_____| |_____|
2025-03-07 20:19:35 
2025-03-07 20:19:35  ===============================================================
2025-03-07 20:19:35 
2025-03-07 20:19:35  Version            : v2.71.1
2025-03-07 20:19:35  TLS enabled        : false
2025-03-07 20:19:35  External Secure    : false
2025-03-07 20:19:35  Machine Id Method  : Private Ip
2025-03-07 20:19:35  Console URL        : http://localhost:8080/ui/console
2025-03-07 20:19:35  Health Check URL   : http://localhost:8080/debug/healthz
2025-03-07 20:19:35 
2025-03-07 20:19:35  Warning: you're using plain http without TLS. Be aware this is 
2025-03-07 20:19:35  not a secure setup and should only be used for test systems.         
2025-03-07 20:19:35  Visit: https://zitadel.com/docs/self-hosting/manage/tls_modes    
2025-03-07 20:19:35 
2025-03-07 20:19:35  ===============================================================
````

Healthcheck inside the Docker container:

```
/app/zitadel ready
WARN[0000] ready check failed                            caller="/home/runner/work/zitadel/zitadel/cmd/ready/ready.go:38" error="Get \"https://localhost:8080/debug/ready\": http: server gave HTTP response to HTTPS client"
```

### To reproduce

**compose.yml**
```yml
services:
  zitadel:
    image: ghcr.io/zitadel/zitadel:v2.71.1
    restart: always
    ports:
      - "8080:8080"
    networks:
      - "zitadel"
    command: 'start-from-init --tlsMode disabled --masterkey "MasterkeyNeedsToHave32Characters" --config /zitadel-config.yaml --config /zitadel-secrets.yaml --steps /zitadel-init-steps.yaml'
    volumes:
      - "./compose/zitadel/local-zitadel-admin-sa.pat:/zitadel-admin-sa.pat"
      - "./compose/zitadel/local-zitadel-config.yaml:/zitadel-config.yaml"
      - "./compose/zitadel/local-zitadel-secrets.yaml:/zitadel-secrets.yaml"
      - "./compose/zitadel/local-zitadel-init-steps.yaml:/zitadel-init-steps.yaml"
    depends_on:
      - zitadel_database
    healthcheck:
      test: ["CMD", "/app/zitadel", "ready"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  zitadel_database:
    image: postgres:16-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=postgres
    networks:
      - 'zitadel'
    volumes:
      - 'data:/var/lib/postgresql/data:rw'
````
```bash
docker compose up
```

```bash
docker inspect --format '{{json .State.Health}}' zitadel | jq

{
  "Status": "unhealthy",
  "FailingStreak": 14,
  "Log": [
    {
      "Start": "2025-03-07T19:21:36.910487596Z",
      "End": "2025-03-07T19:21:37.163806638Z",
      "ExitCode": 1,
      "Output": "time=\"2025-03-07T19:21:37Z\" level=warning msg=\"ready check failed\" caller=\"/home/runner/work/zitadel/zitadel/cmd/ready/ready.go:38\" error=\"Get \\\"https://localhost:8080/debug/ready\\\": http: server gave HTTP response to HTTPS client\"\n"
    },
    {
      "Start": "2025-03-07T19:21:47.168051087Z",
      "End": "2025-03-07T19:21:47.42293142Z",
      "ExitCode": 1,
      "Output": "time=\"2025-03-07T19:21:47Z\" level=warning msg=\"ready check failed\" caller=\"/home/runner/work/zitadel/zitadel/cmd/ready/ready.go:38\" error=\"Get \\\"https://localhost:8080/debug/ready\\\": http: server gave HTTP response to HTTPS client\"\n"
    },
    {
      "Start": "2025-03-07T19:21:57.425654883Z",
      "End": "2025-03-07T19:21:57.669025842Z",
      "ExitCode": 1,
      "Output": "time=\"2025-03-07T19:21:57Z\" level=warning msg=\"ready check failed\" caller=\"/home/runner/work/zitadel/zitadel/cmd/ready/ready.go:38\" error=\"Get \\\"https://localhost:8080/debug/ready\\\": http: server gave HTTP response to HTTPS client\"\n"
    },
    {
      "Start": "2025-03-07T19:22:07.67095168Z",
      "End": "2025-03-07T19:22:07.914647055Z",
      "ExitCode": 1,
      "Output": "time=\"2025-03-07T19:22:07Z\" level=warning msg=\"ready check failed\" caller=\"/home/runner/work/zitadel/zitadel/cmd/ready/ready.go:38\" error=\"Get \\\"https://localhost:8080/debug/ready\\\": http: server gave HTTP response to HTTPS client\"\n"
    },
    {
      "Start": "2025-03-07T19:22:17.91943242Z",
      "End": "2025-03-07T19:22:18.163827379Z",
      "ExitCode": 1,
      "Output": "time=\"2025-03-07T19:22:18Z\" level=warning msg=\"ready check failed\" caller=\"/home/runner/work/zitadel/zitadel/cmd/ready/ready.go:38\" error=\"Get \\\"https://localhost:8080/debug/ready\\\": http: server gave HTTP response to HTTPS client\"\n"
    }
  ]
}
````

### Expected behavior

With TLS disabled the `/app/zitadel ready` should perform a request using scheme `http://` and not `https://`.
