### ISSUE TITLE
[Bug]: start-from-setup fails with relation "eventstore.events" does not exist on clean Postgres database

### ISSUE THREAD

**Issue by tomers** [zitadel/zitadel#9728]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

zitadel:v3.0.0-rc.1-debug (also occurs on v2.43.5)

### Database

PostgreSQL

### Database Version

postgres:15-alpine

### Describe the problem caused by this bug

# 📝 Description:
When running ZITADEL using start-from-setup against a clean, empty Postgres database (no volumes, no preinit), setup fails during the very first migration (01_tables) with:

```vbnet
migration failed ... unable to filter events Parent=(ERROR: relation "eventstore.events" does not exist)
This occurs even with latest stable version v2.43.5, using the documented Docker environment configuration.
```

### To reproduce

# ✅ Steps to Reproduce:
Docker Compose file (minimal, clean setup):

```yaml
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: zitadel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d zitadel']
      interval: 5s
      timeout: 5s
      retries: 5

  zitadel:
    image: ghcr.io/zitadel/zitadel:v2.43.5
    command: start-from-setup --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode disabled
    depends_on:
      db:
        condition: service_healthy
    environment:
      ZITADEL_DATABASE_POSTGRES_HOST: db
      ZITADEL_DATABASE_POSTGRES_PORT: 5432
      ZITADEL_DATABASE_POSTGRES_DATABASE: zitadel
      ZITADEL_DATABASE_POSTGRES_USER_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_USER_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE: disable
      ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD: postgres
      ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE: disable
      ZITADEL_EXTERNALSECURE: false
```

### Run steps:

```bash
docker compose down -v --remove-orphans
docker compose up --force-recreate
```

# 💥 Error:
```pgsql
zitadel  | time="2025-04-08T18:50:22Z" level=fatal msg="migration failed" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:135" error="ID=SQL-KyeAx Message=unable to filter events Parent=(ERROR: relation \"eventstore.events\" does not exist (SQLSTATE 42P01))" name=01_tables
```

This happens even though:

- The DB is 100% clean (no volumes)

- Default Postgres is used (15-alpine)

- Admin and user credentials are provided

- Postgres healthcheck passes before setup starts

# ✅ Expected Behavior:
ZITADEL should:

- Successfully run all migrations in start-from-setup

- Create the eventstore.events table during the migration

- Not attempt to query a table that doesn’t exist yet

# ❓Extra Notes:
`start-from-init` works fine in the same environment

This appears to be a regression or ordering issue in the initial setup migrations

Verified reproducible in both `v2.43.4` and `v2.43.5`

# 🙏 Help
We’d love to use `start-from-setup` in a CI/test environment with Testcontainers, but this blocks full automation. Please advise or patch if this is a known issue.
