### ISSUE TITLE
[Bug]: New deployment fails migration when defining Restrictions AllowedLanguages

### ISSUE THREAD

**Issue by D1StrX** [zitadel/zitadel#9787]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

v2.71.7

### Database

PostgreSQL

### Database Version

17

### Describe the problem caused by this bug

When defining `Restrictions.AllowedLanguages` a fresh dockerized install of Zitadel fails with the error below. It is working without defining restrictions.

```yaml
FirstInstance:
  # If set to true zitadel is setup without initial data
  Skip: false
  DefaultLanguage: en
...
DefaultInstance:
  InstanceName: ZITADEL
  DefaultLanguage: en
  Restrictions:
    AllowedLanguages:
      - en
```

Also fails when defining:
```
  Restrictions:
    AllowedLanguages:
      - en
      - fr
      - de
```

**Error**
```
time="2025-04-22T21:32:37Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=03_default_instance
time="2025-04-22T21:32:38Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:68" error="ID=COMMAND-L0m2u Message=Errors.Restrictions.DefaultLanguageMustBeAllowed Parent=(ID=LANG-3M9f2 Message=Errors.Language.Undefined)" name=03_default_instance
```

### To reproduce

Fresh self-hosted Zitadel installation in a Docker container, and define the language restriction.
