### ISSUE TITLE
[Bug]: Zitadel Instance using Docker

### ISSUE THREAD

**Issue by abhaybhargav** [zitadel/zitadel#9896]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [ ] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

3.0.4

### Database

PostgreSQL

### Database Version

Postgres 17

### Describe the problem caused by this bug

I am using Zitadel with Docker compose based on the example I've seen [here](https://zitadel.com/docs/self-hosting/deploy/compose#docker-compose-with-service-account)

I want to start zitadel with a machine key instead of with a human user. 

When I run it with `--tlsMode disabled` and ENV-var `ZITADEL_EXTERNALSECURE: false` it works fine

However, when I try and run it on a server with TLS, etc enabled. the container restarts with some unique key constraint errors. 

I have tried deleting the images, removing volumes, reconstructing the entire deployment to no avail. What am I doing wrong? Is it a possible bug?

Here's my docker compose file

```
services:
  zitadel:
    restart: 'always'
    network_mode: host
    image: 'ghcr.io/zitadel/zitadel:latest'
    command: 'start-from-init --masterkey "MasterkeyNeedsToHave32Characters" --tlsMode external'
    environment:
      - ZITADEL_DATABASE_POSTGRES_HOST=localhost
      - ZITADEL_DATABASE_POSTGRES_PORT=5432
      - ZITADEL_DATABASE_POSTGRES_DATABASE=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_USERNAME=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_PASSWORD=zitadel
      - ZITADEL_DATABASE_POSTGRES_USER_SSL_MODE=disable
      - ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD=postgres
      - ZITADEL_DATABASE_POSTGRES_ADMIN_SSL_MODE=disable
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALDOMAIN=blah.blah.com
      - ZITADEL_EXTERNALPORT=8080
      - ZITADEL_SESSION_UI_COOKIE_CHECK_USER_AGENT=false
      - ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/machinekey/zitadel-admin-sa.json
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=zitadel-admin-sa
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Admin
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1

    depends_on:
      db:
        condition: 'service_healthy'
    volumes:
      - ./machinekey:/machinekey

  db:
    image: postgres:17-alpine
    restart: always
    network_mode: host
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: zitadel
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d zitadel -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 20s
```

P.S - this works fine with podman on macOS. But on a linux server with Docker, this is not working for some reason

### To reproduce

1. Load this as a docker-compose file
2. run `docker compose up`
