### ISSUE TITLE
[Bug]: Migration from v2.71.4 to v2.71.5 fails (goal: v2.71.10 for v3 mirror migration)

### ISSUE THREAD

**Issue by Duneyr** [zitadel/zitadel#9960]
### Preflight Checklist

- [x] I could not find a solution in the documentation, the existing issues or discussions
- [x] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Environment

Self-hosted

### Version

2.71.4

### Database

CockroachDB (Zitadel v2)

### Database Version

v25.1.4-cockroach-cloud

### Describe the problem caused by this bug

First of all: Thank your for this amazing piece of software. I am especially impressed with the now well working tofu / terraform capabilities and the relatively low maintenance.

Currently I use Zitadel in docker-compose. My goal is to move from cloud cockroachdb to self-hosted postgres with zitadel cli mirror. I had issues with using mirror so I decided it is probably a good idea to update  to the most recent <v3 version, which seems to be `2.71.10`

During startup of 2.71.5 this pops up, Zitadel fails to start:

```
time="2025-05-25T09:26:24Z" level=info msg="initialization started" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/init.go:74"
time="2025-05-25T09:26:25Z" level=info msg="verify user" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_user.go:40" username=zitadeluser2
time="2025-05-25T09:26:25Z" level=info msg="verify database" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_database.go:40" database=defaultdb
time="2025-05-25T09:26:25Z" level=info msg="verify grant" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_grant.go:35" database=defaultdb user=zitadeluser2
time="2025-05-25T09:26:25Z" level=info msg="verify settings" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_settings.go:41" database=defaultdb user=zitadeluser2
time="2025-05-25T09:26:25Z" level=info msg="verify zitadel" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:85" database=defaultdb
time="2025-05-25T09:26:25Z" level=info msg="verify system" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:46"
time="2025-05-25T09:26:25Z" level=info msg="verify encryption keys" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:51"
time="2025-05-25T09:26:25Z" level=info msg="verify projections" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:56"
time="2025-05-25T09:26:25Z" level=info msg="verify eventstore" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:61"
time="2025-05-25T09:26:25Z" level=info msg="verify events tables" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:66"
time="2025-05-25T09:26:25Z" level=info msg="verify system sequence" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:71"
time="2025-05-25T09:26:25Z" level=info msg="verify unique constraints" caller="/home/runner/work/zitadel/zitadel/cmd/initialise/verify_zitadel.go:76"
time="2025-05-25T09:26:25Z" level=info msg="setup started" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:103"
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=14_events_push
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=40_init_push_func_v4
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=01_tables
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=02_assets
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=28_add_search_table
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=31_add_aggregate_index_to_fields
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=46_init_permission_functions
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=03_default_instance
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=05_last_failed
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=06_resource_owner_columns
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=07_logstore
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=08_auth_token_indexes
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=12_auth_users_otp_columns
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=13_fix_quota_constraints
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=15_current_projection_state
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=16_unique_constraint_lower
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=17_add_offset_col_to_current_states
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=19_add_current_sequences_index
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=20_add_by_user_index_on_session
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=22_active_instance_events_index
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=23_correct_global_unique_constraints
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=24_add_actor_col_to_auth_tokens
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=26_auth_users3
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=29_init_fields_for_project_grant
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=30_fill_fields_for_org_domain_verified
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=34_add_cache_schema
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=35_add_position_to_index_es_wm
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=36_fill_v3_milestones
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=38_back_channel_logout_notification_start_
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=44_replace_current_sequences_index
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=43_correct_project_owners
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=47_fill_membership_fields
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=49_init_permitted_orgs_function
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=50_idp_templates6_add_use_pkce
time="2025-05-25T09:26:26Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=51_idp_templates6_add_root_ca
time="2025-05-25T09:26:27Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=config_change
time="2025-05-25T09:26:27Z" level=info msg="verify migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:43" name=projection_tables
time="2025-05-25T09:26:27Z" level=info msg="starting migration" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:66" name=projection_tables
time="2025-05-25T09:26:28Z" level=error msg="migration failed" caller="/home/runner/work/zitadel/zitadel/internal/migration/migration.go:68" error="ERROR: savepoint \"exec_stmt\" does not exist (SQLSTATE 3B001)" name=projection_tables
time="2025-05-25T09:26:28Z" level=fatal msg="unable to migrate repeatable step" caller="/home/runner/work/zitadel/zitadel/cmd/setup/setup.go:302" code=3B001 detail= error="ERROR: savepoint \"exec_stmt\" does not exist (SQLSTATE 3B001)" hint= message="savepoint \"exec_stmt\" does not exist" name=projection_tables severity=ERROR
```

No amount of:
- db restore
- `start`
- `setup cleanup` ("no migration failed" <-  well ...)
- `setup`

will make it work. DB restore to 2.71.4 times and running 2.71.4 thankfully works though.

### To reproduce

My past work with zitadel on the non-database side was **basically the docker-compose config below** and tofu for maintaining consistent app-configs:

**I increased the image tag**, restarted the container and checked the logs for generic and especially migration errors. In case I "jumped to far", I rolled back the database and made smaller migration steps which normally worked nicely. (In recent times I became more conservative in version jumps.)

**See relevant config section for docker-compose code.**

### Expected behavior

Migration from` v2.71.4` to `v2.71.5` should succeed. Service should start.
Migration from` v2.71.4` to `v2.71.10` should succeed. Service should start.

### Operating System

```
Docker version 20.10.5+dfsg1, build 55c4c88
docker-compose version 1.25.0, build unknown
on Debian GNU/Linux 11 (bullseye)
```

### Relevant Configuration

```
  zitadel:
    restart: 'always'
    image: 'ghcr.io/zitadel/zitadel:v2.71.4'
    command: 'start-from-init --masterkey "${ZITADEL_MASTERKEY}" --tlsMode external'
    environment:
      - ZITADEL_DATABASE_COCKROACH_HOST=${ZITADEL_DATABASE_COCKROACH_HOST}
      - ZITADEL_DATABASE_COCKROACH_PORT=${ZITADEL_DATABASE_COCKROACH_PORT}
      - ZITADEL_DATABASE_COCKROACH_DATABASE=${ZITADEL_DATABASE_COCKROACH_DATABASE}
      - ZITADEL_DATABASE_COCKROACH_ADMIN_USERNAME=<REDACTED>
      - ZITADEL_DATABASE_COCKROACH_ADMIN_PASSWORD=${ZITADEL_DATABASE_COCKROACH_ADMIN_PASSWORD}
      - ZITADEL_DATABASE_COCKROACH_ADMIN_SSL_MODE=verify-full
      - ZITADEL_DATABASE_COCKROACH_ADMIN_SSL_ROOTCERT=/cockroach-root-ca.crt
      - ZITADEL_DATABASE_COCKROACH_USER_USERNAME=zitadeluser2
      - ZITADEL_DATABASE_COCKROACH_USER_PASSWORD=${ZITADEL_DATABASE_COCKROACH_USER_PASSWORD}
      - ZITADEL_DATABASE_COCKROACH_USER_SSL_MODE=verify-full
      - ZITADEL_DATABASE_COCKROACH_USER_SSL_ROOTCERT=/cockroach-root-ca.crt
      - ZITADEL_EXTERNALSECURE=true
      - ZITADEL_EXTERNALPORT=443
      - ZITADEL_EXTERNALDOMAIN=<REDACTED>

      - ZITADEL_DEFAULTINSTANCE_DEFAULTLANGUAGE=de
      - ZITADEL_FIRSTINSTANCE_DEFAULTLANGUAGE=de

      # probably ignored because machine user is prefered
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_USERNAME=<REDACTED>
      - ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORD=<REDACTED>

      # enable terraform access (get token)
      # - ZITADEL_LOG_LEVEL=debug
      - ZITADEL_FIRSTINSTANCE_MACHINEKEYPATH=/home/zitadel/zitadel-admin-sa.json
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_USERNAME=zitadel-admin-sa
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINE_NAME=Admin
      - ZITADEL_FIRSTINSTANCE_ORG_MACHINE_MACHINEKEY_TYPE=1

    volumes:
      - /root/cockroach-root-ca.crt:/cockroach-root-ca.crt:ro
      - ./zitadel-admin-sa-mount-dir:/home/zitadel
    ports:
      - 127.0.0.1:8070:8080
```
